const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),{parseMidi,writeMidi}=require('midi-file');const dir=__dirname,source=fs.readFileSync('reports/gibran-alcocer-harmony-audit-2026-10-04/transkun/idea-15.mid'),m=parseMidi(source),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function notes(m){return m.tracks.flatMap(tr=>{let tick=0;const active=new Map(),ns=[];for(const e of tr){tick+=e.deltaTime;if(e.type==='noteOn'&&e.velocity){assert(!active.has(e.noteNumber),'Overlapping same pitch');active.set(e.noteNumber,{start:tick,pitch:e.noteNumber,velocity:e.velocity});}else if(e.type==='noteOff'||e.type==='noteOn'&&!e.velocity){const n=active.get(e.noteNumber);assert(n);ns.push({...n,end:tick});active.delete(e.noteNumber);}}assert.equal(active.size,0);return ns;}).sort((a,b)=>a.start-b.start||a.pitch-b.pitch);}
const controllers=[];m.tracks.forEach(tr=>{let tick=0;tr.forEach(e=>{tick+=e.deltaTime;if(e.type==='controller')controllers.push({tick,event:{...e}});});});
const ns=notes(m),old=notes(parseMidi(Buffer.from(JSON.parse(fs.readFileSync('src/midis/eX97GlcN8uB2C0p6Zg9r.json')).blobBase64,'base64'))),comp=JSON.parse(fs.readFileSync('reports/gibran-alcocer-harmony-audit-2026-10-04/post-fix/comparisons/idea-15---gibran-alcocer.json'));
const measures=[0];for(let bar=2;bar<=109;bar++){const approx=comp.summary.measure_windows.find(x=>x.measure===bar).audio_time;const pitches=old.filter(n=>n.start===(bar-1)*1440).map(n=>n.pitch);let candidates=ns.filter(n=>pitches.includes(n.pitch)&&Math.abs(n.start/1920-approx)<.48&&n.start/1920>measures.at(-1)+.45);if(candidates.some(n=>n.pitch<60))candidates=candidates.filter(n=>n.pitch<60);assert(candidates.length,'No anchor for '+bar);candidates.sort((a,b)=>Math.abs(a.start/1920-approx)-Math.abs(b.start/1920-approx));measures.push(candidates[0].start/1920);}measures.push(measures.at(-1)+(measures.at(-1)-measures.at(-2)));assert.equal(measures.length,110);assert(measures.every((t,i)=>!i||t>measures[i-1]));
for(let i=2;i<measures.length-1;i++){if(measures[i]-measures[i-1]<.85||measures[i+1]-measures[i]>1.25){const target=(measures[i-1]+measures[i+1])/2;const close=ns.filter(n=>Math.abs(n.start/1920-target)<.1).sort((a,b)=>Math.abs(a.start/1920-target)-Math.abs(b.start/1920-target));assert(close.length);measures[i]=close[0].start/1920;}}
const priorAnalysis=JSON.parse(fs.readFileSync('src/corpus/analyses.json'))['f/idea-15---gibran-alcocer'];const options={version:1,legato:true,measures,beatsPerMeasure:3,gridSubdivisions:6,analysis:{modulations:priorAnalysis.modulations,phrasePatch:priorAnalysis.phrasePatch,sections:priorAnalysis.sections,comment:'',tags:[],form:{}}};const endTick=212501;
const meta=m.tracks[0].filter(e=>e.type!=='endOfTrack');meta.push({deltaTime:0,meta:true,type:'text',text:'RAWL_DISPLAY:'+JSON.stringify(options)},{deltaTime:endTick,meta:true,type:'endOfTrack'});
function voice(n){const bar=Math.max(1,measures.findIndex(t=>t>n.start/1920));if(bar>=92){if([98,99,106,107].includes(bar)&&n.pitch===59)return 1;return n.pitch<60?0:n.pitch<73?1:2;}if(n.pitch<=64)return 0;return (bar>=20&&bar<=35||bar>=56&&bar<=71)?1:2;}
const names=['Transkun / Bass and accompaniment','Transkun / Arpeggios','Transkun / Melody and overdub'];const tracks=names.map((name,ch)=>{const events=[{t:0,e:{meta:true,type:'trackName',text:name}},{t:0,e:{channel:ch,type:'programChange',programNumber:0}}];for(const c of controllers)events.push({t:c.tick,e:{...c.event,channel:ch}});for(const n of ns.filter(n=>voice(n)===ch))events.push({t:n.start,e:{channel:ch,type:'noteOn',noteNumber:n.pitch,velocity:n.velocity}},{t:n.end,e:{channel:ch,type:'noteOff',noteNumber:n.pitch,velocity:0}});events.sort((a,b)=>a.t-b.t||(a.e.type==='noteOff'?-1:0)-(b.e.type==='noteOff'?-1:0));let t=0;const tr=events.map(x=>{const e={...x.e,deltaTime:x.t-t};t=x.t;return e;});tr.push({deltaTime:endTick-t,meta:true,type:'endOfTrack'});return tr;});const out=Buffer.from(writeMidi({header:{...m.header,numTracks:4},tracks:[meta,...tracks]}));assert.deepEqual(notes(parseMidi(out)),ns);assert.equal(ns.length,947);const checkControllers=parseMidi(out).tracks.slice(1).map(tr=>{let tick=0;return tr.flatMap(e=>{tick+=e.deltaTime;return e.type==='controller'?[[tick,e.controllerType,e.value]]:[]});});checkControllers.forEach(cc=>assert.deepEqual(cc,controllers.map(c=>[c.tick,c.event.controllerType,c.event.value])));fs.writeFileSync(dir+'/idea-15-transkun-visual-legato.mid',out);fs.writeFileSync(dir+'/display.json',JSON.stringify(options,null,2));fs.writeFileSync(dir+'/manifest.json',JSON.stringify({sourceSha256:sha(source),outputSha256:sha(out),noteCount:ns.length,sourceControllerCount:controllers.length,pedalControllerCount:controllers.filter(c=>c.event.controllerType===64).length,voices:names.map((name,ch)=>({name,count:ns.filter(n=>voice(n)===ch).length})),preserved:'All pitches, velocities, note-on ticks, note-off ticks, tempo and playback duration',measureCount:109},null,2));console.log('Prepared',ns.length,'unaltered notes. Measure duration range:',Math.min(...measures.slice(1).map((v,i)=>v-measures[i])),Math.max(...measures.slice(1).map((v,i)=>v-measures[i])));
