const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),{parseMidi,writeMidi}=require('midi-file'),MidiFile=require('midifile');
require('ts-node').register({transpileOnly:true,compilerOptions:{module:'commonjs'}});
const {parseNotes}=require('../../src/components/rawl/parseMidi');
const root=__dirname,filename=root+'/idea-15-transkun-visual-legato.mid',before=fs.readFileSync(filename),prior=JSON.parse(fs.readFileSync(root+'/m36-bass-updated.json')),saved=JSON.parse(fs.readFileSync(root+'/saved.json'));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');assert.equal(sha(before),prior.sha256);
const abs=tr=>{let t=0;return tr.map(e=>({tick:t+=e.deltaTime,event:{...e,deltaTime:0}}));},m=parseMidi(before),tracks=m.tracks.map(abs),original=tracks.map(t=>JSON.parse(JSON.stringify(t))),grid=JSON.parse(fs.readFileSync(root+'/display.json')).measures;
const rank=e=>e.type==='noteOff'?0:e.type==='noteOn'?2:1;
function serialize(){m.tracks=tracks.map(tr=>{tr.sort((a,b)=>a.tick-b.tick||rank(a.event)-rank(b.event));let t=0;return tr.map(x=>{const e={...x.event,deltaTime:x.tick-t};t=x.tick;return e;});});return Buffer.from(writeMidi(m));}
function parsed(b){const mf=new MidiFile(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));return parseNotes({events:mf.getEvents(),activeChannels:[0,1,2],timeEvents:[{type:'tempo',bpm:120,playTime:0,tick:0},{type:'end',playTime:110678,tick:212501}],timebase:960});}
function pairs(tr){const active=new Map(),out=[];for(const x of [...tr].sort((a,b)=>a.tick-b.tick||rank(a.event)-rank(b.event))){const e=x.event;if(e.type==='noteOn'&&e.velocity){assert(!active.has(e.noteNumber),'overlapping pitch');active.set(e.noteNumber,x);}else if(e.type==='noteOff'||e.type==='noteOn'&&!e.velocity){const on=active.get(e.noteNumber);assert(on);out.push({on,off:x});active.delete(e.noteNumber);}}assert.equal(active.size,0);return out;}
const oldPairs=pairs(tracks[1]),remove=oldPairs.find(n=>n.on.tick===142285&&n.on.event.noteNumber===54);assert(remove);tracks[1]=tracks[1].filter(x=>x!==remove.on&&x!==remove.off);
const added=[],endings=[];
for(const first of [18,36,54,72,90,108]){const low=first===108,pitches=low?[42,47,51]:[54,59,63],lastTick=Math.round(grid[first+1]*1920);for(let offset=0;offset<2;offset++){const bar=first+offset,boundary=Math.round(grid[bar-1]*1920),wanted=offset?pitches.slice(1):pitches;const melody=tracks[3].find(x=>x.event.type==='noteOn'&&Math.abs(x.tick-boundary)<100);assert(melody);const anchor=melody.tick;for(const pitch of wanted){let hit=tracks[1].find(x=>x.event.type==='noteOn'&&x.event.noteNumber===pitch&&Math.abs(x.tick-boundary)<100);if(!hit){hit={tick:anchor,event:{deltaTime:0,type:'noteOn',channel:0,noteNumber:pitch,velocity:39}};const off={tick:lastTick,event:{deltaTime:0,type:'noteOff',channel:0,noteNumber:pitch,velocity:0}};tracks[1].push(hit,off);added.push({bar,pitch,tick:anchor,velocity:39});}}endings.push({bar,pitches:wanted,bassHeld:!!offset});}}
// Cap every old same-pitch release before a newly introduced attack before parsing.
for(const pitch of [42,47,51,54,59,63]){const ons=tracks[1].filter(x=>x.event.type==='noteOn'&&x.event.noteNumber===pitch).sort((a,b)=>a.tick-b.tick);for(const pair of oldPairs){if(pair===remove||pair.on.event.noteNumber!==pitch)continue;const next=ons.find(x=>x.tick>pair.on.tick);if(next&&pair.off.tick>next.tick)pair.off.tick=next.tick;}}
const p=parsed(serialize()),releaseChanges=[];
p.notes.forEach((voice,ch)=>{for(const n of voice){const pitch=n.note.midiNumber,start=Math.round(n.span[0]*1920),end=Math.round(n.span[1]*1920),next=voice.filter(o=>o.note.midiNumber===pitch&&o.span[0]>n.span[0]+1e-6).sort((a,b)=>a.span[0]-b.span[0])[0],target=Math.min(next?Math.round(next.span[0]*1920):Infinity,Math.max(end,Math.ceil(n.displaySpan[1]*1920-1e-7)));if(target!==end){assert.equal(ch,0);const off=tracks[ch+1].find(x=>x.event.type==='noteOff'&&x.event.noteNumber===pitch&&x.tick===end);assert(off);off.tick=target;releaseChanges.push({pitch,start,oldEnd:end,end:target});}}});
const after=serialize(),got=parsed(after);assert.equal(got.notes.flat().length,968+added.length-1);
for(const voice of got.notes)for(const n of voice){assert(n.span[1]+1e-7>=n.displaySpan[1],n.id);const next=voice.filter(o=>o.note.midiNumber===n.note.midiNumber&&o.span[0]>n.span[0]+1e-6).sort((a,b)=>a.span[0]-b.span[0])[0];if(next){assert(n.span[1]<=next.span[0]+1e-7);assert(n.displaySpan[1]<=next.span[0]+1e-7);}}
for(let i=0;i<4;i++){if(i!==1)assert.deepEqual(abs(parseMidi(after).tracks[i]),original[i]);else{const nonNotes=t=>t.filter(x=>!['noteOn','noteOff'].includes(x.event.type));assert.deepEqual(nonNotes(tracks[i]),nonNotes(original[i]));const ons=t=>t.filter(x=>x.event.type==='noteOn').map(x=>[x.tick,x.event.noteNumber,x.event.velocity]);assert.deepEqual(ons(tracks[i]).filter(x=>!added.some(a=>a.tick===x[0]&&a.pitch===x[1])),ons(original[i]).filter(x=>x[0]!==142285||x[1]!==54));}}
for(const row of endings){const t=grid[row.bar-1]*1920,attacks=got.notes[0].filter(n=>Math.abs(n.span[0]*1920-t)<100).map(n=>n.note.midiNumber).sort((a,b)=>a-b);assert.deepEqual(attacks,row.pitches);}
const revision={id:prior.id,slug:prior.slug,beforeSha256:prior.sha256,sha256:sha(after),noteCount:got.notes.flat().length,voices:got.notes.map(v=>v.length),added,removed:{tick:142285,pitch:54},releaseChanges,endings,decision:'Uniform editorial normalization: first closing bar beat1 bass plus B/D# dyad; second closing bar beat1 dyad only; bass held across both. Final ending octave lower. Existing attacks/velocities retained; inserted attacks use melody anchor and velocity39. Recording confirms bass entry consistently; dyad attacks less conclusive, confirmed73 retained. Controllers and other voices unchanged.',updatedAt:new Date().toISOString()};
fs.writeFileSync(root+'/uniform-endings-candidate.mid',after);fs.writeFileSync(root+'/uniform-endings-candidate.json',JSON.stringify(revision,null,2));
if(!process.argv.includes('--publish')){console.log(JSON.stringify(revision,null,2));process.exit(0);}
const admin=require('firebase-admin');admin.initializeApp({credential:admin.credential.cert(require('../../src/config/firebaseConfigPrivate.json'))});
(async()=>{const ref=admin.firestore().collection('midis').doc(prior.id);await admin.firestore().runTransaction(async tx=>{const d=(await tx.get(ref)).data();assert.equal(d.slug,prior.slug);assert.equal(sha(Buffer.from(d.blob)),prior.sha256);tx.update(ref,{blob:after});});assert.equal(sha(Buffer.from((await ref.get()).data().blob)),sha(after));assert.equal(sha(Buffer.from((await admin.firestore().collection('midis').doc('eX97GlcN8uB2C0p6Zg9r').get()).data().blob)),saved.originalUnchangedSha256);fs.writeFileSync(root+'/before-uniform-endings.mid',before);fs.writeFileSync(filename,after);const path='src/midis/'+prior.id+'.json',local=JSON.parse(fs.readFileSync(path));assert.equal(sha(Buffer.from(local.blobBase64,'base64')),prior.sha256);local.blobBase64=after.toString('base64');fs.writeFileSync(path,JSON.stringify(local,null,2));fs.writeFileSync(root+'/uniform-endings-updated.json',JSON.stringify(revision,null,2));const manifest=JSON.parse(fs.readFileSync(root+'/manifest.json'));manifest.outputSha256=sha(after);manifest.noteCount=revision.noteCount;manifest.voices.forEach((v,i)=>v.count=revision.voices[i]);manifest.uniformEndingsRevision=revision;fs.writeFileSync(root+'/manifest.json',JSON.stringify(manifest,null,2));fs.appendFileSync(root+'/README.txt','\nUniform ending revision: '+revision.decision+' Added'+added.length+' attacks; removed m73 beat3 F#3. Current'+revision.noteCount+' notes. See uniform-endings-updated.json and ending-attack-evidence.json.\n');console.log('Published and readback verified: '+revision.noteCount+' notes, six uniform LH endings, all controllers and other voices preserved.');process.exit(0);})().catch(e=>{console.error(e.message);process.exit(1)});
