const MIDI_PREVIEWS = {
  "C3-E3-G3-C4 G2-B2-D3-D4 C3-E3-G3-E4 F3-A3-C4-F4 E3-G#3-B3-G#4 A3-C4-E4-A4 G3-B3-D4-B4 C3-E3-G3-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 48 }, id: 0, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 52 }, id: 1, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 2, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 3, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 43 }, id: 4, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 47 }, id: 5, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 6, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 7, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 48 }, id: 8, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 9, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 10, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 11, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 53 }, id: 12, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 57 }, id: 13, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 60 }, id: 14, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 15, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 52 }, id: 16, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 56 }, id: 17, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 59 }, id: 18, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 68 }, id: 19, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 57 }, id: 20, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 60 }, id: 21, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 64 }, id: 22, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 69 }, id: 23, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 55 }, id: 24, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 59 }, id: 25, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 62 }, id: 26, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 71 }, id: 27, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 28, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 52 }, id: 29, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 55 }, id: 30, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 31, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C3-E3-G3-C4 G2-B2-D3-D4 C3-E3-G3-E4 F3-A3-C4-F4 C3-E3-G3-G4 D3-F#3-A3-A4 G3-B3-D4-B4 C3-E3-G3-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 48 }, id: 32, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 52 }, id: 33, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 34, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 35, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 43 }, id: 36, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 47 }, id: 37, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 38, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 39, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 48 }, id: 40, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 41, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 42, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 43, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 53 }, id: 44, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 57 }, id: 45, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 60 }, id: 46, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 47, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 48 }, id: 48, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 52 }, id: 49, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 55 }, id: 50, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 51, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 50 }, id: 52, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 54 }, id: 53, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 57 }, id: 54, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 69 }, id: 55, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 55 }, id: 56, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 59 }, id: 57, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 62 }, id: 58, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 71 }, id: 59, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 60, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 52 }, id: 61, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 55 }, id: 62, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 63, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C3-E3-G3-C4 G2-B2-D3-D4 C3-E3-G3-E4 F2-A2-C3-F4 C3-E3-G3-G4 F2-A2-C3-A4 G2-B2-D3-B4 C3-E3-G3-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 48 }, id: 64, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 52 }, id: 65, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 66, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 67, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 43 }, id: 68, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 47 }, id: 69, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 70, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 71, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 48 }, id: 72, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 73, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 74, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 75, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 41 }, id: 76, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 45 }, id: 77, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 48 }, id: 78, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 79, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 48 }, id: 80, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 52 }, id: 81, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 55 }, id: 82, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 83, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 41 }, id: 84, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 45 }, id: 85, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 48 }, id: 86, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 69 }, id: 87, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 43 }, id: 88, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 47 }, id: 89, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 50 }, id: 90, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 71 }, id: 91, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 92, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 52 }, id: 93, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 55 }, id: 94, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 95, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C3-E3-G3-C4 G2-B2-D3-D4 C3-E3-G3-E4 G2-B2-D3-F4 C3-E3-G3-G4 C3-E3-G3-A4 G2-B2-D3-B4 C3-E3-G3-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 48 }, id: 96, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 52 }, id: 97, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 98, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 99, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 43 }, id: 100, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 47 }, id: 101, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 102, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 103, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 48 }, id: 104, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 105, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 106, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 107, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 43 }, id: 108, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 47 }, id: 109, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 50 }, id: 110, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 111, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 48 }, id: 112, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 52 }, id: 113, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 55 }, id: 114, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 115, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 48 }, id: 116, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 52 }, id: 117, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 55 }, id: 118, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 69 }, id: 119, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 43 }, id: 120, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 47 }, id: 121, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 50 }, id: 122, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 71 }, id: 123, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 124, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 52 }, id: 125, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 55 }, id: 126, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 127, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C4-E4-G4-B4-D5 G3-B3-D4-F4-A4 A3-C4-E4-G4-B4 E3-G3-B3-D4 F3-A3-C4-E4-G4 C3-E3-G3-B3-D4 F3-A3-C4-E4-G4 G3-B3-D4-F4-Ab4":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 60 }, id: 128, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 64 }, id: 129, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 67 }, id: 130, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 71 }, id: 131, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 74 }, id: 132, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 133, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 59 }, id: 134, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 135, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 65 }, id: 136, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 69 }, id: 137, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 57 }, id: 138, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 60 }, id: 139, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 140, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 67 }, id: 141, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 71 }, id: 142, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 143, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 55 }, id: 144, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 59 }, id: 145, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 62 }, id: 146, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 53 }, id: 147, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 57 }, id: 148, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 60 }, id: 149, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 64 }, id: 150, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 151, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 48 }, id: 152, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 52 }, id: 153, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 55 }, id: 154, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 59 }, id: 155, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 62 }, id: 156, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 53 }, id: 157, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 57 }, id: 158, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 60 }, id: 159, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 64 }, id: 160, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 67 }, id: 161, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 55 }, id: 162, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 59 }, id: 163, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 62 }, id: 164, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 65 }, id: 165, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 68 }, id: 166, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C4-E4-G4-B4 G3-B3-D4-F4 A3-C4-E4-G4 E3-G3-B3-D4 F3-A3-C4-E4 C3-E3-G3-B3 F3-A3-C4-E4 G3-B3-D4-F4":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 60 }, id: 167, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 64 }, id: 168, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 67 }, id: 169, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 71 }, id: 170, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 171, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 59 }, id: 172, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 173, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 65 }, id: 174, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 57 }, id: 175, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 60 }, id: 176, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 177, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 67 }, id: 178, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 179, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 55 }, id: 180, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 59 }, id: 181, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 62 }, id: 182, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 53 }, id: 183, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 57 }, id: 184, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 60 }, id: 185, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 64 }, id: 186, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 48 }, id: 187, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 52 }, id: 188, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 55 }, id: 189, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 59 }, id: 190, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 53 }, id: 191, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 57 }, id: 192, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 60 }, id: 193, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 64 }, id: 194, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 55 }, id: 195, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 59 }, id: 196, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 62 }, id: 197, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 65 }, id: 198, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C4-E4-G4 G3-B3-D4 A3-C4-E4 E3-G3-B3 F3-A3-C4 C3-E3-G3 F3-A3-C4 G3-B3-D4": {
    measuresAndBeats: {
      measures: [0, 2, 4, 6, 8],
      beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
    },
    notes: [
      [
        { note: { midiNumber: 60 }, id: 199, isDrum: false, span: [0, 1] },
        { note: { midiNumber: 64 }, id: 200, isDrum: false, span: [0, 1] },
        { note: { midiNumber: 67 }, id: 201, isDrum: false, span: [0, 1] },
        { note: { midiNumber: 55 }, id: 202, isDrum: false, span: [1, 2] },
        { note: { midiNumber: 59 }, id: 203, isDrum: false, span: [1, 2] },
        { note: { midiNumber: 62 }, id: 204, isDrum: false, span: [1, 2] },
        { note: { midiNumber: 57 }, id: 205, isDrum: false, span: [2, 3] },
        { note: { midiNumber: 60 }, id: 206, isDrum: false, span: [2, 3] },
        { note: { midiNumber: 64 }, id: 207, isDrum: false, span: [2, 3] },
        { note: { midiNumber: 52 }, id: 208, isDrum: false, span: [3, 4] },
        { note: { midiNumber: 55 }, id: 209, isDrum: false, span: [3, 4] },
        { note: { midiNumber: 59 }, id: 210, isDrum: false, span: [3, 4] },
        { note: { midiNumber: 53 }, id: 211, isDrum: false, span: [4, 5] },
        { note: { midiNumber: 57 }, id: 212, isDrum: false, span: [4, 5] },
        { note: { midiNumber: 60 }, id: 213, isDrum: false, span: [4, 5] },
        { note: { midiNumber: 48 }, id: 214, isDrum: false, span: [5, 6] },
        { note: { midiNumber: 52 }, id: 215, isDrum: false, span: [5, 6] },
        { note: { midiNumber: 55 }, id: 216, isDrum: false, span: [5, 6] },
        { note: { midiNumber: 53 }, id: 217, isDrum: false, span: [6, 7] },
        { note: { midiNumber: 57 }, id: 218, isDrum: false, span: [6, 7] },
        { note: { midiNumber: 60 }, id: 219, isDrum: false, span: [6, 7] },
        { note: { midiNumber: 55 }, id: 220, isDrum: false, span: [7, 8] },
        { note: { midiNumber: 59 }, id: 221, isDrum: false, span: [7, 8] },
        { note: { midiNumber: 62 }, id: 222, isDrum: false, span: [7, 8] },
      ],
    ],
  },
  "C4-G4 G3-D4 A3-E4 E3-B3 F3-C4 C3-G3 F3-C4 G3-D4": {
    measuresAndBeats: {
      measures: [0, 2, 4, 6, 8],
      beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
    },
    notes: [
      [
        { note: { midiNumber: 60 }, id: 223, isDrum: false, span: [0, 1] },
        { note: { midiNumber: 67 }, id: 224, isDrum: false, span: [0, 1] },
        { note: { midiNumber: 55 }, id: 225, isDrum: false, span: [1, 2] },
        { note: { midiNumber: 62 }, id: 226, isDrum: false, span: [1, 2] },
        { note: { midiNumber: 57 }, id: 227, isDrum: false, span: [2, 3] },
        { note: { midiNumber: 64 }, id: 228, isDrum: false, span: [2, 3] },
        { note: { midiNumber: 52 }, id: 229, isDrum: false, span: [3, 4] },
        { note: { midiNumber: 59 }, id: 230, isDrum: false, span: [3, 4] },
        { note: { midiNumber: 53 }, id: 231, isDrum: false, span: [4, 5] },
        { note: { midiNumber: 60 }, id: 232, isDrum: false, span: [4, 5] },
        { note: { midiNumber: 48 }, id: 233, isDrum: false, span: [5, 6] },
        { note: { midiNumber: 55 }, id: 234, isDrum: false, span: [5, 6] },
        { note: { midiNumber: 53 }, id: 235, isDrum: false, span: [6, 7] },
        { note: { midiNumber: 60 }, id: 236, isDrum: false, span: [6, 7] },
        { note: { midiNumber: 55 }, id: 237, isDrum: false, span: [7, 8] },
        { note: { midiNumber: 62 }, id: 238, isDrum: false, span: [7, 8] },
      ],
    ],
  },
  "C4 G3 A3 E3 F3 C3 F3 G3": {
    measuresAndBeats: {
      measures: [0, 2, 4, 6, 8],
      beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
    },
    notes: [
      [
        { note: { midiNumber: 60 }, id: 239, isDrum: false, span: [0, 1] },
        { note: { midiNumber: 55 }, id: 240, isDrum: false, span: [1, 2] },
        { note: { midiNumber: 57 }, id: 241, isDrum: false, span: [2, 3] },
        { note: { midiNumber: 52 }, id: 242, isDrum: false, span: [3, 4] },
        { note: { midiNumber: 53 }, id: 243, isDrum: false, span: [4, 5] },
        { note: { midiNumber: 48 }, id: 244, isDrum: false, span: [5, 6] },
        { note: { midiNumber: 53 }, id: 245, isDrum: false, span: [6, 7] },
        { note: { midiNumber: 55 }, id: 246, isDrum: false, span: [7, 8] },
      ],
    ],
  },
  "C2-C3-Eb3-G3-C4 Bb1-Bb2-D3-F3-D4 Eb2-Eb3-G3-Bb3-Eb4 F2-F3-Ab3-C4-F4 G2-G3-Bb3-D4-G4 Ab2-Ab3-C4-Eb4-Ab4 Bb2-Bb3-D4-F4-Bb4 C3-C4-Eb4-G4-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 36 }, id: 247, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 48 }, id: 248, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 51 }, id: 249, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 250, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 251, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 34 }, id: 252, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 46 }, id: 253, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 254, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 53 }, id: 255, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 256, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 39 }, id: 257, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 51 }, id: 258, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 259, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 58 }, id: 260, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 63 }, id: 261, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 41 }, id: 262, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 53 }, id: 263, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 56 }, id: 264, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 60 }, id: 265, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 266, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 43 }, id: 267, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 55 }, id: 268, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 58 }, id: 269, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 62 }, id: 270, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 271, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 44 }, id: 272, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 56 }, id: 273, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 60 }, id: 274, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 63 }, id: 275, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 68 }, id: 276, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 46 }, id: 277, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 58 }, id: 278, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 62 }, id: 279, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 65 }, id: 280, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 70 }, id: 281, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 282, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 60 }, id: 283, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 63 }, id: 284, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 67 }, id: 285, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 286, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C2-C3-Eb3-G3-C4 Bb1-Bb2-D3-F3-D4 Eb2-Eb3-G3-Bb3-Eb4 F2-F3-Ab3-C4-F4 G2-G3-Bb3-D4-G4 Ab2-Ab3-C4-Eb4-Ab4 G2-G3-B3-D4-B4 C3-C4-Eb4-G4-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 36 }, id: 287, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 48 }, id: 288, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 51 }, id: 289, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 290, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 291, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 34 }, id: 292, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 46 }, id: 293, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 294, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 53 }, id: 295, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 296, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 39 }, id: 297, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 51 }, id: 298, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 299, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 58 }, id: 300, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 63 }, id: 301, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 41 }, id: 302, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 53 }, id: 303, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 56 }, id: 304, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 60 }, id: 305, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 306, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 43 }, id: 307, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 55 }, id: 308, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 58 }, id: 309, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 62 }, id: 310, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 311, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 44 }, id: 312, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 56 }, id: 313, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 60 }, id: 314, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 63 }, id: 315, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 68 }, id: 316, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 43 }, id: 317, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 55 }, id: 318, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 59 }, id: 319, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 62 }, id: 320, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 71 }, id: 321, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 322, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 60 }, id: 323, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 63 }, id: 324, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 67 }, id: 325, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 326, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C2-C3-E3-G3-C4 D2-D3-F3-A3-D4 E2-E3-G3-B3-E4 F2-F3-A3-C4-F4 G2-G3-B3-D4-G4 A2-A3-C4-E4-A4 G2-G3-B3-D4-B4 C3-C4-E4-G4-C5":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 36 }, id: 327, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 48 }, id: 328, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 52 }, id: 329, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 330, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 331, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 38 }, id: 332, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 333, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 53 }, id: 334, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 57 }, id: 335, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 336, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 40 }, id: 337, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 338, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 339, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 59 }, id: 340, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 341, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 41 }, id: 342, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 53 }, id: 343, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 57 }, id: 344, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 60 }, id: 345, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 65 }, id: 346, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 43 }, id: 347, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 55 }, id: 348, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 59 }, id: 349, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 62 }, id: 350, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 351, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 45 }, id: 352, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 57 }, id: 353, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 60 }, id: 354, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 64 }, id: 355, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 69 }, id: 356, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 43 }, id: 357, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 55 }, id: 358, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 59 }, id: 359, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 62 }, id: 360, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 71 }, id: 361, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 362, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 60 }, id: 363, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 64 }, id: 364, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 67 }, id: 365, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 72 }, id: 366, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C2-C3-E3-G3-C4 D2-A2-D3-F3-D4 G1-B2-D3-G3-B3 C2-C3-E3-G3-C4 C#2-C#3-E#3-G#3-C#4 D#2-A#2-D#3-F#3-D#4 G#1-B#2-D#3-G#3-B#3 C#2-C#3-E#3-G#3-C#4":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      analysis: {
        modulations: { "3": 1 },
        tonic: 0,
        comment: "",
        tags: [],
        form: [],
        phrasePatch: [],
      },
      notes: [
        [
          { note: { midiNumber: 36 }, id: 0, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 48 }, id: 1, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 52 }, id: 2, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 3, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 60 }, id: 4, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 38 }, id: 5, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 45 }, id: 6, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 50 }, id: 7, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 53 }, id: 8, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 9, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 31 }, id: 10, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 47 }, id: 11, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 50 }, id: 12, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 55 }, id: 13, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 59 }, id: 14, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 36 }, id: 15, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 48 }, id: 16, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 52 }, id: 17, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 55 }, id: 18, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 60 }, id: 19, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 37 }, id: 20, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 49 }, id: 21, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 53 }, id: 22, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 56 }, id: 23, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 61 }, id: 24, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 39 }, id: 25, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 46 }, id: 26, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 51 }, id: 27, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 54 }, id: 28, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 63 }, id: 29, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 32 }, id: 30, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 48 }, id: 31, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 51 }, id: 32, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 56 }, id: 33, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 60 }, id: 34, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 37 }, id: 35, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 49 }, id: 36, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 53 }, id: 37, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 56 }, id: 38, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 61 }, id: 39, isDrum: false, span: [7, 8] },
        ],
      ],
    },
  "C4-E4-G4-B4-D5 G3-D4-E4-G4-B4 A3-C4-E4-G4-B4 E3-G3-B3-D4 F3-A3-C4-E4-G4 C3-E3-G3-B3-D4 F3-A3-C4-E4-G4 G3-B3-D4-F4-A4":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6, 8],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7, 7.5],
      },
      notes: [
        [
          { note: { midiNumber: 60 }, id: 80, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 64 }, id: 81, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 67 }, id: 82, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 71 }, id: 83, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 74 }, id: 84, isDrum: false, span: [0, 1] },
          { note: { midiNumber: 55 }, id: 85, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 62 }, id: 86, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 64 }, id: 87, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 67 }, id: 88, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 71 }, id: 89, isDrum: false, span: [1, 2] },
          { note: { midiNumber: 57 }, id: 90, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 60 }, id: 91, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 64 }, id: 92, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 67 }, id: 93, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 71 }, id: 94, isDrum: false, span: [2, 3] },
          { note: { midiNumber: 52 }, id: 95, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 55 }, id: 96, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 59 }, id: 97, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 62 }, id: 98, isDrum: false, span: [3, 4] },
          { note: { midiNumber: 53 }, id: 99, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 57 }, id: 100, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 60 }, id: 101, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 64 }, id: 102, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 67 }, id: 103, isDrum: false, span: [4, 5] },
          { note: { midiNumber: 48 }, id: 104, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 52 }, id: 105, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 55 }, id: 106, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 59 }, id: 107, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 62 }, id: 108, isDrum: false, span: [5, 6] },
          { note: { midiNumber: 53 }, id: 109, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 57 }, id: 110, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 60 }, id: 111, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 64 }, id: 112, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 67 }, id: 113, isDrum: false, span: [6, 7] },
          { note: { midiNumber: 55 }, id: 114, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 59 }, id: 115, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 62 }, id: 116, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 65 }, id: 117, isDrum: false, span: [7, 8] },
          { note: { midiNumber: 69 }, id: 118, isDrum: false, span: [7, 8] },
        ],
      ],
    },
};

export default MIDI_PREVIEWS;
