const MIDI_PREVIEWS = {
  "C3-C4-E4-G4 F2-F4-A4-C5 G2-G4-B4-D5 C3-C4-E4-G4": {
    measuresAndBeats: { measures: [0, 2], beats: [0.5, 1, 1.5] },
    notes: [
      [
        {
          note: { midiNumber: 48 },
          id: 0,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x19",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x29",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 1,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x1d",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x2e",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 64 },
          id: 2,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x21",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 64,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x32",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 64,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 67 },
          id: 3,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x25",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x36",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 41 },
          id: 4,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x3a",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x4a",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 65 },
          id: 5,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x3e",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 65,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x4f",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 65,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 69 },
          id: 6,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x42",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 69,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x53",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 69,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 72 },
          id: 7,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x46",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 72,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x57",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 72,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 43 },
          id: 8,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x5b",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x6b",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 67 },
          id: 9,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x5f",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x70",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 71 },
          id: 10,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x63",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 71,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x74",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 71,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 74 },
          id: 11,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x67",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 74,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x78",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 74,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 48 },
          id: 12,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x7c",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x8c",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 13,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x80",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x91",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 64 },
          id: 14,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x84",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 64,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x95",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 64,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 67 },
          id: 15,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x88",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x99",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 2000,
            },
          },
        },
      ],
    ],
  },
  "C3-C4-Eb4-G4 F2-F4-Ab4-C5 G2-G4-B4-D5 C3-C4-Eb4-G4": {
    measuresAndBeats: { measures: [0, 2], beats: [0.5, 1, 1.5] },
    notes: [
      [
        {
          note: { midiNumber: 48 },
          id: 16,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x19",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x29",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 17,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x1d",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x2e",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 63 },
          id: 18,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x21",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 63,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x32",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 63,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 67 },
          id: 19,
          isDrum: false,
          span: [0, 0.5],
          chipState: {
            on: {
              index: "0x25",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x36",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 500,
            },
          },
        },
        {
          note: { midiNumber: 41 },
          id: 20,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x3a",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x4a",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 65 },
          id: 21,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x3e",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 65,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x4f",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 65,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 68 },
          id: 22,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x42",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 68,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x53",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 68,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 72 },
          id: 23,
          isDrum: false,
          span: [0.5, 1],
          chipState: {
            on: {
              index: "0x46",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 72,
              param2: 64,
              playTime: 500,
            },
            off: {
              index: "0x57",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 72,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 43 },
          id: 24,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x5b",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x6b",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 67 },
          id: 25,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x5f",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x70",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 71 },
          id: 26,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x63",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 71,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x74",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 71,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 74 },
          id: 27,
          isDrum: false,
          span: [1, 1.5],
          chipState: {
            on: {
              index: "0x67",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 74,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x78",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 74,
              param2: 64,
              playTime: 1500,
            },
          },
        },
        {
          note: { midiNumber: 48 },
          id: 28,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x7c",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x8c",
              delta: 128,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 29,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x80",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x91",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 63 },
          id: 30,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x84",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 63,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x95",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 63,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 67 },
          id: 31,
          isDrum: false,
          span: [1.5, 2],
          chipState: {
            on: {
              index: "0x88",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 1500,
            },
            off: {
              index: "0x99",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 67,
              param2: 64,
              playTime: 2000,
            },
          },
        },
      ],
    ],
  },
  "C3 F2 G2 C3": {
    measuresAndBeats: {
      measures: [0, 2, 4],
      beats: [0.5, 1, 1.5, 2.5, 3, 3.5],
    },
    notes: [
      [
        {
          note: { midiNumber: 48 },
          id: 24,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x19",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x1d",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 41 },
          id: 25,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x22",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x26",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 43 },
          id: 26,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x2b",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x2f",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 48 },
          id: 27,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x34",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x38",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 4000,
            },
          },
        },
      ],
    ],
  },
  "C3-G3 F2-C3 G2-D3 C3-G3": {
    measuresAndBeats: {
      measures: [0, 2, 4],
      beats: [0.5, 1, 1.5, 2.5, 3, 3.5],
    },
    notes: [
      [
        {
          note: { midiNumber: 48 },
          id: 28,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x19",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x21",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 55 },
          id: 29,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x1d",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x26",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 41 },
          id: 30,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x2a",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x32",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 48 },
          id: 31,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x2e",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x37",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 43 },
          id: 32,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x3b",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x43",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 50 },
          id: 33,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x3f",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 50,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x48",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 50,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 48 },
          id: 34,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x4c",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x54",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 48,
              param2: 64,
              playTime: 4000,
            },
          },
        },
        {
          note: { midiNumber: 55 },
          id: 35,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x50",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x59",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 4000,
            },
          },
        },
      ],
    ],
  },
  "C2-Eb3-G3-C4 Ab1-Eb3-Ab3-C4 Bb1-F3-Bb3-D3 Eb2-Eb3-G3-Bb3 F2-F3-Ab3-C4 G2-G3-B3-D4 C2-G3-C4-Eb4":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7],
      },
      notes: [
        [
          {
            note: { midiNumber: 36 },
            id: 28,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x19",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x29",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 51 },
            id: 29,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x1d",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 51,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x2e",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 51,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 30,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x21",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x32",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 31,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x25",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x36",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 32 },
            id: 32,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x3a",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 32,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x4a",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 32,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 51 },
            id: 33,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x3e",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 51,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x4f",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 51,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 56 },
            id: 34,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x42",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 56,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x53",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 56,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 35,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x46",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x57",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 34 },
            id: 36,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x5b",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 34,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x6b",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 34,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 53 },
            id: 37,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x5f",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x70",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 58 },
            id: 38,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x63",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 58,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x74",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 58,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 50 },
            id: 39,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x67",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 50,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x78",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 50,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 39 },
            id: 40,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x7c",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 39,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x8c",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 39,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 51 },
            id: 41,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x80",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 51,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x91",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 51,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 42,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x84",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x95",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 58 },
            id: 43,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x88",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 58,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x99",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 58,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 41 },
            id: 44,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0x9d",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 41,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xad",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 41,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 53 },
            id: 45,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0xa1",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xb2",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 56 },
            id: 46,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0xa5",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 56,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xb6",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 56,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 47,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0xa9",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xba",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 43 },
            id: 48,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xbe",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 43,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xce",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 43,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 49,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xc2",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xd3",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 59 },
            id: 50,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xc6",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 59,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xd7",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 59,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 62 },
            id: 51,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xca",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 62,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xdb",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 62,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 36 },
            id: 52,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xdf",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xef",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 7000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 53,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xe3",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xf4",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 7000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 54,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xe7",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xf8",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 7000,
              },
            },
          },
          {
            note: { midiNumber: 63 },
            id: 55,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xeb",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 63,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xfc",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 63,
                param2: 64,
                playTime: 7000,
              },
            },
          },
        ],
      ],
    },
  "C2-E3-G3-C4 A1-E3-A3-C4 F2-F3-A3-C4 D2-F3-A3-D4 G2-G3-B3-D4 C2-G3-C4-E4": {
    measuresAndBeats: {
      measures: [0, 2, 4, 6],
      beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5],
    },
    notes: [
      [
        {
          note: { midiNumber: 36 },
          id: 0,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x19",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 36,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x29",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 36,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 52 },
          id: 1,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x1d",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 52,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x2e",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 52,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 55 },
          id: 2,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x21",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x32",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 3,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x25",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x36",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 1000,
            },
          },
        },
        {
          note: { midiNumber: 33 },
          id: 4,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x3a",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 33,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x4a",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 33,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 52 },
          id: 5,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x3e",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 52,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x4f",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 52,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 57 },
          id: 6,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x42",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 57,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x53",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 57,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 7,
          isDrum: false,
          span: [1, 2],
          chipState: {
            on: {
              index: "0x46",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 1000,
            },
            off: {
              index: "0x57",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 2000,
            },
          },
        },
        {
          note: { midiNumber: 41 },
          id: 8,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x5b",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x6b",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 41,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 53 },
          id: 9,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x5f",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 53,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x70",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 53,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 57 },
          id: 10,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x63",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 57,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x74",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 57,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 11,
          isDrum: false,
          span: [2, 3],
          chipState: {
            on: {
              index: "0x67",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 2000,
            },
            off: {
              index: "0x78",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 3000,
            },
          },
        },
        {
          note: { midiNumber: 38 },
          id: 12,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x7c",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 38,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x8c",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 38,
              param2: 64,
              playTime: 4000,
            },
          },
        },
        {
          note: { midiNumber: 53 },
          id: 13,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x80",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 53,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x91",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 53,
              param2: 64,
              playTime: 4000,
            },
          },
        },
        {
          note: { midiNumber: 57 },
          id: 14,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x84",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 57,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x95",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 57,
              param2: 64,
              playTime: 4000,
            },
          },
        },
        {
          note: { midiNumber: 62 },
          id: 15,
          isDrum: false,
          span: [3, 4],
          chipState: {
            on: {
              index: "0x88",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 62,
              param2: 64,
              playTime: 3000,
            },
            off: {
              index: "0x99",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 62,
              param2: 64,
              playTime: 4000,
            },
          },
        },
        {
          note: { midiNumber: 43 },
          id: 16,
          isDrum: false,
          span: [4, 5],
          chipState: {
            on: {
              index: "0x9d",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 4000,
            },
            off: {
              index: "0xad",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 43,
              param2: 64,
              playTime: 5000,
            },
          },
        },
        {
          note: { midiNumber: 55 },
          id: 17,
          isDrum: false,
          span: [4, 5],
          chipState: {
            on: {
              index: "0xa1",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 4000,
            },
            off: {
              index: "0xb2",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 5000,
            },
          },
        },
        {
          note: { midiNumber: 59 },
          id: 18,
          isDrum: false,
          span: [4, 5],
          chipState: {
            on: {
              index: "0xa5",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 59,
              param2: 64,
              playTime: 4000,
            },
            off: {
              index: "0xb6",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 59,
              param2: 64,
              playTime: 5000,
            },
          },
        },
        {
          note: { midiNumber: 62 },
          id: 19,
          isDrum: false,
          span: [4, 5],
          chipState: {
            on: {
              index: "0xa9",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 62,
              param2: 64,
              playTime: 4000,
            },
            off: {
              index: "0xba",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 62,
              param2: 64,
              playTime: 5000,
            },
          },
        },
        {
          note: { midiNumber: 36 },
          id: 20,
          isDrum: false,
          span: [5, 6],
          chipState: {
            on: {
              index: "0xbe",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 36,
              param2: 64,
              playTime: 5000,
            },
            off: {
              index: "0xce",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 36,
              param2: 64,
              playTime: 6000,
            },
          },
        },
        {
          note: { midiNumber: 55 },
          id: 21,
          isDrum: false,
          span: [5, 6],
          chipState: {
            on: {
              index: "0xc2",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 5000,
            },
            off: {
              index: "0xd3",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 55,
              param2: 64,
              playTime: 6000,
            },
          },
        },
        {
          note: { midiNumber: 60 },
          id: 22,
          isDrum: false,
          span: [5, 6],
          chipState: {
            on: {
              index: "0xc6",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 5000,
            },
            off: {
              index: "0xd7",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 60,
              param2: 64,
              playTime: 6000,
            },
          },
        },
        {
          note: { midiNumber: 64 },
          id: 23,
          isDrum: false,
          span: [5, 6],
          chipState: {
            on: {
              index: "0xca",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 64,
              param2: 64,
              playTime: 5000,
            },
            off: {
              index: "0xdb",
              delta: 0,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 64,
              param2: 64,
              playTime: 6000,
            },
          },
        },
      ],
    ],
  },
  "": {
    measuresAndBeats: { measures: [0], beats: [0.5, 1] },
    notes: [
      [
        {
          note: { midiNumber: 0 },
          id: 37,
          isDrum: false,
          span: [0, 1],
          chipState: {
            on: {
              index: "0x19",
              delta: 0,
              type: 8,
              subtype: 9,
              channel: 0,
              param1: 0,
              param2: 64,
              playTime: 0,
            },
            off: {
              index: "0x1d",
              delta: 256,
              type: 8,
              subtype: 8,
              channel: 0,
              param1: 0,
              param2: 64,
              playTime: 1000,
            },
          },
        },
      ],
    ],
  },
  "C2-E3-G3-C4 A1-E3-A3-C4 E2-E3-G3-B3 F2-F3-A3-C4 D2-F3-A3-D4 G2-G3-B3-D4 C2-G3-C4-E4":
    {
      measuresAndBeats: {
        measures: [0, 2, 4, 6],
        beats: [0.5, 1, 1.5, 2.5, 3, 3.5, 4.5, 5, 5.5, 6.5, 7],
      },
      notes: [
        [
          {
            note: { midiNumber: 36 },
            id: 0,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x19",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x29",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 52 },
            id: 1,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x1d",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 52,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x2e",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 52,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 2,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x21",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x32",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 3,
            isDrum: false,
            span: [0, 1],
            chipState: {
              on: {
                index: "0x25",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 0,
              },
              off: {
                index: "0x36",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 1000,
              },
            },
          },
          {
            note: { midiNumber: 33 },
            id: 4,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x3a",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 33,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x4a",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 33,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 52 },
            id: 5,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x3e",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 52,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x4f",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 52,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 57 },
            id: 6,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x42",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 57,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x53",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 57,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 7,
            isDrum: false,
            span: [1, 2],
            chipState: {
              on: {
                index: "0x46",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 1000,
              },
              off: {
                index: "0x57",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 2000,
              },
            },
          },
          {
            note: { midiNumber: 40 },
            id: 8,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x5b",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 40,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x6b",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 40,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 52 },
            id: 9,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x5f",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 52,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x70",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 52,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 10,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x63",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x74",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 59 },
            id: 11,
            isDrum: false,
            span: [2, 3],
            chipState: {
              on: {
                index: "0x67",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 59,
                param2: 64,
                playTime: 2000,
              },
              off: {
                index: "0x78",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 59,
                param2: 64,
                playTime: 3000,
              },
            },
          },
          {
            note: { midiNumber: 41 },
            id: 12,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x7c",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 41,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x8c",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 41,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 53 },
            id: 13,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x80",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x91",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 57 },
            id: 14,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x84",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 57,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x95",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 57,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 15,
            isDrum: false,
            span: [3, 4],
            chipState: {
              on: {
                index: "0x88",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 3000,
              },
              off: {
                index: "0x99",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 4000,
              },
            },
          },
          {
            note: { midiNumber: 38 },
            id: 16,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0x9d",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 38,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xad",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 38,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 53 },
            id: 17,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0xa1",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xb2",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 53,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 57 },
            id: 18,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0xa5",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 57,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xb6",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 57,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 62 },
            id: 19,
            isDrum: false,
            span: [4, 5],
            chipState: {
              on: {
                index: "0xa9",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 62,
                param2: 64,
                playTime: 4000,
              },
              off: {
                index: "0xba",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 62,
                param2: 64,
                playTime: 5000,
              },
            },
          },
          {
            note: { midiNumber: 43 },
            id: 20,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xbe",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 43,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xce",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 43,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 21,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xc2",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xd3",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 59 },
            id: 22,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xc6",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 59,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xd7",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 59,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 62 },
            id: 23,
            isDrum: false,
            span: [5, 6],
            chipState: {
              on: {
                index: "0xca",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 62,
                param2: 64,
                playTime: 5000,
              },
              off: {
                index: "0xdb",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 62,
                param2: 64,
                playTime: 6000,
              },
            },
          },
          {
            note: { midiNumber: 36 },
            id: 24,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xdf",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xef",
                delta: 256,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 36,
                param2: 64,
                playTime: 7000,
              },
            },
          },
          {
            note: { midiNumber: 55 },
            id: 25,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xe3",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xf4",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 55,
                param2: 64,
                playTime: 7000,
              },
            },
          },
          {
            note: { midiNumber: 60 },
            id: 26,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xe7",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xf8",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 60,
                param2: 64,
                playTime: 7000,
              },
            },
          },
          {
            note: { midiNumber: 64 },
            id: 27,
            isDrum: false,
            span: [6, 7],
            chipState: {
              on: {
                index: "0xeb",
                delta: 0,
                type: 8,
                subtype: 9,
                channel: 0,
                param1: 64,
                param2: 64,
                playTime: 6000,
              },
              off: {
                index: "0xfc",
                delta: 0,
                type: 8,
                subtype: 8,
                channel: 0,
                param1: 64,
                param2: 64,
                playTime: 7000,
              },
            },
          },
        ],
      ],
    },
};

export default MIDI_PREVIEWS;
