type StaticMidiFile = {
  idx: number;
  path: string;
  link?: string;
  type: "file";
  size: 1337;
};

const STATIC_MIDI_FILES: StaticMidiFile[] = [
  {
    idx: 0,
    path: "/static/Yes/Close_to_the_edge.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 1,
    path: "/static/Yes/To_be_over.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 2,
    path: "/static/bushgrafts/funny val solo.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 3,
    path: "/static/Lena/Merry_Go_Round_of_Life_Howls_Moving_Castle_Piano_Tutorial_.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 4,
    path: "/static/Lena/One_Summers_Day_Spirited_Away.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 5,
    path: "/static/Daniil/Sviridov_Time_Foward.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 6,
    path: "/static/Daniil/pornofilmy-prosti_proshyay_privet.1.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 7,
    path: "/static/Daniil/pornofilmy-prosti_proshyay_privet.2.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 8,
    path: "/static/Daniil/pornofilmy-prosti_proshyay_privet.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 9,
    path: "/static/Daniil/pornofilmy-ya_tak_soskuchilsya.1.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 10,
    path: "/static/Daniil/pornofilmy-ya_tak_soskuchilsya.2.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 11,
    path: "/static/Daniil/pornofilmy-ya_tak_soskuchilsya.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 12,
    path: "/static/Daniil/vivaldi_summer_part1.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 13,
    path: "/static/Daniil/vivaldi_summer_part2.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 14,
    path: "/static/Daniil/vivaldi_summer_part3.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 15,
    path: "/static/Daniil/vivaldi_summer_part3.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 16,
    path: "/static/Daniil/Vivaldi_-_Summer__The_Four_Seasons__-_Rousseau.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 17,
    path: "/static/Daniil/Sviridov_Time_Foward.1.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 18,
    path: "/static/blues_heads/Bags_Groove__Lead_sheet_.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 19,
    path: "/static/blues_heads/Billie_s_Bounce_Billies_Bounce.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 20,
    path: "/static/blues_heads/Blue_Rondo_A_La_Turk.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 21,
    path: "/static/blues_heads/Blues_for_Alice.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 22,
    path: "/static/blues_heads/Sandu.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 23,
    path: "/static/blues_heads/Blue_Monk_piano.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 24,
    path: "/static/blues_heads/Blues_in_the_Closet_Lead_sheet_.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 25,
    path: "/static/musescore_manual/Another_Love__-_Tom_Odell_Professional.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 26,
    path: "/static/musescore_manual/Canon_in_D.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 27,
    path: "/static/musescore_manual/Chopin_-_Nocturne_Op_9_No_2_E_Flat_Major.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 28,
    path: "/static/musescore_manual/Clair_de_Lune__Debussy.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 29,
    path: "/static/musescore_manual/Fr_Elise.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 30,
    path: "/static/musescore_manual/Game_of_Thrones_Easy_piano.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 31,
    path: "/static/musescore_manual/Golden_Hour__JVKE_Updated_Ver..mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 32,
    path: "/static/musescore_manual/Gymnopdie_No._1__Satie.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 33,
    path: "/static/musescore_manual/Hallelujah.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 34,
    path: "/static/musescore_manual/Interstellar.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 35,
    path: "/static/musescore_manual/Je_Te_Laisserai_Des_Mots_-_Patrick_Watson.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 36,
    path: "/static/musescore_manual/Merry_Go_Round_of_Life_Howls_Moving_Castle_Piano_Tutorial_.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 37,
    path: "/static/musescore_manual/One_Summers_Day_Spirited_Away.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 38,
    path: "/static/musescore_manual/Pirates_of_the_Caribbean_-_Hes_a_Pirate.mid",
    link: "https://musescore.com/user/24950681/scores/4601656",
    size: 1337,
    type: "file",
  },
  {
    idx: 39,
    path: "/static/musescore_manual/River_Flows_In_You.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 40,
    path: "/static/musescore_manual/Someone_You_Loved.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 41,
    path: "/static/musescore_manual/Sonate_No._14_Moonlight_1st_Movement.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 42,
    path: "/static/musescore_manual/Sonate_No._14_Moonlight_3rd_Movement.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 43,
    path: "/static/musescore_manual/Sweden_Minecraft.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 44,
    path: "/static/musescore_manual/Undertale_-_Megalovania_Piano_ver._3.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 45,
    path: "/static/musescore_manual/SENTINEL",
    size: 1337,
    type: "file",
  },
  {
    idx: 46,
    path: "/static/musescore_manual/All_I_Want_for_Christmas_is_You.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 47,
    path: "/static/musescore_manual/All_Of_Me_-_John_Legend_Piano_Cover_-_ReiK.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 48,
    path: "/static/musescore_manual/Attack_on_Titan_Shinzou_wo_Sasageyo.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 49,
    path: "/static/musescore_manual/Believer_-_Imagine_Dragons.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 50,
    path: "/static/musescore_manual/Bella_Ciao.mid",
    link: "https://musescore.com/user/26930991/scores/6106322",
    size: 1337,
    type: "file",
  },
  {
    idx: 51,
    path: "/static/musescore_manual/Carol_of_the_Bells.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 52,
    path: "/static/musescore_manual/Dawn_Pride_and_Prejudice.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 53,
    path: "/static/musescore_manual/Disney_Pixar_Up_Theme.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 54,
    path: "/static/musescore_manual/Ed_Sheeran_Perfect_THE_WORST_PIANO_ARRANGEMENT_I_HAVE_EVER_MADE.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 55,
    path: "/static/musescore_manual/Fallen_Down_Undertale.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 56,
    path: "/static/musescore_manual/Feliz_Navidad.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 57,
    path: "/static/musescore_manual/Fly_Me_to_the_Moon.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 58,
    path: "/static/musescore_manual/SENTINEL2",
    size: 1337,
    type: "file",
  },
  {
    idx: 59,
    path: "/static/musescore_manual/Godfather.mid",
    link: "https://musescore.com/user/16140171/scores/6244267",
    size: 1337,
    type: "file",
  },
  {
    idx: 60,
    path: "/static/musescore_manual/Gravity_Falls_Opening.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 61,
    path: "/static/musescore_manual/Jingle_Bell_Rock.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 62,
    path: "/static/musescore_manual/Jojo_s_Bizarre_Adventure_Golden_Wind_Giornos_Theme_Ver_2.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 63,
    path: "/static/musescore_manual/Kiss_The_Rain_-_Yiruma_-_10th_Anniversary_Version_Piano_Updated_2019.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 64,
    path: "/static/musescore_manual/Legend_of_Zelda_Great_Fairy_Fountain.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 65,
    path: "/static/musescore_manual/Let_It_Go_Disney_Frozen.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 66,
    path: "/static/musescore_manual/Liebestraum_No._3_in_A_Major.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 67,
    path: "/static/musescore_manual/Love_Like_You_Steven_Universe.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 68,
    path: "/static/musescore_manual/Love_Store_Francis_Lai.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 69,
    path: "/static/musescore_manual/Mad_world_Piano.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 70,
    path: "/static/musescore_manual/Mariage_dAmour.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 71,
    path: "/static/musescore_manual/Michael_Giaccino_Married_Life.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 72,
    path: "/static/musescore_manual/Moon_River_Breakfast_at_Tiffanys.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 73,
    path: "/static/musescore_manual/My_War_Attack_on_Titan.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 74,
    path: "/static/musescore_manual/Omori_Duet.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 75,
    path: "/static/musescore_manual/Pink_Panther.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 76,
    path: "/static/musescore_manual/Pokemon_Theme_Song.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 77,
    path: "/static/musescore_manual/Requiem_for_a_Dream.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 78,
    path: "/static/musescore_manual/Sadness_and_Sorrow.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 79,
    path: "/static/musescore_manual/Schindlers_List.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 80,
    path: "/static/musescore_manual/Someone_Like_You_easy_piano.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 81,
    path: "/static/musescore_manual/Summer_Joe_Hisaishi.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 82,
    path: "/static/musescore_manual/Super_Mario_Bros_Main_Theme.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 83,
    path: "/static/musescore_manual/Super_Mario_Bros_Peaches.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 84,
    path: "/static/musescore_manual/Test_Drive_How_to_Train_Your_Dragon.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 85,
    path: "/static/musescore_manual/Waltz_in_A_MinorChopin.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 86,
    path: "/static/musescore_manual/We_Dont_Talk_about_Bruno.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 87,
    path: "/static/musescore_manual/Wet_Hands_Minecraft.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 88,
    path: "/static/musescore_manual/Yann_Tiersen_Amelie.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 89,
    path: "/static/musescore_manual/Zeldas_Lullaby.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 90,
    path: "/static/musescore_manual/tude_S._1413_in_G_Minor_La_Campanella__Liszt.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 91,
    path: "/static/musescore_manual/A_Thousand_Miles.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 92,
    path: "/static/musescore_manual/Alone_Marshmello.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 93,
    path: "/static/musescore_manual/Avicii_Wake_me_up.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 94,
    path: "/static/musescore_manual/Avril_14_Aphex_Twin.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 95,
    path: "/static/musescore_manual/Axel_F_Beverly_Hills_Cop_III.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 96,
    path: "/static/musescore_manual/Billie_Eilish_Bad_Guy.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 97,
    path: "/static/musescore_manual/Bruno_Mars_When_I_was_your_man.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 98,
    path: "/static/musescore_manual/Cant_Help_Falling_In_Love.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 99,
    path: "/static/musescore_manual/Chris_Isaak_Wicked_Game.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 100,
    path: "/static/musescore_manual/Coffin_dance.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 101,
    path: "/static/musescore_manual/Despacito.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 102,
    path: "/static/musescore_manual/Dream_a_little_dream_of_me.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 103,
    path: "/static/musescore_manual/Ed_Sheeran_Shape_of_you.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 104,
    path: "/static/musescore_manual/Good_Bye_Hachiko.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 105,
    path: "/static/musescore_manual/Happy_Birthday_to_You.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 106,
    path: "/static/musescore_manual/Hit_the_Road_Jack.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 107,
    path: "/static/musescore_manual/How_long_blues.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 108,
    path: "/static/musescore_manual/Im_Blue_Eiffel_65.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 109,
    path: "/static/musescore_manual/John_Lennon_Imagine.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 110,
    path: "/static/musescore_manual/Johnny_Cash_Hurt.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 111,
    path: "/static/musescore_manual/Jolene.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 112,
    path: "/static/musescore_manual/Lady_Gaga_Always_remember_us_this_way.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 113,
    path: "/static/musescore_manual/Lena_Raine_Pigstep.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 114,
    path: "/static/musescore_manual/Let_Her_Go_Passenger.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 115,
    path: "/static/musescore_manual/Liana_Flores_Rises_the_Moon.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 116,
    path: "/static/musescore_manual/Lovely_Billie_Eilish.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 117,
    path: "/static/musescore_manual/Never_Gonna_Give_You_Up.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 118,
    path: "/static/musescore_manual/Ophelia.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 119,
    path: "/static/musescore_manual/Photograph_Ed_Sheeran.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 120,
    path: "/static/musescore_manual/Sweet_Dreams.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 121,
    path: "/static/musescore_manual/Sweet_home_Chicago.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 122,
    path: "/static/musescore_manual/Take_on_me.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 123,
    path: "/static/musescore_manual/TheFatRat_Monody.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 124,
    path: "/static/musescore_manual/TheFatRat_Unity.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 125,
    path: "/static/musescore_manual/The_Weeknd_Blinding_Lights.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 126,
    path: "/static/musescore_manual/Titanic.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 127,
    path: "/static/musescore_manual/Vangelis_Chariots_of_fire.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 128,
    path: "/static/musescore_manual/Viva_La_Vida_Coldplay.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 129,
    path: "/static/musescore_manual/Wellerman_Sea_Shanty.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 130,
    path: "/static/musescore_manual/Alice_DJ_Better_Off_Alone.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 131,
    path: "/static/musescore_manual/Sviridov_Snowstorm_Waltz.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 132,
    path: "/static/musescore_manual/Flight_Facilities_Crave_You.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 133,
    path: "/static/musescore_manual/Flight_Facilities_Crave_You_2.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 134,
    path: "/static/musescore_manual/Morphine_Cure_for_Pain.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 135,
    path: "/static/musescore_manual/The_Strokes_Reptilia.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 136,
    path: "/static/musescore_manual/The_Strokes_Reptilia_2.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 137,
    path: "/static/musescore_manual/The_Strokes_Reptilia_3.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 138,
    path: "/static/musescore_manual/Walking_On_a_dream.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 139,
    path: "/static/musescore_manual/You_and_whose_army.mid",
    size: 1337,
    type: "file",
  },
  {
    idx: 140,
    path: "/static/musescore_manual/Godfather.1.mid",
    link: "https://musescore.com/user/9265496/scores/2049321",
    size: 1337,
    type: "file",
  },
  {
    idx: 141,
    path: "/static/musescore_manual/smth.mid",
    // link: "https://musescore.com/user/16693/scores/38133",
    // based on it, not exactly
    size: 1337,
    type: "file",
  },
  {
    idx: 142,
    path: "/static/musescore_manual/smth2.mid",
    link: "https://musescore.com/user/37758827/scores/6833120/",
    size: 1337,
    type: "file",
  },
  {
    idx: 143,
    path: "/static/urfu/Prelude_in_G_Minor_Opus_23_No._5.mid",
    link: "https://musescore.com/user/2660886/scores/6026988",
    size: 1337,
    type: "file",
  },
  {
    idx: 144,
    path: "/static/urfu/Waltz_No._2_The_Second_Waltz_by_Dmitri_Shostakovich_for_Piano.mid",
    link: "https://musescore.com/minh_cuteee/scores/6555384",
    size: 1337,
    type: "file",
  },
  {
    idx: 145,
    path: "/static/urfu/ludovico-einaudi-una-mattina.mid",
    link: "https://www.nonstop2k.com/midi-files/11642-ludovico-einaudi-una-mattina-midi.html",
    size: 1337,
    type: "file",
  },
  {
    idx: 146,
    path: "/static/urfu/maneskin_honey_are_u_comingv1rock.mid",
    link: "https://musescore.com/user/7484921/scores/15314107/",
    size: 1337,
    type: "file",
  },
];

export default STATIC_MIDI_FILES;
