import { canonicalArtistName } from "./artistShelves";
import { RockPopEra } from "./rockPopFacets";

// Editorial era assignments for the wider directory. Unidentified folders and
// generic collections stay undated; dates are never inferred from MIDI files.
// Dutch additions: early releases in nldiscografie.nl (de-electronicas,
// gebroeders-grimm, dingetje, franky-boy, renee-de-haan, jantje-koopmans,
// palemiger-spatzen, bill-and-jodie-lee); De Migra's formed in 1963
// (helenas.nl/2015/10/24/the-story-of-toon-van-de-burgt/), De Nachroave
// in 1979 (streektaalzang.nl/strk/limb/limbnacn.htm), Assekruus in 1982
// (st-anneke.nl, December 2023 bulletin). C'est Tout's site describes a
// 40-year history; Nico Landers' biography documents performances in 1993.
const eraArtists: Partial<Record<RockPopEra, string[]>> = {
  before1955: [
    // Re-reviewed unclassified folders, using artist/repertoire dates.
    "Baxter",
    "Derby",
    "Faith",
    "Freddy Martin",
    "Garland",
    "Greger",
    "Herman",
    "Heywood",
    "Hughie Cannon",
    "Johnson",
    "LANZA",
    "Robert Hampton",
    "Vaughn",
    "Warren",
    "Al Jolson",
    "Annie Cordy",
    "Atkins Chet",
    "B.B. King",
    "Bach Johann Sebastian",
    "Barber Samuel",
    "Basie",
    "Bela Bartok",
    "Belafonte Harry",
    "Benjamin Arthur",
    "Berlin Irving",
    "Billy Mayerl",
    "Bizet Georges",
    "Borodin",
    "Brown Clarence Gatemouth",
    "Burton Lane",
    "Carl Teike",
    "Carmina Burana",
    "Cesar Franck",
    "Charles Aznavour",
    "Charles-Valentin Alkan",
    "Chopin Frederic",
    "Chris Barber's Jazz Band",
    "Christoph Willibald Gluck",
    "Claude Bolling",
    "Claude Debussy",
    "Clementi",
    "Cole Porter",
    "Dave Brubeck",
    "Davis Miles",
    "Delibes Leo",
    "Dick Hyman",
    "Dietrich Marlene",
    "Digno Garcia",
    "Donna Hightower",
    "Dorsey",
    "Duke Ellington",
    "Dvorak",
    "Eddy Arnold",
    "Edvard Grieg",
    "Emmanuel Chabrier",
    "Ernst Neger",
    "Erroll Garner",
    "Esther Phillips",
    "Eubie Blake",
    "FAURE Gabriel",
    "Falla",
    "Fitzgerald Ella",
    "Francois Couperin",
    "George Frideric Handel",
    "George M. Cohan",
    "Georges Brassens",
    "Gerry Mulligan Quartet",
    "Gershwin",
    "Gilbert & Sullivan",
    "Gilbert Becaud",
    "Gillespie Dizzy",
    "Glenn Miller",
    "Gounod Charles",
    "Granados Enrique",
    "Hank Jones",
    "Hank Williams",
    "Hans Albers",
    "Hawkins Erskine",
    "Haydn",
    "Henry Mancini",
    "Hines Earl",
    "Holiday Billie",
    "Jackie McLean",
    "Jerome Kern",
    "Jimmy Reed",
    "Johann Nepomuk Hummel",
    "Johannes Brahms",
    "John Field",
    "John Lee Hooker",
    "Johnny Hoes",
    "Johnny Mercer",
    "Johnny Shines",
    "Johnson James P",
    "Jolson. Al",
    "Joseph Kosma",
    "Joseph Lamb",
    "Jule Styne",
    "Julie Andrews",
    "Karas Anton",
    "Kenny Dorham",
    "Laine Cleo",
    "Lena Horne",
    "Leo Friedman",
    "Leonard Bernstein",
    "Lewis George",
    'Lewis Meade "lux"',
    "Lloyd Price",
    "Loesser",
    "Louis Armstrong",
    "Louis Moreau Gottschalk",
    "Louis Prima",
    "Ludwig van Beethoven",
    "Mahalia Jackson",
    "Marilyn Monroe",
    "Merle Travis",
    "Mily Balakirev",
    "Modern Jazz Quartet",
    "Morton Jelly Roll",
    "Mosch",
    "Nat King Cole",
    "Oscar Peterson",
    "Parker Charlie",
    "Paul Desmond",
    "Paul Dukas",
    "Percy Faith",
    "Percy Grainger",
    "Powell Bud",
    "Professor Longhair",
    "Quincy Jones",
    "RODGERS RICHARD",
    "Rascel",
    "Ray Charles",
    "Reinhardt Django",
    "Rene Carol",
    "Rich , Buddy",
    "Roger Williams",
    "Rufus Thomas",
    "Sauter-Finegan Orchestra",
    "Scott James",
    "Scott Joplin",
    "Shearing George",
    "Stan Getz",
    "Stan Kenton",
    "Tatum Art",
    "The Ramsey Lewis Trio",
    "Thelonious Monk",
    "Thomas Campion",
    "Tom Turpin",
    "Vaughan Sarah",
    "Wagner",
    "Waller Fats",
    "Walter Donaldson",
    "Washington Dinah",
    "Whiteman Paul & His Orchestra",
    "Will Glahe",
    "Wilson Teddy",
    "Wolfgang Amadeus Mozart",
    "Xavier Cugat",
    "Zequinha Abreu",
    "Zez Confrey",
    "elgar",
  ],
  "1955": [
    // Re-reviewed unclassified folders, using artist/repertoire dates.
    "Ann Farina",
    "Antonio Carlos",
    "Calvert",
    "Fontana",
    "Playmates",
    "Robinson",
    "Solo",
    "The Charmaines",
    "Watanabe",
    "101 Strings",
    "Aaron Neville",
    "Adriano Celentano",
    "Al Hirt",
    "Alexander Peter",
    "Allen Toussaint",
    "Anthony Richard",
    "Aretha Franklin",
    "Barry John",
    "Ben E. King",
    "Bilk",
    "Bob James",
    "Bobby Bare",
    "Boris Gardiner",
    "Buck Owens",
    "Burt Bacharach",
    "Byrd Charlie",
    "Carole King",
    "Charlie Rich",
    "Conway Twitty",
    "Dallara",
    "Danyel Gerard",
    "Dave Grusin",
    "Ed Townsend",
    "Ernie K-Doe",
    "Evans Bill",
    "Floyd Cramer",
    "Gary Burton",
    "George Benson",
    "Heidi Bruhl",
    "Herbie Mann",
    "Hugues Aufray",
    "Jackie Wilson",
    "James Brown",
    "Jerry Herman",
    "Jobim Antonio Carlos",
    "Johnny Cash",
    "Johnny Horton",
    "Kaempfert",
    "Kenny Baker",
    "Lewis Ramsey",
    "Little Tony",
    "Melina Mercouri",
    "Mina",
    "Morricone Ennio",
    "Mouskouri Nana",
    "Nelson Oliver",
    "Nina Simone",
    "Oberkrainer",
    "Ornella Vanoni",
    "Patsy Cline",
    "Paul Simon",
    "Peter Koelewijn & Zijn Rockets",
    "Rocco Granata",
    "Sam Cooke",
    "Sammy Nestico",
    "Sheb Wooley",
    "Smokey Robinson",
    "The Brothers Four",
    "The Drifters",
    "The Isley Brothers",
    "The Shadows",
    "The The Kingston Trio",
    "The Ventures",
    "Theodorakis Mikis",
    "Tommy Flanagan",
    "Torriani, Vico",
    "Trini Lopez",
    "Vince Guaraldi",
    "Watson Johnny Guitar",
    "Willie Nelson",
  ],
  "1963": [
    // Representative repertoire: Willy Alberti's 1968 recording, also covered
    // by Willeke. https://www.top40.nl/willy-alberti/de-glimlach-van-een-kind-2115
    "Alberti",
    // Re-reviewed unclassified folders, using artist/repertoire dates.
    "Alpert",
    "Bell",
    "Classics",
    "Ekseption",
    "Glover",
    "Haak",
    "Knight",
    "Last",
    "Reeves",
    "Roberts",
    "Ross",
    "Sergio",
    "Sly",
    "Toys",
    "Vera",
    "De Electronica's",
    "De Migra's",

    "AL Bano",
    "Adam & Eve",
    "Al Green",
    "Al Stewart",
    "Al Wilson",
    "Alain Barriere",
    "Alain Bashung",
    "Alain Chamfort",
    "Albert West",
    "Alexandra",
    "Alice",
    "Alice Cooper",
    "Allan Sherman",
    "Alunni del Sole",
    "Amedeo Minghi",
    "Andre Brasseur",
    "Andre van Duin",
    "Andrew Lloyd Webber",
    "Ann Peebles",
    "Anne Murray",
    "Antoine",
    "Aphrodite's Child",
    "Astrud Gilberto",
    "BRECK,FREDDY",
    "BZN",
    "Barclay James Harvest",
    "Battiato",
    "Ben Cramer",
    "Berger Michel",
    "Billie Jo Spears",
    'Billy "Crash" Craddock',
    "Billy Paul",
    "Billy Preston",
    "Birkin",
    "Blue Oyster Cult",
    "Bob Dylan",
    "Bob Marley",
    'Bobby "Boris" Pickett',
    "Bobby Prins",
    "Bonzo Dog Doo Dah Band",
    "Booker T. & The MG's",
    "Boothe, Ken",
    "Boz Scaggs",
    "Brenton Wood",
    "Brewer And Shipley",
    "Buffalo Springfield",
    "Camaleonti",
    "Candi Staton",
    "Canned Heat",
    "Caterina Caselli",
    "Charlebois Robert",
    "Chick Corea",
    "Chip Taylor",
    "Chris Roberts",
    "Chuck Mangione",
    "Cindy & Bert",
    "Claude Francois",
    "Claudio Baglioni",
    "Clerc Julien",
    "Croce Jim",
    "Crosby, Stills, Nash & Young",
    "Crusaders",
    "Curtis Mayfield",
    "Dalla Lucio",
    "Deep Purple",
    "Delfonics the",
    "Desmond Dekker",
    "Detroit Emeralds",
    "Diana Ross",
    "Dik Dik",
    "Dionne Warwick",
    "Dobie Gray",
    "Don Backy",
    "Don McLean",
    "Donovan",
    "Dr. John",
    "Drafi Deutscher",
    "Dusty Springfield",
    "Eddie Floyd",
    "Eddie Holman",
    "Eddy Grant",
    "Edward Kleban",
    "Elvin Bishop",
    "Equipe 84",
    "Eric Clapton",
    "Fairport Convention",
    "Focus",
    "Fontella Bass",
    "Four Tops",
    "Freda Payne",
    "Gene Chandler",
    "Genesis",
    "Gerard Cox",
    "Gianni Bella",
    "Gibson Brothers",
    "Gino Paoli",
    "Gladys Knight",
    "Glen Campbell",
    "Gordon Lightfoot",
    "Gwen McCrae",
    "Haggard. Merle",
    "Hans Dulfer",
    "Harold Melvin",
    "Herb Alpert",
    "Herbie Hancock",
    "Holm, Michael",
    "Hot Chocolate",
    "Howard Carpendale",
    "Ike & Tina Turner",
    "Imca Marina",
    "Isaac Hayes",
    "J.J. Jackson",
    "Jackson 5",
    "James Last",
    "James Taylor",
    "Janis Ian",
    "Jeannie C. Riley",
    "Jethro Tull",
    "Jim Croce",
    "Jimmy Cliff",
    "Jimmy James",
    "Jimmy McGriff",
    "Jimmy Ruffin",
    "Joe Dassin",
    "Johnny Bristol",
    "Joni Mitchell",
    "Jose Feliciano",
    "Judy Collins",
    "Julio Iglesias",
    "Junior Walker",
    "King Crimson",
    "Kool & The Gang",
    "LaBelle",
    "LaSalle",
    "Leali",
    "Led Zeppelin",
    "Leon Russell",
    "Liesbeth List",
    "Linda Ronstadt",
    "Los Del Rio",
    "Lou Rawls",
    "Lou Reed",
    "Love Sculpture",
    "Lucio Battisti",
    "Luther Ingram",
    "Lynn Anderson",
    "Marianne Faithfull",
    "Martha Reeves",
    "Marvin Gaye",
    "Marvin Hamlisch",
    "Mary Wells",
    "Mason Williams",
    "Melanie",
    "Michael Jackson",
    "Michel Delpech",
    "Mocedades",
    "Monty Python",
    "Morandi",
    "Neil Young",
    "Nini Rosso",
    "Nomadi",
    "Nuovi Angeli",
    "Otis Redding",
    "Pagliaro",
    "Paoli",
    "Parton Dolly",
    "Patricia Paay",
    "Paul Mauriat",
    "Peppino di Capri",
    "Percy Sledge",
    "Peter Tosh",
    "Peter, Paul & Mary",
    "Pink Floyd",
    "Poco",
    "Pooh",
    "Procol Harum",
    "Raffaella Carra",
    "Randy Newman",
    "Ranieri",
    "Roberta Flack",
    "Rogers Kenny",
    "Roy Black",
    "Roy Clark",
    "Rudi Carrell",
    "Salvatore Adamo",
    "Sam & Dave",
    "Sandy Denny",
    "Santana",
    "Scott McKenzie",
    "Sergio Franchi",
    "Sergio Mendes",
    "Simon & Garfunkel",
    "Sly & The Family Stone",
    "Spinners",
    "Stevie Wonder",
    "Tammy Wynette",
    "Ted Nugent",
    "Ten Years After",
    "The Archies",
    "The Byrds",
    "The Chi-Lites",
    "The Contours",
    "The Five Stairsteps",
    "The Foundations",
    "The Main Ingredient",
    "The Manhattans",
    "The Moody Blues",
    "The O'Jays",
    "The Rooftop Singers",
    "The Seekers",
    "The Soul Survivors",
    "The Spotnicks",
    "The Stylistics",
    "The Supremes",
    "The Temptations",
    "The Whispers",
    "Thelma Houston",
    "Three degrees the",
    "Tina Turner",
    "Tony Joe White",
    "Tornados",
    "Traffic",
    "Trio Hellenique",
    "Tyner Mccoy",
    "Van McCoy",
    "Willeke Alberti",
    "Wilson Pickett",
    "Womack",
    "Yes",
    "Zamfir Gheorghe",
    "Zappa",
  ],
  "1970": [
    // Margot Werner began recording as a singer in 1972; "So ein Mann" (1977).
    // https://www.bmlo.lmu.de/w1165
    "Werner",
    // Re-reviewed unclassified folders, using artist/repertoire dates.
    "Amanda McBroom",
    "Droids",
    "Duval",
    "McDonald",
    "Meco",
    "Phyllis Nelson",
    "Rah Band",
    "Santo",
    "Soulful Dynamics",
    "Supermax",
    "The Chaplin Band",
    "De Nachroave",
    "Dingetje",
    "Gebroeders Grimm",

    ".38 Special",
    "A Taste of Honey",
    "AC DC",
    "Ace Frehley",
    "Aerosmith",
    "Al Jarreau",
    "Alabama",
    "Alain Souchon",
    "Alan Parsons",
    "Alberto Fortis",
    "Amii Stewart",
    "Ana Belen",
    "Andre Hazes",
    "Andre Moss",
    "Angelo Branduardi",
    "Anita Meyer",
    "Anita Ward",
    "Anna Oxa",
    "Antonello Venditti",
    "Apollo 100",
    "Aswad",
    "Au bonheur des dames",
    "Average White Band",
    "B.W. Stevenson",
    "BAP",
    "Barry White",
    "Bellamy Brothers",
    "Beres Hammond",
    "Bernd Cluver",
    "Bernhard Brink",
    "Berte",
    "Bill Withers",
    "Billy Ocean",
    "Bino",
    "Black Fooss",
    "Black Sabbath",
    "Blattschuss",
    "Boney M.",
    "Bonnie Raitt",
    "Bryson",
    "Byron Berline",
    "CASIOPEA",
    "CORDALIS,COSTA",
    "Calimeros",
    "Camel",
    "Cameo",
    "Carl Douglas",
    "Carly Simon",
    "Carra",
    "Chaka Khan",
    "Cheryl Lynn",
    "Chic",
    "Chip Davis",
    "Claude-Michel Schonberg",
    "Claudia Schmidt",
    "Cocciante",
    "Commander Cody",
    "Commodores",
    "Cornelius Brothers",
    "Corry Konings",
    "Crystal Gayle",
    "Dan Fogelberg",
    "Daniele",
    "David Foster",
    "De Havenzangers",
    "Dennie Christian",
    "Derek and the Dominos",
    "Devo",
    "Doe Maar",
    "Donna Summer",
    "Drukwerk",
    "Drupi",
    "Duke Robillard",
    "Earth, Wind & Fire",
    "Eddie Kendricks",
    "Electric Light Orchestra",
    "Elvis Costello",
    "Emerson, Lake & Palmer",
    "Fat Larry's Band",
    "Fiorella Mannoia",
    "Fossati Ivano",
    "Francesco De Gregori",
    "Francis Cabrel",
    "Frank & Mirella",
    "Frank Mills",
    "Freek de Jonge",
    "Gary Moore",
    "George McCrae",
    "George Thorogood",
    "Giorgio Moroder",
    "Gipsy Kings",
    "Gloria Estefan",
    "Gloria Gaynor",
    "Goblin",
    "Godspell",
    "Grace Jones",
    "Graziani",
    "Grease",
    "Gregori",
    "Gruppo Sportivo",
    "HORNER JAMES",
    "Harry Chapin",
    "Heatwave",
    "Henry Arland",
    "Hohner",
    "Honey Cone",
    "Hot Butter",
    "Hues Corporation",
    "Inner Circle",
    "J.J. Cale",
    "Jackson Browne",
    "Jaco Pastorius",
    "Jan Hammer",
    "Jean Knight",
    "Jean Michel Jarre",
    "Jimmy Buffett",
    "Joey Ramone",
    "John Denver",
    "John Scofield",
    "Judas Priest",
    "Julie Covington",
    "Jurgen Drews",
    "KC and The Sunshine Band",
    "KING,RICKY",
    "Kansas",
    "Kate Bush",
    "Kiss",
    "Kraftwerk",
    "Kris Kristofferson",
    "La Bionda",
    "Le Grand Orchestre du Splendid",
    "Lee Ritenour",
    "Les Humphries Singers",
    "Lionel Richie",
    "Lipps, Inc.",
    "Loggins & Messina",
    "Los Lobos",
    "Love Unlimited Orchestra",
    "Luther Vandross",
    "MFSB",
    "Mac Davis",
    "Major Harris",
    "Mango",
    "Maria Muldaur",
    "Mark Snow",
    "Marky Ramone",
    "Massada",
    "Matia Bazar",
    "Maxime Le Forestier",
    "McFadden & Whitehead",
    "Mezzoforte",
    "Miami Sound Machine",
    "Michael McDonald",
    "Michael Zager",
    "Michele Zarrillo",
    "Mike Oldfield",
    "Murray Head",
    "Natalie Cole",
    "Nazareth",
    "Norman Blake",
    "Norman Connors",
    "Odyssey",
    "Ohio Players",
    "Pat Metheny",
    "Patti Smith",
    "Peaches & Herb",
    "Peter Cornelius",
    "Peter Gabriel",
    "Peter Maffay",
    "Prince",
    "Rainbow",
    "Randy Crawford",
    "Ray Parker Jr.",
    "Raydio",
    "Real Thing",
    "Renato Teixeira",
    "Renzo Arbore",
    "Riccardo Cocciante",
    "Ricchi e Poveri",
    "Richard Clayderman",
    "Rick James",
    "Rickie Lee Jones",
    "Rocky Horror",
    "Romina Power Al Bano",
    "Ron",
    "Rory Block",
    "Rose Royce",
    "Roxy Music",
    "Rufus",
    "Ruggeri",
    "Rush",
    "Ry Cooder",
    "Sammy Hagar",
    "Scorpions",
    "Seals & Crofts",
    "Silver Convention",
    "Sister Sledge",
    "Sorrenti",
    "Spyro Gyra",
    "Stanley Clarke",
    "Stephanie Mills",
    "Styx",
    "Supertramp",
    "Sylvester",
    "T-Square",
    "Talking Heads",
    "Tavares",
    "The Alan Parsons Project",
    "The B-52's",
    "The Bluegrass Cardinals",
    "The Blues Brothers",
    "The Boomtown Rats",
    "The Brecker Brothers",
    "The Clash",
    "The Cure",
    "The Fabulous Thunderbirds",
    "The Gap Band",
    "The Manhattan Transfer",
    "The Marshall Tucker Band",
    "The Pointer Sisters",
    "The Pretenders",
    "The Ritchie Family",
    "The Robert Cray Band",
    "The Rutles",
    "The Stranglers",
    "The Sugarhill Gang",
    "The Sylvers",
    "The Trammps",
    "Thin Lizzy",
    "Todd Rundgren",
    "Tom Astor",
    "Tower of Power",
    "UB40",
    "Umberto Tozzi",
    "Uriah Heep",
    "Van Halen",
    "Vangelis",
    "Vasco Rossi",
    "Village People",
    "War",
    "Warren Zevon",
    "Wayne Jeff",
    "Weather Report",
    "Westernhagen",
    "Whitesnake",
    "Wild Cherry",
    "Wolfgang Ambros",
    "Yellow Magic Orchestra (YMO)",
    "Youssou N'Dour",
    "ZZ Top",
    "Zero",
  ],
  "1980": [
    // Marco Armani: "Solo con l'anima mia", Sanremo 1984.
    "Armani",
    // Kurt Elsasser recorded as Daniel in the mid-1980s.
    "Daniel",
    // Re-reviewed unclassified folders, using artist/repertoire dates.
    "Big Mr.",
    "Carpenter",
    "Davis John",
    "Fluid",
    "Forrest",
    "Gordon",
    "Grant & Forsyth",
    "James Colin",
    "Jets",
    "Taja Sevelle",
    "Trinere",
    "Vega",
    "C'est Tout",
    "Renee de Haan",
    "Sugar Lee Hooper",
    "Assekruus",
    "Franky Boy",
    "Jantje Koopmans",

    '"Weird Al" Yankovic',
    "10,000 Maniacs",
    "808 State",
    "Acoustic Alchemy",
    "Adamski",
    "Adventures of Stevie V.",
    "Alexander O'Neal",
    "Alpentrio Tirol",
    "Amina",
    "Ana Caram",
    "Anita Baker",
    "Art of Noise",
    "Asia",
    "Atlantic Starr",
    "BAGINSKY,GABY",
    "BUTLER, JONATHAN",
    "Babyface",
    "Baltimora",
    "Banda Blanca",
    "Beastie Boys",
    "Beloved",
    "Biagio Antonacci",
    "Black Box",
    "Blind Guardian",
    "Bobby Brown",
    "Bobby McFerrin",
    "Bon Jovi",
    "Borg Andy",
    "Bronski Beat",
    "Brunner & Brunner",
    "Calloway",
    "Carboni",
    "Cats",
    "Chaka Demus",
    "Champaign",
    "Chastain",
    "Clouseau",
    "DJ Jazzy Jeff",
    "DULFER, CANDY",
    "David Lee Roth",
    "De Deurzakkers",
    "De Dijk",
    "Dead Or Alive",
    "Def Leppard",
    "Deniece Williams",
    "Depeche Mode",
    "Desireless",
    "Die Arzte",
    "Dr. Dre",
    "Dream Theater",
    "Echo & The Bunnymen",
    "El DeBarge",
    "Elsa",
    "Enya",
    "Erasure",
    "Eros Ramazzotti",
    "Europe",
    "Extreme",
    "Faith No More",
    "Falco",
    "Fat Boys",
    "Fay Lovsky",
    "Firehouse",
    "Frankie Goes to Hollywood",
    "Freakwater",
    "Freddie Jackson",
    "G. G. Anderson",
    "Garth Brooks",
    "Gerard Joling",
    "Goo Goo Dolls",
    "Great White",
    "Guesch Patti",
    "Guns N' Roses",
    "Harold Faltermeyer",
    "Henry Butler",
    "Het Goede Doel",
    "Huub Hangop",
    "Ice Cube",
    "Images",
    "Imagination",
    "Incognito",
    "Information Society",
    "Ingram James",
    "Inner City",
    "Iron Maiden",
    "Isabelle Adjani",
    "Jamaaladeen Tacuma",
    "James",
    "Jane's Addiction",
    "Janet Jackson",
    "Jeffrey Osborne",
    "Jeffrey Reid Baker",
    "Jody Watley",
    "Joe Dolce",
    "Johnny Gill",
    "Johnny Kemp",
    "Jon Cleary",
    "Jovanotti",
    "Juan Luis Guerra",
    "Kamoze Ini",
    "Kaoma",
    "Kenny G",
    "Klaus & Klaus",
    "Klein Orkest",
    "Koos Alberts",
    "Kristina Bach",
    "LL Cool J",
    "Lenny Kravitz",
    "Lisa Lisa",
    "Lisa Stansfield",
    "Lois Lane",
    "MC Hammer",
    "Malmsteen Yngwie",
    "Marianne & Michael",
    "Marillion",
    "Matt Bianco",
    "Maxi Priest",
    "Meat Puppets",
    "Mecano",
    "Megadeth",
    "Melissa Etheridge",
    "Metallica",
    "Mica Paris",
    "Michael Ball",
    "Michael Walthius",
    "Midnight Oil",
    "Modern Talking",
    "Motley Crue",
    "Mylene Farmer",
    "NOFX",
    "Natalie Merchant",
    "Nena",
    "New Order",
    "Night Ranger",
    "Nine Inch Nails",
    "Nino De Angelo",
    "Oingo Boingo",
    "Oleta Adams",
    "Omar",
    "Ozzy Osbourne",
    "Pantera",
    "Pato Banton",
    "Patrick Bruel",
    "Paul de Leeuw",
    "Pet Shop Boys",
    "Peter Schilling",
    "Phish",
    "Queensryche",
    "Quiet Riot",
    "R.E.M.",
    "Raf",
    "Ratt",
    "Red Hot Chili Peppers",
    "Rene Froger",
    "Renee Rosnes",
    "Restless Heart",
    "Righeira",
    "Rockwell",
    "Sabrina",
    "Sade",
    "Salt-N-Pepa",
    "Sarah McLachlan",
    "Sawyer Brown",
    "Schilling, Peter",
    "Selena",
    "Shakatak",
    "Shanice",
    "Shawn Colvin",
    "Simply Red",
    "Sinead O'Connor",
    "Skid Row",
    "Soft Cell",
    "Sonic Youth",
    "Soul Asylum",
    "Soul II Soul",
    "Soundgarden",
    "Special EFX",
    "Steps Ahead",
    "Stern Mike",
    "Steve Vai",
    "Surface",
    "Suzanne Ciani",
    "Suzanne Vega",
    "Swing Out Sister",
    "Sydney Youngblood",
    "Talk Talk",
    "Tanita Tikaram",
    "Technotronic",
    "Terence Trent D'Arby",
    "The Beautiful South",
    "The Cult",
    "The Human League",
    "The KLF",
    "The Lemonheads",
    "The Mighty Mighty Bosstones",
    "The Pasadenas",
    "The Psychedelic Furs",
    "The Rippingtons",
    "The Shamen",
    "The Smiths",
    "The Tragically Hip",
    "They Might Be Giants",
    "Toad the Wet Sprocket",
    "Tom McDermott",
    "Tone-Loc",
    "Tracy Chapman",
    "Trans-X",
    "Trio",
    "UZEB",
    "VOF de Kunst",
    "Vanessa Paradis",
    "Vanessa Williams",
    "Victoria Williams",
    "Violent Femmes",
    "Visage",
    "Was (Not Was)",
    "Westbam",
    "White Lion",
    "White Zombie",
    "Whitney Houston",
    "Will Smith",
    "William Orbit",
    "Winger",
    "Wolter Kroes",
    "Yanni",
    "Yazoo",
    "Yazz & plastic population",
    "Zucchero",
    "k.d. lang",
  ],
  "1990": [
    // Debut recordings: Bruno & Marrone (1994), Rick & Renner (1992).
    // https://dicionariompb.com.br/grupo/bruno-e-marrone/
    // https://dicionariompb.com.br/grupo/rick-e-renner/
    "Bruno",
    "Rick",
    // "Oh Middernacht" (1995): https://www.top40.nl/flair/flair-oh-middernacht-6033
    "Flair",
    // Re-reviewed unclassified folders, using artist/repertoire dates.
    "2Boys",
    "BND",
    "Bauer",
    "Bolero",
    "Bommbastic",
    "Bone",
    "Carey",
    "Chocolate",
    "Cosmix",
    "Double Vision",
    "Duke",
    "Freak Power",
    "K2",
    "K7",
    "KWS",
    "Lavinia Jones",
    "Prince Ital Joe",
    "Quartz",
    "Red",
    "Shalom",
    "Talk of the Town",
    "Tatyana Ali",
    "Tears n' Joy",
    "The Commitments",
    "Nico Landers",
    "Palemiger Spatzen",

    "2 Brothers on the 4th Floor",
    "2 Unlimited",
    "20 Fingers",
    "311",
    "3T",
    "4 Non Blondes",
    "702",
    "883",
    "Aaliyah",
    "Adiemus",
    "Alan Jackson",
    "Alanis Morissette",
    "Alexia",
    "Alice in Chains",
    "Alien Ant Farm",
    "Alizee",
    "All-4-One",
    "Allan Theo",
    "Alliage",
    "Allure",
    "Alpenrebellen",
    "Amber",
    "Ambra",
    "Amie Comeaux",
    "Andre & Adriano",
    "Andrea Bocelli",
    "Anggun",
    "Aqua",
    "Army of Lovers",
    "Arrested Development",
    "Articolo 31",
    "Assia",
    "Atlantic Ocean",
    "Axelle Red",
    "B.G. The Prince of Rap",
    "BBE",
    "Baby D",
    "Barenaked Ladies",
    "Bart Herman",
    "Beck",
    "Ben Folds Five",
    "Bert Heerink",
    "Big Bad Voodoo Daddy",
    "Big Mountain",
    "Billy Ray Cyrus",
    "Bjork",
    "Black Rob",
    "Blackstreet",
    "Blaque",
    "Blind Melon",
    "Bloodhound Gang",
    "Blues Traveler",
    "Blumchen",
    "Blur",
    "Bombalurina",
    "Bomfunk MC's",
    "Boney James",
    "Booming Support",
    "Boyz II Men",
    "Brandy",
    "Brian McKnight",
    "Brooks & Dunn",
    "Buena Vista Social Club",
    "Bush",
    "Busta Rhymes",
    "C+C Music Factory",
    "C.J. Lewis",
    "CB Milton",
    "Cake",
    "Capella",
    "Captain Hollywood Project",
    "Captain Jack",
    "Centory",
    "Charles & Eddie",
    "Cherry Poppin' Daddies",
    "Chumbawamba",
    "Collective Soul",
    "Color Me Badd",
    "Confederate Railroad",
    "Coolio",
    "Corduroy",
    "Corona",
    "Counting Crows",
    "Crash Test Dummies",
    "Creed",
    "Crystal Waters",
    "Culture Beat",
    "Cut 'n' Move",
    "D:Ream",
    "DJ BoBo",
    "DJ Paul Elstak",
    "DJ Quicksilver",
    "DMX",
    "Daft Punk",
    "Dance 2 Trance",
    "Danilo Amerio",
    "Darude",
    "Dave Matthews Band",
    "Deep Blue Something",
    "Deftones",
    "Des'ree",
    "Destiny's Child",
    "Diana King",
    "Die Doofen",
    "Die Fantastischen Vier",
    "Dina Carroll",
    "Dirotta su Cuba",
    "Dixie Chicks",
    "Dolls United",
    "Double You",
    "Dr. Alban",
    "Dune",
    "E-Rotic",
    "E-Type",
    "EMF",
    "East Side Beat",
    "Eels",
    "Eiffel 65",
    "Eminem",
    "En Vogue",
    "Energy 52",
    "Enigma",
    "Enrique Iglesias",
    "Eve 6",
    "Everclear",
    "Everlast",
    "Fabi",
    "Faith Evans",
    "Faithless",
    "Fastball",
    "Fatboy Slim",
    "Filter",
    "Fiona Apple",
    "Fiorello",
    "Fluitsma",
    "Foo Fighters",
    "Fourplay",
    "Frank Galan",
    "Frans Bauer",
    "Fugees",
    "Fun Factory",
    "Gabber Piet",
    "Gala",
    "Garbage",
    "Gatto Panceri",
    "Gin Blossoms",
    "Gina G",
    "Giorgia",
    "Godsmack",
    "Gompie",
    "Grandi",
    "Green Day",
    "Groove Theory",
    "Haddaway",
    "Hakkuhbar",
    "Harvey Danger",
    "Hole",
    "Hollenboer",
    "Home Grown",
    "Hootie & the Blowfish",
    "Ice MC",
    "Imperial Teen",
    "Interactive",
    "Intermission",
    "Jam & Spoon",
    "Jamiroquai",
    "Jars of Clay",
    "Jesus Jones",
    "Jewel",
    "Jodeci",
    "Joe",
    "Joe Diffie",
    "Jon Secada",
    "Jordy",
    "K-Ci & JoJo",
    "Kadoc",
    "Kenny Thomas",
    "Kid Rock",
    "Korn",
    "LIGABUE",
    "La Bouche",
    "LaTour",
    "Laura Pausini",
    "LeAnn Rimes",
    "Limp Bizkit",
    "Linda, Roos & Jessica",
    "Linkin Park",
    "Lisa Loeb",
    "Lit",
    "Little Texas",
    "Live",
    "Local H",
    "Loft",
    "Lou Bega",
    "Lunapop",
    "Luniz",
    "Lutricia McNeal",
    "M People",
    "Macy Gray",
    "Magic Affair",
    "Marc Anthony",
    "Marc Cohn",
    "Marco Borsato",
    "Marcy Playground",
    "Mariah Carey",
    "Marilyn Manson",
    "Mark 'Oh",
    "Mark Collie",
    "Mark Morrison",
    "Marky Mark",
    "Marusha",
    "Mary J. Blige",
    "Masini",
    "Master P",
    "Masterboy",
    "Maxx",
    "Meredith Brooks",
    "Missy Elliott",
    "Mo-Do",
    "Moby",
    "Moist",
    "Monica",
    "Mr. President",
    "N-Trance",
    "Nada Surf",
    "Nakatomi",
    "Nas",
    "Natalie Imbruglia",
    "Nek",
    "Nelly",
    "New Radicals",
    "Nightcrawlers",
    "Nine Days",
    "Nirvana",
    "No Doubt",
    "Oasis",
    "Ocean Colour Scene",
    "Orbital",
    "Orgy",
    "Our Lady Peace",
    "Paola Turci",
    "Papa Roach",
    "Party Animals",
    "Pater Moeskroen",
    "Pearl Jam",
    "Perplexer",
    "Peter de Koning",
    "Pharao",
    "Primus",
    "Puff Daddy",
    "R. Kelly",
    "RMB",
    "Radiohead",
    "Rage Against the Machine",
    "Rammstein",
    "Rastape",
    "Real McCoy",
    "Red 5",
    "Rednex",
    "Reel 2 Real",
    "Reel Big Fish",
    "Rene Klijn",
    "Ricky Martin",
    "Rionegro",
    "Rob Zombie",
    "Robert Leroy",
    "Robert Miles",
    "Robin S",
    "Ronny Jordan",
    "Roots Syndicate",
    "Rozalla",
    "Ruth Jacott",
    "SASH!",
    "Saez",
    "Sailor Moon",
    "Sandro & Gustavo",
    "Save Ferris",
    "Scatman John",
    "Scooter",
    "Seal",
    "Semisonic",
    "Shaggy",
    "Shania Twain",
    "Shawn Mullins",
    "Sheryl Crow",
    "Shola Ama",
    "Silverchair",
    "Sisqo",
    "Sister Hazel",
    "Sixpence None the Richer",
    "Skee-Lo",
    "Smash Mouth",
    "Snap",
    "Snoop Dogg",
    "Spin Doctors",
    "Squirrel Nut Zippers",
    "Star Wash",
    "Stiltskin",
    "Stone Temple Pilots",
    "Sublime",
    "Sugar Ray",
    "TLC",
    "Tag Team",
    "Technohead",
    "The Brian Setzer Orchestra",
    "The Cardigans",
    "The Cranberries",
    "The Folk Implosion",
    "The Mavericks",
    "The Notorious B.I.G.",
    "The Offspring",
    "The Outhere Brothers",
    "The Presidents of the United States of America",
    "The Prodigy",
    "The Smashing Pumpkins",
    "The Tony Rich Project",
    "The Verve",
    "The Verve Pipe",
    "The Wallflowers",
    "Third Eye Blind",
    "Tim Immers",
    "Toni Braxton",
    "Tool",
    "Tori Amos",
    "Tracy Byrd",
    "Travis Tritt",
    "Trisha Yearwood",
    "Trovato",
    "Tupac",
    "Type O Negative",
    "U96",
    "Ugly Kid Joe",
    "Urban Cookie Collective",
    "Us3",
    "Usher",
    "Vanilla Ice",
    "Vengaboys",
    "Vertical Horizon",
    "Veruca Salt",
    "Warren G",
    "Weezer",
    "Wendy Moten",
    "Whigfield",
    "Xscape",
    "Zebrahead",
    "Zeze di Camargo",
    "Zhane",
    "Zhi-Vago",
    "blink-182",
  ],
};

const eras = new Map<string, RockPopEra>();
(Object.entries(eraArtists) as [RockPopEra, string[]][]).forEach(
  ([era, artists]) =>
    artists.forEach((name) => eras.set(canonicalArtistName(name).trim(), era)),
);

export const artistEra = (name: string): RockPopEra =>
  eras.get(canonicalArtistName(name).trim()) || "unassigned";
