// Curated browsing shelves, not authoritative genre or identity metadata.

// Unknown or ambiguous folders deliberately fall back to the final shelf.

export const LAKH_SHELF_GROUPS = [
  {
    id: "pop",
    label: "Pop & rock",
  },
  {
    id: "heavy",
    label: "Metal & alternative",
  },
  {
    id: "soul",
    label: "Soul, funk & R&B",
  },
  {
    id: "electronic",
    label: "Electronic & dance",
  },
  {
    id: "jazz",
    label: "Jazz & blues",
  },
  {
    id: "classical",
    label: "Classical",
  },
  {
    id: "folk",
    label: "Country & folk",
  },
  {
    id: "stage",
    label: "Stage & screen",
  },
  {
    id: "international",
    label: "International",
  },
  {
    id: "other",
    label: "Other",
  },
] as const;

export const LAKH_SHELVES = [
  {
    id: "rock",
    label: "Rock & pop",
    group: "pop",
  },
  {
    id: "metal",
    label: "Hard rock & metal",
    group: "heavy",
  },
  {
    id: "alternative",
    label: "Alternative, punk & indie",
    group: "heavy",
  },
  {
    id: "progressive",
    label: "Progressive & art rock",
    group: "pop",
  },
  {
    id: "rnb",
    label: "R&B",
    group: "soul",
  },
  {
    id: "soul",
    label: "Soul",
    group: "soul",
  },
  {
    id: "funk",
    label: "Funk",
    group: "soul",
  },
  {
    id: "hiphop",
    label: "Hip-hop & rap",
    group: "other",
  },
  {
    id: "electronic",
    label: "Electronic & dance",
    group: "electronic",
  },
  {
    id: "jazz",
    label: "Jazz",
    group: "jazz",
  },
  {
    id: "blues",
    label: "Blues",
    group: "jazz",
  },
  {
    id: "country",
    label: "Country & Americana",
    group: "folk",
  },
  {
    id: "folk",
    label: "Folk, chanson & singer-songwriter",
    group: "folk",
  },
  {
    id: "classical",
    label: "Classical & historical composers",
    group: "classical",
  },
  {
    id: "instrumental",
    label: "Easy listening & instrumental",
    group: "other",
  },
  {
    id: "latin",
    label: "Latin, Caribbean & world",
    group: "international",
  },
  {
    id: "italian",
    label: "Italian music",
    group: "international",
  },
  {
    id: "french",
    label: "French-language music",
    group: "international",
  },
  {
    id: "european",
    label: "German, Dutch & Central European",
    group: "international",
  },
  {
    id: "stage",
    label: "Stage, screen & themes",
    group: "stage",
  },
  {
    id: "novelty",
    label: "Children, comedy & novelty",
    group: "other",
  },
  {
    id: "other",
    label: "Unclassified or ambiguous",
    group: "other",
  },
] as const;

export type ShelfId = (typeof LAKH_SHELVES)[number]["id"];

const normalizeName = (name: string) =>
  name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");

const aliases: Record<string, string> = {
  eltonjohn: "Elton John",
  johnelton: "Elton John",
  michaeljackson: "Michael Jackson",
  jacksonmichael: "Michael Jackson",
  philcollins: "Phil Collins",
  collinsphil: "Phil Collins",
  zappa: "Zappa",
  zappafrank: "Zappa",
  battisti: "Lucio Battisti",
  battistilucio: "Lucio Battisti",
  adrianocelentano: "Adriano Celentano",
  celentano: "Adriano Celentano",
  dallalucio: "Dalla Lucio",
  dalla: "Dalla Lucio",
  laurapausini: "Laura Pausini",
  pausinilaura: "Laura Pausini",
  umbertotozzi: "Umberto Tozzi",
  tozziumberto: "Umberto Tozzi",
  tozzi: "Umberto Tozzi",
  erosramazzotti: "Eros Ramazzotti",
  ramazzotti: "Eros Ramazzotti",
  vascorossi: "Vasco Rossi",
  rossivasco: "Vasco Rossi",
  vasco: "Vasco Rossi",
  antonellovenditti: "Antonello Venditti",
  vendittiantonello: "Antonello Venditti",
  luciobattisti: "Lucio Battisti",
  claudiobaglioni: "Claudio Baglioni",
  baglioniclaudio: "Claudio Baglioni",
  davidbowie: "David Bowie",
  bowiedavid: "David Bowie",
  chuckberry: "Chuck Berry",
  berrychuck: "Chuck Berry",
  louisarmstrong: "Louis Armstrong",
  armstronglouis: "Louis Armstrong",
  bobbydarin: "Bobby Darin",
  darinbobby: "Bobby Darin",
  jamesbrown: "James Brown",
  brownjames: "James Brown",
  thebrownjames: "James Brown",
  garthbrooks: "Garth Brooks",
  brooksgarth: "Garth Brooks",
  johnleehooker: "John Lee Hooker",
  hookerjohnlee: "John Lee Hooker",
  johnnycash: "Johnny Cash",
  cashjohnny: "Johnny Cash",
  johnlennon: "John Lennon",
  lennonjohn: "John Lennon",
  paulmccartney: "Paul McCartney",
  mccartney: "Paul McCartney",
  rodstewart: "Rod Stewart",
  stewartrod: "Rod Stewart",
  steviewonder: "Stevie Wonder",
  wonderstevie: "Stevie Wonder",
  tinaturner: "Tina Turner",
  turnertina: "Tina Turner",
  dionnewarwick: "Dionne Warwick",
  warwickdionne: "Dionne Warwick",
  gloriaestefan: "Gloria Estefan",
  estefangloria: "Gloria Estefan",
  sherylcrow: "Sheryl Crow",
  crowsheryl: "Sheryl Crow",
  toriamos: "Tori Amos",
  amostori: "Tori Amos",
  billyidol: "Billy Idol",
  idolbilly: "Billy Idol",
  lionelrichie: "Lionel Richie",
  richielionel: "Lionel Richie",
  barrywhite: "Barry White",
  whitebarry: "Barry White",
  billyocean: "Billy Ocean",
  oceanbilly: "Billy Ocean",
  gracejones: "Grace Jones",
  jonesgrace: "Grace Jones",
  dianaking: "Diana King",
  kingdiana: "Diana King",
  beneking: "Ben E. King",
  kingbene: "Ben E. King",
  billypreston: "Billy Preston",
  prestonbilly: "Billy Preston",
  otisredding: "Otis Redding",
  reddingotis: "Otis Redding",
  paulsimon: "Paul Simon",
  simonpaul: "Paul Simon",
  jamestaylor: "James Taylor",
  taylorjames: "James Taylor",
  kimcarnes: "Kim Carnes",
  carneskim: "Kim Carnes",
  ericcarmen: "Eric Carmen",
  carmeneric: "Eric Carmen",
  richardmarx: "Richard Marx",
  marxrichard: "Richard Marx",
  neilsedaka: "Neil Sedaka",
  sedakaneil: "Neil Sedaka",
  cliffrichard: "Cliff Richard",
  richardcliff: "Cliff Richard",
  paulanka: "Paul Anka",
  ankapaul: "Paul Anka",
  conniefrancis: "Connie Francis",
  francisconnie: "Connie Francis",
  bobmarley: "Bob Marley",
  marleybob: "Bob Marley",
  buddyholly: "Buddy Holly",
  hollybuddy: "Buddy Holly",
  fatsdomino: "Fats Domino",
  dominofats: "Fats Domino",
  billhaleyhiscomets: "Bill Haley & His Comets",
  billhaley: "Bill Haley & His Comets",
  hueylewisthenews: "Huey Lewis & The News",
  hueylewis: "Huey Lewis & The News",
  brucehornsbytherange: "Bruce Hornsby & The Range",
  brucehornsby: "Bruce Hornsby & The Range",
  thefoundations: "The Foundations",
  foundations: "The Foundations",
  foundationsthe: "The Foundations",
  themamasthepapas: "The Mamas & The Papas",
  themamasandpapas: "The Mamas & The Papas",
  mamaspapas: "The Mamas & The Papas",
  thedrifters: "The Drifters",
  drifters: "The Drifters",
  thesearchers: "The Searchers",
  searchers: "The Searchers",
  themccoys: "The McCoys",
  mccoys: "The McCoys",
  theromantics: "The Romantics",
  romantics: "The Romantics",
  theventures: "The Ventures",
  ventures: "The Ventures",
  thefixx: "The Fixx",
  fixx: "The Fixx",
  thepresidentsoftheunitedstatesofamerica:
    "The Presidents of the United States of America",
  presidentsoftheunitedstates: "The Presidents of the United States of America",
  thelmahouston: "Thelma Houston",
  houstonthelma: "Thelma Houston",
  deniecewilliams: "Deniece Williams",
  williamsdeniece: "Deniece Williams",
  jackiewilson: "Jackie Wilson",
  wilsonjackie: "Jackie Wilson",
  lisastansfield: "Lisa Stansfield",
  stansfieldlisa: "Lisa Stansfield",
  rkelly: "R. Kelly",
  kellyr: "R. Kelly",
  rickymartin: "Ricky Martin",
  martinricky: "Ricky Martin",
  genevincent: "Gene Vincent",
  vincentgene: "Gene Vincent",
  richardclayderman: "Richard Clayderman",
  claydermanrichard: "Richard Clayderman",
  georgesbrassens: "Georges Brassens",
  brassensgeorges: "Georges Brassens",
  franciscabrel: "Francis Cabrel",
  cabrelfrancis: "Francis Cabrel",
  dukeellington: "Duke Ellington",
  ellington: "Duke Ellington",
  leonardbernstein: "Leonard Bernstein",
  bernsteinleonard: "Leonard Bernstein",
  coleporter: "Cole Porter",
  portercole: "Cole Porter",
  herbiemann: "Herbie Mann",
  mannherbie: "Herbie Mann",
  mikeoldfield: "Mike Oldfield",
  oldfieldmike: "Mike Oldfield",
  scatmanjohn: "Scatman John",
  scatman: "Scatman John",
  salvatoreadamo: "Salvatore Adamo",
  adamo: "Salvatore Adamo",
  yazoo: "Yazoo",
  yazooyaz: "Yazoo",
  orchestralmanoeuvresinthedark: "Orchestral Manoeuvres in the Dark",
  omd: "Orchestral Manoeuvres in the Dark",
  samtheshamthepharaohs: "Sam the Sham & The Pharaohs",
  samthesham: "Sam the Sham & The Pharaohs",
  elvispresley: "Elvis Presley",
  elvis: "Elvis Presley",
  georgemichael: "George Michael",
  michaelgeorge: "George Michael",
  marvingaye: "Marvin Gaye",
  gayemarvin: "Marvin Gaye",
  donnasummer: "Donna Summer",
  summerdonna: "Donna Summer",
  paulyoung: "Paul Young",
  youngpaul: "Paul Young",
  mungojerry: "Mungo Jerry",
  jerrymungo: "Mungo Jerry",
  lloydprice: "Lloyd Price",
  pricelloyd: "Lloyd Price",
  johnmiles: "John Miles",
  milesjohn: "John Miles",
  davidfoster: "David Foster",
  fosterdavid: "David Foster",
};

export const canonicalArtistName = (name: string) =>
  aliases[normalizeName(name)] || name;

const primaryShelves: Record<string, ShelfId> = {
  // Re-reviewed against the folder repertoire; classify without merging identities.
  "2Boys": "electronic",
  "Alberti": "european",
  "Alive": "rock",
  "Alpert": "jazz",
  "Amanda McBroom": "folk",
  "Ann Farina": "instrumental",
  "Antonio Carlos": "jazz",
  "Armani": "italian",
  "BND": "electronic",
  "Band": "rock",
  "Bauer": "european",
  "Baxter": "instrumental",
  "Bell": "soul",
  "Bennett": "rock",
  "Big Mr.": "metal",
  "Bolero": "electronic",
  "Bommbastic": "electronic",
  "Bone": "hiphop",
  "Bruno": "latin",
  "Bumble B": "rock",
  "Calvert": "instrumental",
  "Carey": "rnb",
  "Carmen": "rock",
  "Carpenter": "country",
  "Charlie Makes The Cook": "rock",
  "Chocolate": "electronic",
  "Classics": "european",
  "Cocker": "rock",
  "Cosmix": "novelty",
  "Creation": "rock",
  "Daniel": "european",
  "Davis John": "stage",
  "Dee": "rock",
  "Derby": "european",
  "Double Vision": "electronic",
  "Droids": "electronic",
  "Duke": "electronic",
  "Duval": "instrumental",
  "Ekseption": "progressive",
  "Elliot": "rock",
  "Faith": "instrumental",
  "Flair": "european",
  "Flamingos": "rock",
  "Fluid": "alternative",
  "Fontana": "italian",
  "Forrest": "funk",
  "Freak Power": "funk",
  "Freddy Martin": "jazz",
  "Garland": "stage",
  "Glover": "progressive",
  "Good Shape": "rock",
  "Gordon": "european",
  "Grant & Forsyth": "country",
  "Greger": "jazz",
  "Haak": "european",
  "Haley": "rock",
  "Herman": "jazz",
  "Heywood": "jazz",
  "Hughie Cannon": "jazz",
  "Izabella": "rock",
  "James Colin": "blues",
  "Jets": "rnb",
  "Jett": "rock",
  "John Robert": "rock",
  "Johnson": "jazz",
  "K2": "electronic",
  "K7": "hiphop",
  "KWS": "electronic",
  "Kalua Beach Boys": "latin",
  "Keith": "rock",
  "Knight": "soul",
  "Kramer": "rock",
  "LANZA": "classical",
  "Last": "instrumental",
  "Lavinia Jones": "electronic",
  "Lewis": "rock",
  "Lucifer": "rock",
  "Mamas": "rock",
  "Masquerade": "rock",
  "Mathis": "rock",
  "McDonald": "soul",
  "Meco": "electronic",
  "New Age": "instrumental",
  "Ocean": "rock",
  "Oliver": "rock",
  "Petty": "rock",
  "Phyllis Nelson": "soul",
  "Playmates": "novelty",
  "Prince Ital Joe": "electronic",
  "Propaganda": "rock",
  "Puckett": "rock",
  "Quartz": "electronic",
  "Quatro": "rock",
  "Rah Band": "funk",
  "Rea": "rock",
  "Red": "french",
  "Reeves": "soul",
  "Revere": "rock",
  "Rick": "latin",
  "Robert Hampton": "jazz",
  "Roberts": "italian",
  "Robin Cock": "rock",
  "Robinson": "soul",
  "Ross": "soul",
  "SAM": "rock",
  "Santo": "italian",
  "Sergio": "latin",
  "Shalom": "european",
  "Sharpe": "rock",
  "Sinatra": "rock",
  "Skylark": "rock",
  "Sly": "funk",
  "Solo": "italian",
  "Soulful Dynamics": "latin",
  "Stone & Stone": "rock",
  "Streisand": "rock",
  "Supermax": "electronic",
  "Taja Sevelle": "rnb",
  "Talk of the Town": "novelty",
  "Tatyana Ali": "rnb",
  "Tears n' Joy": "electronic",
  "Telly Savalas": "rock",
  "The Chaplin Band": "funk",
  "The Charmaines": "soul",
  "The Commitments": "soul",
  "The Dinky Toys": "rock",
  "Tokens": "rock",
  "Toys": "soul",
  "Trinere": "electronic",
  "Trio Rio": "rock",
  "Vaughn": "instrumental",
  "Vega": "folk",
  "Vera": "soul",
  "Vicki Brown": "rock",
  "Warren": "jazz",
  "Watanabe": "jazz",
  "Werner": "european",

  '"Weird Al" Yankovic': "novelty",
  ".38 Special": "metal",
  "10,000 Maniacs": "alternative",
  "101 Strings": "instrumental",
  "10cc": "rock",
  "1910 Fruitgum Company": "rock",
  "2 Brothers on the 4th Floor": "electronic",
  "2 Unlimited": "electronic",
  "20 Fingers": "electronic",
  "311": "alternative",
  "3T": "rnb",
  "4 Non Blondes": "alternative",
  "702": "rnb",
  "808 State": "electronic",
  "883": "italian",
  "911": "rock",
  "98 Degrees": "rock",
  "A Taste of Honey": "funk",
  "A*Teens": "rock",
  "a-ha": "rock",
  Aaliyah: "rnb",
  "Aaron Neville": "soul",
  ABBA: "rock",
  ABC: "rock",
  "AC DC": "metal",
  Ace: "rock",
  "Ace Frehley": "metal",
  "Ace of Base": "rock",
  "Acoustic Alchemy": "instrumental",
  "Adam & Eve": "european",
  "Salvatore Adamo": "french",
  Adamski: "electronic",
  Adiemus: "instrumental",
  "Adriano Celentano": "italian",
  "Adventures of Stevie V.": "electronic",
  Aerosmith: "metal",
  "Air Supply": "rock",
  "AL Bano": "italian",
  "Al Green": "soul",
  "Al Hirt": "jazz",
  "Al Jarreau": "jazz",
  "Al Jolson": "stage",
  "Al Martino": "rock",
  "Al Stewart": "folk",
  "Al Wilson": "soul",
  Alabama: "country",
  "Alain Barriere": "french",
  "Alain Bashung": "french",
  "Alain Chamfort": "french",
  "Alain Souchon": "french",
  "Alan Jackson": "country",
  "Alan Parsons": "progressive",
  "Alanis Morissette": "alternative",
  "Alannah Myles": "rock",
  "Albert Hammond": "rock",
  "Albert West": "european",
  "Alberto Fortis": "italian",
  "Alexander O'Neal": "rnb",
  "Alexander Peter": "european",
  Alexandra: "european",
  Alexia: "electronic",
  Alice: "italian",
  "Alice Cooper": "metal",
  "Alice in Chains": "alternative",
  "Alien Ant Farm": "alternative",
  "Alison Moyet": "rock",
  Alizee: "french",
  "All Saints": "rock",
  "All-4-One": "rnb",
  "Allan Sherman": "novelty",
  "Allan Theo": "french",
  "Allen Toussaint": "soul",
  Alliage: "french",
  Allure: "rnb",
  "Alma Cogan": "rock",
  Alpenrebellen: "european",
  "Alpentrio Tirol": "european",
  Alphaville: "rock",
  "Alunni del Sole": "italian",
  "Alvin Stardust": "rock",
  Amber: "electronic",
  Ambra: "italian",
  "Amedeo Minghi": "italian",
  America: "rock",
  "Amie Comeaux": "country",
  "Amii Stewart": "soul",
  Amina: "french",
  "Tori Amos": "alternative",
  "Amy Grant": "rock",
  "Ana Belen": "latin",
  "Ana Caram": "latin",
  Anastacia: "rock",
  "Andre & Adriano": "latin",
  "Andre Brasseur": "instrumental",
  "Andre Hazes": "european",
  "Andre Moss": "instrumental",
  "Andre van Duin": "european",
  "Andrea Bocelli": "italian",
  "Andrew Gold": "rock",
  "Andrew Lloyd Webber": "stage",
  "Andy Kim": "rock",
  "Andy Williams": "rock",
  "Angelo Branduardi": "italian",
  Anggun: "latin",
  Animotion: "rock",
  "Anita Baker": "rnb",
  "Anita Meyer": "european",
  "Anita Ward": "soul",
  "Paul Anka": "rock",
  "Ann Peebles": "soul",
  "Anna Oxa": "italian",
  "Anne Murray": "country",
  "Annie Cordy": "french",
  "Annie Lennox": "rock",
  "Another Level": "rock",
  "Anthony Richard": "french",
  Antoine: "french",
  "Antonello Venditti": "italian",
  "Aphrodite's Child": "progressive",
  "Apollo 100": "instrumental",
  Aqua: "electronic",
  Arabesque: "rock",
  "Aretha Franklin": "soul",
  "Louis Armstrong": "jazz",
  "Army of Lovers": "electronic",
  "Arrested Development": "hiphop",
  "Art of Noise": "electronic",
  "Articolo 31": "italian",
  Asia: "progressive",
  Assekruus: "european",
  Assia: "french",
  "Astrud Gilberto": "jazz",
  Aswad: "latin",
  "Atkins Chet": "country",
  "Atlanta Rhythm Section": "rock",
  "Atlantic Ocean": "electronic",
  "Atlantic Starr": "rnb",
  "Atomic Kitten": "rock",
  "Au bonheur des dames": "french",
  "Average White Band": "funk",
  "Axelle Red": "french",
  "B*Witched": "rock",
  "B.B. King": "blues",
  "B.G. The Prince of Rap": "electronic",
  "B.W. Stevenson": "folk",
  "Baby D": "electronic",
  Babyface: "rnb",
  "Babylon Zoo": "rock",
  Baccara: "rock",
  "Bach Johann Sebastian": "classical",
  "Bachman-Turner Overdrive": "rock",
  "Backstreet Boys": "rock",
  "Bad Boys Blue": "rock",
  "Bad Company": "rock",
  "Bad English": "rock",
  "Bad Manners": "rock",
  "BAGINSKY,GABY": "european",
  "Claudio Baglioni": "italian",
  Baltimora: "italian",
  Bananarama: "rock",
  "Band Aid": "rock",
  "Banda Blanca": "latin",
  BAP: "european",
  "Barber Samuel": "classical",
  "Barbra Streisand": "rock",
  "Barclay James Harvest": "progressive",
  "Barenaked Ladies": "alternative",
  "Barlow Gary": "rock",
  "Barry & Eileen": "rock",
  "Barry John": "stage",
  "Barry Manilow": "rock",
  "Barry Mann": "rock",
  "Barry White": "soul",
  "Bart Herman": "european",
  Basia: "rock",
  Basie: "jazz",
  Battiato: "italian",
  "Lucio Battisti": "italian",
  "Bay City Rollers": "rock",
  BBE: "electronic",
  BBMak: "rock",
  "Beastie Boys": "hiphop",
  Beck: "alternative",
  "Bee Gees": "rock",
  "Bela Bartok": "classical",
  "Belafonte Harry": "latin",
  "Belinda Carlisle": "rock",
  "Bellamy Brothers": "country",
  Beloved: "electronic",
  "Ben Cramer": "european",
  "Ben E. King": "soul",
  "Ben Folds Five": "alternative",
  "Benjamin Arthur": "classical",
  "Beres Hammond": "latin",
  "Berger Michel": "french",
  Berlin: "rock",
  "Berlin Irving": "stage",
  "Bernd Cluver": "european",
  "Bernhard Brink": "european",
  "Leonard Bernstein": "stage",
  "Chuck Berry": "rock",
  "Bert Heerink": "european",
  Berte: "italian",
  "Bertie Higgins": "rock",
  "Bette Midler": "rock",
  "Biagio Antonacci": "italian",
  "Big Bad Voodoo Daddy": "jazz",
  "Big Mountain": "latin",
  Bilk: "jazz",
  "Bill Haley & His Comets": "rock",
  "Bill Medley": "rock",
  "Bill Withers": "soul",
  "Billie Jo Spears": "country",
  "Billie Myers": "rock",
  'Billy "Crash" Craddock': "country",
  "Billy Fury": "rock",
  "Billy Idol": "rock",
  "Billy Joel": "rock",
  "Billy Mayerl": "jazz",
  "Billy Ocean": "rnb",
  "Billy Paul": "soul",
  "Billy Preston": "funk",
  "Billy Ray Cyrus": "country",
  "Billy Swan": "rock",
  Bino: "italian",
  Birkin: "french",
  "Bizet Georges": "classical",
  Bjork: "alternative",
  Black: "rock",
  "Black Box": "electronic",
  "Black Fooss": "european",
  "Black Rob": "hiphop",
  "Black Sabbath": "metal",
  Blackstreet: "rnb",
  Blaque: "rnb",
  Blattschuss: "european",
  "Blind Guardian": "metal",
  "Blind Melon": "alternative",
  "blink-182": "alternative",
  Blondie: "rock",
  "Blood, Sweat & Tears": "rock",
  "Bloodhound Gang": "alternative",
  "Blue Oyster Cult": "metal",
  "Blue System": "rock",
  "Blues Image": "rock",
  "Blues Traveler": "blues",
  Blumchen: "electronic",
  Blur: "alternative",
  "Bob Carlisle": "rock",
  "Bob Dylan": "folk",
  "Bob James": "jazz",
  "Bob Marley": "latin",
  "Bob Seger": "rock",
  "Bob Welch": "rock",
  'Bobby "Boris" Pickett': "novelty",
  "Bobby Bare": "country",
  "Bobby Bloom": "rock",
  "Bobby Brown": "rnb",
  "Bobby Darin": "rock",
  "Bobby Goldsboro": "rock",
  "Bobby McFerrin": "jazz",
  "Bobby Prins": "european",
  "Bobby Rydell": "rock",
  "Bobby Vee": "rock",
  "Bobby Vinton": "rock",
  Bombalurina: "novelty",
  "Bomfunk MC's": "electronic",
  "Bon Jovi": "metal",
  "Boney James": "instrumental",
  "Boney M.": "latin",
  "Bonnie Raitt": "blues",
  "Bonnie Tyler": "rock",
  "Bonzo Dog Doo Dah Band": "novelty",
  "Booker T. & The MG's": "funk",
  "Booming Support": "electronic",
  "Boothe, Ken": "latin",
  "Borg Andy": "european",
  "Boris Gardiner": "latin",
  Borodin: "classical",
  Boston: "rock",
  "David Bowie": "rock",
  "Boy George": "rock",
  "Boys Town Gang": "rock",
  "Boyz II Men": "rnb",
  Boyzone: "rock",
  "Boz Scaggs": "soul",
  Brandy: "rnb",
  "Georges Brassens": "french",
  Bread: "rock",
  Breathe: "rock",
  "BRECK,FREDDY": "european",
  "Brenton Wood": "soul",
  "Brewer And Shipley": "folk",
  "Brian Hyland": "rock",
  "Brian May": "rock",
  "Brian McKnight": "rnb",
  "Brian Wilson": "rock",
  "Britney Spears": "rock",
  Broadway: "stage",
  "Bronski Beat": "electronic",
  "Brooks & Dunn": "country",
  "Garth Brooks": "country",
  Bros: "rock",
  "Brotherhood of Man": "rock",
  "Brown Clarence Gatemouth": "blues",
  "James Brown": "funk",
  "Brownsville Station": "rock",
  "Bruce Channel": "rock",
  "Bruce Hornsby & The Range": "rock",
  "Bruce Springsteen": "rock",
  "Brunner & Brunner": "european",
  "Bryan Adams": "rock",
  Bryson: "rnb",
  "Buck Owens": "country",
  "Buddy Holly": "rock",
  "Buena Vista Social Club": "latin",
  "Buffalo Springfield": "folk",
  Buggles: "rock",
  "Burt Bacharach": "stage",
  "Burton Lane": "stage",
  Bush: "alternative",
  "Busta Rhymes": "hiphop",
  "BUTLER, JONATHAN": "jazz",
  "Buzz Clifford": "rock",
  "Byrd Charlie": "jazz",
  "Byron Berline": "country",
  BZN: "european",
  "C'est Tout": "european",
  "C+C Music Factory": "electronic",
  "C.J. Lewis": "latin",
  "Francis Cabrel": "french",
  Cake: "alternative",
  Calimeros: "european",
  Calloway: "funk",
  Camaleonti: "italian",
  Camel: "progressive",
  Cameo: "funk",
  "Candi Staton": "soul",
  "Canned Heat": "blues",
  "Cannibal & The Headhunters": "rock",
  Capella: "electronic",
  "Captain Hollywood Project": "electronic",
  "Captain Jack": "electronic",
  Carboni: "italian",
  "Carl Douglas": "funk",
  "Carl Perkins": "rock",
  "Carl Teike": "classical",
  "Carly Simon": "folk",
  "Eric Carmen": "rock",
  "Carmina Burana": "classical",
  "Kim Carnes": "rock",
  "Carole King": "folk",
  Carpenters: "rock",
  Carra: "italian",
  Cascades: "rock",
  "Johnny Cash": "country",
  CASIOPEA: "jazz",
  "Caterina Caselli": "italian",
  "Cathy Dennis": "rock",
  Cats: "stage",
  "Caught in the Act": "rock",
  "CB Milton": "electronic",
  "Celine Dion": "rock",
  Centory: "electronic",
  "Cesar Franck": "classical",
  "Chaka Demus": "latin",
  "Chaka Khan": "funk",
  Champaign: "rnb",
  Champs: "rock",
  "Charlebois Robert": "french",
  "Charles & Eddie": "soul",
  "Charles Aznavour": "french",
  "Charles-Valentin Alkan": "classical",
  "Charlie Rich": "country",
  Chastain: "metal",
  "Cheap Trick": "rock",
  "Checker Chubby": "rock",
  Cher: "rock",
  "Cherry Poppin' Daddies": "jazz",
  "Cheryl Ladd": "rock",
  "Cheryl Lynn": "funk",
  "Chesney Hawkes": "rock",
  Chic: "funk",
  Chicago: "rock",
  "Chick Corea": "jazz",
  "Chip Davis": "instrumental",
  "Chip Taylor": "folk",
  "Chopin Frederic": "classical",
  "Chris Andrews": "rock",
  "Chris Barber's Jazz Band": "jazz",
  "Chris de Burgh": "rock",
  "Chris Isaak": "rock",
  "Chris Montez": "rock",
  "Chris Norman": "rock",
  "Chris Rea": "rock",
  "Chris Roberts": "european",
  Christie: "rock",
  "Christie Lou": "rock",
  "CHRISTIE,TONY": "rock",
  "Christina Aguilera": "rock",
  "Christoph Willibald Gluck": "classical",
  "Christopher Cross": "rock",
  "Chuck Mangione": "jazz",
  Chumbawamba: "alternative",
  "Chyp-notic": "rock",
  "Cilla Black": "rock",
  "Cindy & Bert": "european",
  'Clarence "Frogman" Henry': "rock",
  "Classics IV": "rock",
  "Claude Bolling": "jazz",
  "Claude Debussy": "classical",
  "Claude Francois": "french",
  "Claude-Michel Schonberg": "stage",
  "Claudia Schmidt": "folk",
  "Richard Clayderman": "instrumental",
  Clementi: "classical",
  "Clerc Julien": "french",
  "Cliff Richard": "rock",
  Climax: "rock",
  Clouseau: "european",
  Clout: "rock",
  "Club Nouveau": "rock",
  Coasters: "rock",
  Cocciante: "italian",
  "Cock Robin": "rock",
  "Cole Porter": "stage",
  "Collective Soul": "alternative",
  "Phil Collins": "rock",
  "Color Me Badd": "rnb",
  "Commander Cody": "country",
  Commodores: "funk",
  Communards: "rock",
  "Confederate Railroad": "country",
  "Connie Francis": "rock",
  "Conway Twitty": "country",
  Coolio: "hiphop",
  "CORDALIS,COSTA": "european",
  Corduroy: "jazz",
  "Corey Hart": "rock",
  "Cornelius Brothers": "soul",
  Corona: "electronic",
  "Corry Konings": "european",
  "Counting Crows": "alternative",
  "Crash Test Dummies": "alternative",
  Cream: "rock",
  Creed: "alternative",
  "Creedence Clearwater Revival": "rock",
  Crests: "rock",
  Crickets: "rock",
  "Croce Jim": "folk",
  "Crosby Bing": "rock",
  "Crosby, Stills, Nash & Young": "folk",
  "Sheryl Crow": "alternative",
  "Crowded House": "rock",
  Crusaders: "funk",
  "Crystal Gayle": "country",
  "Crystal Waters": "electronic",
  Crystals: "rock",
  "Culture Beat": "electronic",
  "Culture Club": "rock",
  "Curtis Lee": "rock",
  "Curtis Mayfield": "soul",
  "Curtis Stigers": "rock",
  "Cut 'n' Move": "electronic",
  "Cutting Crew": "rock",
  "Cyndi Lauper": "rock",
  "D:Ream": "electronic",
  "Daft Punk": "electronic",
  "Dalla Lucio": "italian",
  Dallara: "italian",
  "Dan Fogelberg": "folk",
  "Dan Hartman": "rock",
  "Dan Hill": "rock",
  "Dance 2 Trance": "electronic",
  "Daniel Boone": "rock",
  Daniele: "italian",
  "Danilo Amerio": "italian",
  "Dannii Minogue": "rock",
  "Danny & The Juniors": "rock",
  "Danyel Gerard": "french",
  Darts: "rock",
  Darude: "electronic",
  'Dave "Baby" Cortez': "rock",
  "Dave Brubeck": "jazz",
  "Dave Grusin": "jazz",
  "Dave Mason": "rock",
  "Dave Matthews Band": "alternative",
  "David A. Stewart": "rock",
  "David Byrne": "rock",
  "David Dundas": "rock",
  "David Essex": "rock",
  "David Gates": "rock",
  "David Lee Roth": "metal",
  "Davis Miles": "jazz",
  DaWN: "rock",
  "dc Talk": "rock",
  "De Deurzakkers": "european",
  "De Dijk": "european",
  "De Electronica's": "european",
  "De Havenzangers": "european",
  "De Migra's": "european",
  "De Nachroave": "european",
  "Deacon Blue": "rock",
  "Dead Or Alive": "electronic",
  "Debbie Gibson": "rock",
  "Debby Boone": "rock",
  "Deep Blue Something": "alternative",
  "Deep Purple": "metal",
  "Def Leppard": "metal",
  Deftones: "metal",
  "Del Shannon": "rock",
  "Delfonics the": "soul",
  "Delibes Leo": "classical",
  "Demis Roussos": "rock",
  "Deniece Williams": "rnb",
  "Dennie Christian": "european",
  "Depeche Mode": "electronic",
  "Derek and the Dominos": "blues",
  "Des'ree": "soul",
  Desireless: "french",
  "Desmond Dekker": "latin",
  "Destiny's Child": "rnb",
  "Detroit Emeralds": "soul",
  Devo: "alternative",
  "Dexys Midnight Runners": "rock",
  "Diamond Jim": "rock",
  "Diana King": "latin",
  "Diana Ross": "soul",
  "Dick Hyman": "jazz",
  "Die Arzte": "alternative",
  "Die Doofen": "novelty",
  "Die Fantastischen Vier": "hiphop",
  "Dietrich Marlene": "european",
  "Digno Garcia": "latin",
  "Dik Dik": "italian",
  "Dina Carroll": "rnb",
  Dingetje: "european",
  Dion: "rock",
  "Dionne Warwick": "soul",
  "Dire Straits": "rock",
  "Dirotta su Cuba": "italian",
  Divinyls: "rock",
  "Dixie Chicks": "country",
  "Dizzy Man's Band": "rock",
  "DJ BoBo": "electronic",
  "DJ Jazzy Jeff": "hiphop",
  "DJ Paul Elstak": "electronic",
  "DJ Quicksilver": "electronic",
  DMX: "hiphop",
  "Dobie Gray": "soul",
  "Doe Maar": "european",
  "Dolls United": "novelty",
  "Fats Domino": "rock",
  "Don Backy": "italian",
  "Don Henley": "rock",
  "Don Johnson": "rock",
  "Don McLean": "folk",
  "Donna Hightower": "soul",
  "Donna Summer": "soul",
  "Donny Osmond": "rock",
  Donovan: "folk",
  "Doris Day": "rock",
  Dorsey: "jazz",
  Double: "rock",
  "Double You": "electronic",
  "Dr. Alban": "electronic",
  "Dr. Dre": "hiphop",
  "Dr. Hook": "rock",
  "Dr. John": "blues",
  "Drafi Deutscher": "european",
  "Dream Theater": "progressive",
  "The Drifters": "soul",
  Drukwerk: "european",
  Drupi: "italian",
  "Duke Ellington": "jazz",
  "Duke Robillard": "blues",
  "DULFER, CANDY": "jazz",
  Dune: "electronic",
  "Duran Duran": "rock",
  "Dusty Springfield": "soul",
  Dvorak: "classical",
  "E-Rotic": "electronic",
  "E-Type": "electronic",
  "Eagle-Eye Cherry": "rock",
  Eagles: "rock",
  "Earth, Wind & Fire": "funk",
  "East 17": "rock",
  "East Side Beat": "electronic",
  "Echo & The Bunnymen": "alternative",
  "Ed Townsend": "soul",
  "Eddie Cochran": "rock",
  "Eddie Floyd": "soul",
  "Eddie Holman": "soul",
  "Eddie Kendricks": "soul",
  "Eddie Money": "rock",
  "Eddy Arnold": "country",
  "Eddy Duane": "rock",
  "Eddy Grant": "latin",
  "Edgar Winter": "rock",
  "Edison Lighthouse": "rock",
  Edsels: "rock",
  "Edvard Grieg": "classical",
  "Edward Kleban": "stage",
  "Edwyn Collins": "rock",
  Eels: "alternative",
  "Eiffel 65": "electronic",
  "El DeBarge": "soul",
  "Electric Light Orchestra": "progressive",
  elgar: "classical",
  "Elkie Brooks": "rock",
  Elsa: "french",
  "Elton John": "rock",
  "Elvin Bishop": "blues",
  "Elvis Presley": "rock",
  "Elvis Costello": "alternative",
  "Emerson, Lake & Palmer": "progressive",
  EMF: "alternative",
  Eminem: "hiphop",
  "Emmanuel Chabrier": "classical",
  "En Vogue": "soul",
  "Energy 52": "electronic",
  "England Dan": "rock",
  Enigma: "electronic",
  "Enrique Iglesias": "latin",
  Enya: "instrumental",
  Equals: "rock",
  "Equipe 84": "italian",
  Erasure: "electronic",
  "Eric Clapton": "blues",
  "Eric Johnson": "rock",
  "Ernie K-Doe": "soul",
  "Ernst Neger": "european",
  "Eros Ramazzotti": "italian",
  "Erroll Garner": "jazz",
  "Gloria Estefan": "latin",
  "Esther Phillips": "soul",
  "Eubie Blake": "jazz",
  Europe: "metal",
  Eurythmics: "rock",
  "Evans Bill": "jazz",
  "Eve 6": "alternative",
  Everclear: "alternative",
  Everlast: "alternative",
  EXILE: "rock",
  Extreme: "metal",
  Fabi: "italian",
  "Fairground Attraction": "rock",
  "Fairport Convention": "folk",
  "Faith Evans": "soul",
  "Faith No More": "alternative",
  Faithless: "electronic",
  Falco: "european",
  Falla: "classical",
  Fancy: "rock",
  "Far Corporation": "rock",
  Fastball: "alternative",
  "Fat Boys": "hiphop",
  "Fat Larry's Band": "soul",
  "Fatboy Slim": "electronic",
  "FAURE Gabriel": "classical",
  "Fay Lovsky": "european",
  "Feargal Sharkey": "rock",
  "Fifth Dimension": "rock",
  Filter: "alternative",
  "Fine Young Cannibals": "rock",
  "Fiona Apple": "alternative",
  "Fiorella Mannoia": "italian",
  Fiorello: "italian",
  Firefall: "rock",
  Firehouse: "metal",
  "First Class": "rock",
  "Fitzgerald Ella": "jazz",
  "Five Man Electrical Band": "rock",
  "The Fixx": "rock",
  "Fleetwood Mac": "rock",
  "Floyd Cramer": "instrumental",
  Fluitsma: "european",
  Focus: "progressive",
  "Fontella Bass": "soul",
  "Foo Fighters": "alternative",
  "Fool's Garden": "rock",
  Foreigner: "rock",
  Fortunes: "rock",
  "Fossati Ivano": "italian",
  "David Foster": "instrumental",
  "The Foundations": "soul",
  "Four Tops": "soul",
  Fourplay: "jazz",
  "Francesco De Gregori": "italian",
  "Francois Couperin": "classical",
  "Frank & Mirella": "european",
  "Frank Galan": "european",
  "Frank Mills": "instrumental",
  "Frank Sinatra": "rock",
  "Frankie Avalon": "rock",
  "Frankie Goes to Hollywood": "electronic",
  "Frankie Valli": "rock",
  "Franky Boy": "european",
  "Frans Bauer": "european",
  Freakwater: "country",
  "Freda Payne": "soul",
  "Freddie & The Dreamers": "rock",
  "Freddie Jackson": "soul",
  "Freddie Mercury": "rock",
  "Freddy Cannon": "rock",
  Free: "rock",
  "Freek de Jonge": "european",
  "Friend & Lover": "rock",
  Fugees: "hiphop",
  "Fun Factory": "electronic",
  "G. G. Anderson": "european",
  "Gabber Piet": "novelty",
  Gala: "electronic",
  Gallery: "rock",
  Garbage: "alternative",
  "Gary Burton": "jazz",
  "Gary Glitter": "rock",
  "Gary Lewis": "rock",
  "Gary Moore": "blues",
  "Gary Puckett": "rock",
  "Gary Wright": "rock",
  "Gatto Panceri": "italian",
  "Marvin Gaye": "soul",
  "Gebroeders Grimm": "european",
  "Gene Chandler": "soul",
  "Gene Pitney": "rock",
  "Gene Vincent": "rock",
  Genesis: "progressive",
  "George Baker Selection": "rock",
  "George Benson": "jazz",
  "George Frideric Handel": "classical",
  "George Harrison": "rock",
  "George M. Cohan": "stage",
  "George McCrae": "soul",
  "George Michael": "rock",
  "George Thorogood": "blues",
  "Georgie Fame": "rock",
  "Gerard Cox": "european",
  "Gerard Joling": "european",
  "Geri Halliwell": "rock",
  "Gerry & The Pacemakers": "rock",
  "Gerry Mulligan Quartet": "jazz",
  "Gerry Rafferty": "rock",
  Gershwin: "stage",
  "Gianni Bella": "italian",
  "Gibson Brothers": "latin",
  "Gilbert & Sullivan": "stage",
  "Gilbert Becaud": "french",
  "Gilbert O'Sullivan": "rock",
  "Gillespie Dizzy": "jazz",
  "Gin Blossoms": "alternative",
  "Gina G": "electronic",
  "Gino Paoli": "italian",
  "Gino Vannelli": "rock",
  Giorgia: "italian",
  "Giorgio Moroder": "electronic",
  "Gipsy Kings": "latin",
  "Gladys Knight": "soul",
  "Glen Campbell": "country",
  "Glenn Frey": "rock",
  "Glenn Medeiros": "rock",
  "Glenn Miller": "jazz",
  "Gloria Gaynor": "soul",
  "Go West": "rock",
  Goblin: "progressive",
  Godsmack: "metal",
  Godspell: "stage",
  "Golden Earring": "rock",
  Gompie: "novelty",
  "Goo Goo Dolls": "alternative",
  "Gordon Lightfoot": "folk",
  "Gounod Charles": "classical",
  "Grace Jones": "soul",
  "Granados Enrique": "classical",
  "Grand Funk Railroad": "rock",
  Grandi: "italian",
  "Grateful Dead": "rock",
  Graziani: "italian",
  Grease: "stage",
  "Great White": "metal",
  "Green Day": "alternative",
  "Greenbaum Norman": "rock",
  "Greg Kihn": "rock",
  Gregori: "italian",
  "Groove Theory": "soul",
  "Gruppo Sportivo": "european",
  "Guesch Patti": "french",
  "Guess Who": "rock",
  "Guns N' Roses": "metal",
  "Guys 'n' Dolls": "rock",
  "Gwen McCrae": "soul",
  Haddaway: "electronic",
  "Haggard. Merle": "country",
  Hakkuhbar: "novelty",
  "Hall & Oates": "rock",
  "Hank Jones": "jazz",
  "Hank Williams": "country",
  "Hans Albers": "european",
  "Hans Dulfer": "jazz",
  Hanson: "rock",
  "Harold Faltermeyer": "stage",
  "Harold Melvin": "soul",
  Harpo: "rock",
  "Harry Chapin": "folk",
  "Harry Nilsson": "rock",
  "Harvey Danger": "alternative",
  "Hasselhoff David": "rock",
  "Hawkins Erskine": "jazz",
  Haydn: "classical",
  Heart: "rock",
  Heatwave: "funk",
  "Heidi Bruhl": "european",
  "Helen Reddy": "rock",
  "Henry Arland": "instrumental",
  "Henry Butler": "blues",
  "Henry Mancini": "stage",
  "Herb Alpert": "jazz",
  "Herbie Hancock": "jazz",
  "Herbie Mann": "jazz",
  "Herman's Hermits": "rock",
  "Het Goede Doel": "european",
  "Hines Earl": "jazz",
  Hohner: "european",
  Hole: "alternative",
  "Holiday Billie": "jazz",
  Hollenboer: "european",
  "Holm, Michael": "european",
  "Home Grown": "alternative",
  "Honey Cone": "soul",
  "John Lee Hooker": "blues",
  "Hootie & the Blowfish": "alternative",
  "HORNER JAMES": "stage",
  "Hot Butter": "instrumental",
  "Hot Chocolate": "funk",
  "Thelma Houston": "soul",
  "Howard Carpendale": "european",
  "Howard Jones": "rock",
  "Hue & Cry": "rock",
  "Hues Corporation": "soul",
  "Huey Lewis & The News": "rock",
  "Hugues Aufray": "french",
  "Humperdinck Engelbert": "rock",
  "Huub Hangop": "european",
  "Ice Cube": "hiphop",
  "Ice MC": "electronic",
  "Ike & Tina Turner": "soul",
  Images: "french",
  Imagination: "funk",
  "Imca Marina": "european",
  "Imperial Teen": "alternative",
  Incognito: "jazz",
  "Information Society": "electronic",
  "Ingram James": "rnb",
  "Inner Circle": "latin",
  "Inner City": "electronic",
  Interactive: "electronic",
  Intermission: "electronic",
  INXS: "rock",
  "Irene Cara": "rock",
  "Iron Butterfly": "rock",
  "Iron Maiden": "metal",
  "Isaac Hayes": "funk",
  "Isabelle Adjani": "french",
  "It's a Beautiful Day": "rock",
  "J.J. Cale": "blues",
  "J.J. Jackson": "soul",
  "Jack Jones": "rock",
  "Jackie DeShannon": "rock",
  "Jackie McLean": "jazz",
  "Jackie Wilson": "soul",
  "Jackson 5": "soul",
  "Jackson Browne": "folk",
  "Michael Jackson": "rnb",
  "Jaco Pastorius": "jazz",
  Jaggerz: "rock",
  "Jam & Spoon": "electronic",
  "Jamaaladeen Tacuma": "jazz",
  James: "alternative",
  "James Last": "instrumental",
  "James Taylor": "folk",
  Jamiroquai: "funk",
  "Jan & Dean": "rock",
  "Jan Hammer": "instrumental",
  "Jane Child": "rock",
  "Jane's Addiction": "alternative",
  "Janet Jackson": "rnb",
  "Janis Ian": "folk",
  "Janis Joplin": "rock",
  "Jann Arden": "rock",
  "Jantje Koopmans": "european",
  "Jars of Clay": "alternative",
  "Jason Donovan": "rock",
  "Jay & The Americans": "rock",
  "Jean Knight": "funk",
  "Jean Michel Jarre": "electronic",
  "Jeannie C. Riley": "country",
  "Jeff Beck": "rock",
  "Jefferson Airplane": "rock",
  "Jefferson Starship": "rock",
  "Jeffrey Osborne": "rnb",
  "Jeffrey Reid Baker": "instrumental",
  "Jennifer Lopez": "rock",
  "Jennifer Rush": "rock",
  "Jennifer Warnes": "rock",
  "Jeremy Jackson": "rock",
  "Jerome Kern": "stage",
  "Jerry Herman": "stage",
  "Jerry Lee Lewis": "rock",
  "Mungo Jerry": "rock",
  "Jessica Simpson": "rock",
  "Jesus Jones": "alternative",
  "Jethro Tull": "progressive",
  Jewel: "folk",
  Jigsaw: "rock",
  "Jim Croce": "folk",
  "Jimi Hendrix": "rock",
  "Jimmy Barnes": "rock",
  "Jimmy Buffett": "country",
  "Jimmy Cliff": "latin",
  "Jimmy Gilmer": "rock",
  "Jimmy James": "soul",
  "Jimmy McGriff": "jazz",
  "Jimmy Nail": "rock",
  "Jimmy Reed": "blues",
  "Jimmy Ruffin": "soul",
  "Jimmy Somerville": "rock",
  "Jive Bunny": "rock",
  "Joan Jett": "rock",
  "Joan Osborne": "rock",
  "Jobim Antonio Carlos": "jazz",
  Jodeci: "rnb",
  "Jody Reynolds": "rock",
  "Jody Watley": "rnb",
  Joe: "rnb",
  "Joe Cocker": "rock",
  "Joe Dassin": "french",
  "Joe Diffie": "country",
  "Joe Dolce": "novelty",
  "Joe Jackson": "rock",
  "Joe Satriani": "rock",
  "Joe South": "rock",
  "Joe Walsh": "rock",
  "Joey Dee": "rock",
  "Joey Ramone": "alternative",
  "Johann Nepomuk Hummel": "classical",
  "Johannes Brahms": "classical",
  "John Denver": "country",
  "John Farnham": "rock",
  "John Field": "classical",
  "John Fogerty": "rock",
  "John Fred": "rock",
  "John Lennon": "rock",
  "John Mellencamp": "rock",
  "John Paul Young": "rock",
  "John Scofield": "jazz",
  "John Waite": "rock",
  "Johnny & The Hurricanes": "rock",
  "Johnny Bristol": "soul",
  "Johnny Gill": "rnb",
  "Johnny Hates Jazz": "rock",
  "Johnny Hoes": "european",
  "Johnny Horton": "country",
  "Johnny Kemp": "rnb",
  "Johnny Logan": "rock",
  "Johnny Mathis": "rock",
  "Johnny Mercer": "stage",
  "Johnny Nash": "rock",
  "Johnny Rivers": "rock",
  "Johnny Shines": "blues",
  "Johnson James P": "jazz",
  "Jolson. Al": "stage",
  "Jon Cleary": "blues",
  "Jon Secada": "latin",
  "Joni Mitchell": "folk",
  Jordy: "french",
  "Jose Feliciano": "latin",
  "Joseph Kosma": "stage",
  "Joseph Lamb": "jazz",
  "Joshua Kadison": "rock",
  Journey: "rock",
  Jovanotti: "italian",
  "Juan Luis Guerra": "latin",
  "Judas Priest": "metal",
  "Judy Collins": "folk",
  "Jule Styne": "stage",
  "Julian Lennon": "rock",
  "Julie Andrews": "stage",
  "Julie Covington": "stage",
  "Julio Iglesias": "latin",
  "Junior Walker": "soul",
  "Jurgen Drews": "european",
  "K-Ci & JoJo": "rnb",
  "k.d. lang": "country",
  Kadoc: "electronic",
  Kaempfert: "instrumental",
  "Kamoze Ini": "latin",
  Kansas: "progressive",
  Kaoma: "latin",
  "Karas Anton": "instrumental",
  "Kate Bush": "progressive",
  "Katrina and the Waves": "rock",
  "KC and The Sunshine Band": "funk",
  "R. Kelly": "rnb",
  "Kenny Baker": "country",
  "Kenny Dorham": "jazz",
  "Kenny G": "instrumental",
  "Kenny Loggins": "rock",
  "Kenny Thomas": "rnb",
  "Kevin Paige": "rock",
  "Kid Rock": "hiphop",
  "Kiki Dee": "rock",
  "Kim Appleby": "rock",
  "Kim Wilde": "rock",
  "King Crimson": "progressive",
  "King Harvest": "rock",
  "KING,RICKY": "instrumental",
  Kingsmen: "rock",
  Kiss: "metal",
  "Klaus & Klaus": "european",
  "Klein Orkest": "european",
  "Kool & The Gang": "funk",
  "Koos Alberts": "european",
  Korgis: "rock",
  Korn: "metal",
  Kraftwerk: "electronic",
  "Kris Kristofferson": "country",
  "Kristina Bach": "european",
  "Kylie Minogue": "rock",
  "La Bionda": "italian",
  "La Bouche": "electronic",
  LaBelle: "funk",
  "Laid Back": "rock",
  "Laine Cleo": "jazz",
  LaSalle: "soul",
  LaTour: "electronic",
  "Laura Branigan": "rock",
  "Laura Pausini": "italian",
  "Le Grand Orchestre du Splendid": "french",
  Leali: "italian",
  "LeAnn Rimes": "country",
  "Led Zeppelin": "metal",
  "Lee Ritenour": "jazz",
  "Leif Garrett": "rock",
  LEN: "rock",
  "Lena Horne": "jazz",
  "Lenny Kravitz": "alternative",
  "Leo Friedman": "stage",
  "Leo Sayer": "rock",
  "Leon Russell": "folk",
  "Les Humphries Singers": "european",
  "Lesley Gore": "rock",
  "Level 42": "rock",
  "Lewis George": "jazz",
  'Lewis Meade "lux"': "jazz",
  "Lewis Ramsey": "jazz",
  LFO: "rock",
  "Liesbeth List": "european",
  LIGABUE: "italian",
  LightHouse: "rock",
  Limahl: "rock",
  "Limp Bizkit": "metal",
  "Linda Ronstadt": "country",
  "Linda, Roos & Jessica": "european",
  "Lindsey Buckingham": "rock",
  "Linkin Park": "metal",
  "Lionel Richie": "rnb",
  "Lipps, Inc.": "funk",
  "Lisa Lisa": "rnb",
  "Lisa Loeb": "folk",
  "Lisa Stansfield": "soul",
  Lit: "alternative",
  "Little Eva": "rock",
  "Little Richard": "rock",
  "Little River Band": "rock",
  "Little Texas": "country",
  "Little Tony": "italian",
  Live: "alternative",
  "LL Cool J": "hiphop",
  Lobo: "rock",
  "Local H": "alternative",
  Loesser: "stage",
  Loft: "electronic",
  "Loggins & Messina": "folk",
  "Lois Lane": "european",
  Londonbeat: "rock",
  "Looking Glass": "rock",
  "Los Bravos": "rock",
  "Los Del Rio": "latin",
  "Los Lobos": "latin",
  "Lou Bega": "latin",
  "Lou Rawls": "soul",
  "Lou Reed": "alternative",
  "Louis Moreau Gottschalk": "classical",
  "Louis Prima": "jazz",
  "Love Affair": "rock",
  "Love Sculpture": "blues",
  "Love Unlimited Orchestra": "funk",
  Loverboy: "rock",
  "Ludwig van Beethoven": "classical",
  Lulu: "rock",
  Lunapop: "italian",
  Luniz: "hiphop",
  "Luther Ingram": "soul",
  "Luther Vandross": "rnb",
  "Lutricia McNeal": "rnb",
  "Lynn Anderson": "country",
  "Lynyrd Skynyrd": "rock",
  M: "rock",
  "M People": "electronic",
  M2M: "rock",
  "Mac Davis": "country",
  "Macy Gray": "soul",
  Madness: "rock",
  Madonna: "rock",
  "Magic Affair": "electronic",
  "Mahalia Jackson": "soul",
  "Major Harris": "soul",
  "Malmsteen Yngwie": "metal",
  "The Mamas & The Papas": "rock",
  "Mandy Moore": "rock",
  "Manfred Mann": "rock",
  Mango: "italian",
  "Marc Almond": "rock",
  "Marc Anthony": "latin",
  "Marc Cohn": "folk",
  "Marco Borsato": "european",
  "Marcy Playground": "alternative",
  "Maria McKee": "rock",
  "Maria Muldaur": "blues",
  "Mariah Carey": "rnb",
  "Marianne & Michael": "european",
  "Marianne Faithfull": "folk",
  Marillion: "progressive",
  "Marilyn Manson": "metal",
  "Marilyn Monroe": "stage",
  "Mark 'Oh": "electronic",
  "Mark Collie": "country",
  "Mark Morrison": "rnb",
  "Mark Snow": "stage",
  "Marky Mark": "hiphop",
  "Marky Ramone": "alternative",
  "Martha Reeves": "soul",
  Martika: "rock",
  "Martin Dean": "rock",
  "Ricky Martin": "latin",
  Marusha: "electronic",
  "Marvin Hamlisch": "stage",
  "Richard Marx": "rock",
  "Mary Hopkins": "rock",
  "Mary J. Blige": "rnb",
  "Mary Wells": "soul",
  Masini: "italian",
  "Mason Williams": "instrumental",
  Massada: "european",
  "Master P": "hiphop",
  Masterboy: "electronic",
  "Matia Bazar": "italian",
  "Matt Bianco": "jazz",
  "Matthew Wilder": "rock",
  "Maxi Priest": "latin",
  "Maxime Le Forestier": "french",
  Maxx: "electronic",
  "MC Hammer": "hiphop",
  "Paul McCartney": "rock",
  "The McCoys": "rock",
  "McFadden & Whitehead": "funk",
  "Meat Loaf": "rock",
  "Meat Puppets": "alternative",
  Mecano: "latin",
  Megadeth: "metal",
  "Mel C": "rock",
  "Mel Carter": "rock",
  Melanie: "folk",
  "Melina Mercouri": "latin",
  "Melissa Etheridge": "alternative",
  "Melissa Manchester": "rock",
  "Men at Work": "rock",
  "Men Without Hats": "rock",
  "Meredith Brooks": "alternative",
  "Merle Travis": "country",
  Metallica: "metal",
  Mezzoforte: "jazz",
  MFSB: "funk",
  "Miami Sound Machine": "latin",
  "Mica Paris": "rnb",
  "Michael Ball": "stage",
  "Michael Bolton": "rock",
  "Michael Damian": "rock",
  "Michael English": "rock",
  "Michael Johnson": "rock",
  "Michael Learns to Rock": "rock",
  "Michael McDonald": "soul",
  "Michael Penn": "rock",
  "Michael Sembello": "rock",
  "Michael Stanley Band": "rock",
  "Michael Walthius": "instrumental",
  "Michael Zager": "funk",
  "Michel Delpech": "french",
  "Michele Zarrillo": "italian",
  "Mickey & Sylvia": "rock",
  "Middle of the Road": "rock",
  "Midnight Oil": "alternative",
  "Mike + The Mechanics": "rock",
  "Mike Oldfield": "progressive",
  "Mike Reno": "rock",
  "John Miles": "rock",
  "Milli Vanilli": "rock",
  "Mily Balakirev": "classical",
  Mina: "italian",
  "Mink DeVille": "rock",
  "Missy Elliott": "hiphop",
  "Mitch Ryder": "rock",
  "Mixed Emotions": "rock",
  MN8: "rock",
  "Mo-Do": "electronic",
  Moby: "electronic",
  Mocedades: "latin",
  "Modern Jazz Quartet": "jazz",
  "Modern Talking": "european",
  Moist: "alternative",
  Monica: "rnb",
  "Monty Python": "novelty",
  Morandi: "italian",
  "Morricone Ennio": "stage",
  "Morris Albert": "rock",
  "Morton Jelly Roll": "jazz",
  Mosch: "european",
  Motels: "rock",
  "Motley Crue": "metal",
  "Mott The Hoople": "rock",
  "Mouskouri Nana": "latin",
  "Mr. Mister": "rock",
  "Mr. President": "electronic",
  Mud: "rock",
  "Murray Head": "stage",
  "Mylene Farmer": "french",
  "N-Trance": "electronic",
  "Nada Surf": "alternative",
  Nakatomi: "electronic",
  "Naked Eyes": "rock",
  "Nancy Sinatra": "rock",
  Nas: "hiphop",
  "Nashville Teens": "rock",
  "Nat King Cole": "jazz",
  "Natalie Cole": "jazz",
  "Natalie Imbruglia": "alternative",
  "Natalie Merchant": "alternative",
  Nazareth: "metal",
  "Neil Diamond": "rock",
  "Neil Sedaka": "rock",
  "Neil Young": "alternative",
  Nek: "italian",
  Nelly: "hiphop",
  "Nelson Oliver": "jazz",
  Nena: "european",
  "New Kids on the Block": "rock",
  "New Order": "electronic",
  "New Radicals": "alternative",
  "New Vaudeville Band": "rock",
  "Niamh Kavanagh": "rock",
  "Nick Berry": "rock",
  "Nick Gilder": "rock",
  "Nick Kamen": "rock",
  "Nick MacKenzie": "rock",
  "Nicki French": "rock",
  "Nico Landers": "european",
  "Night Ranger": "metal",
  Nightcrawlers: "electronic",
  "Nik Kershaw": "rock",
  "Nina Simone": "jazz",
  "Nine Days": "alternative",
  "Nine Inch Nails": "alternative",
  "Nini Rosso": "instrumental",
  "Nino De Angelo": "european",
  Nirvana: "alternative",
  "No Doubt": "alternative",
  "No Mercy": "rock",
  NOFX: "alternative",
  Nomadi: "italian",
  "Norman Blake": "country",
  "Norman Connors": "soul",
  "Norman Greenbaum": "rock",
  "Nuovi Angeli": "italian",
  Oasis: "alternative",
  Oberkrainer: "european",
  "Ocean Colour Scene": "alternative",
  Odyssey: "funk",
  "Ohio Express": "rock",
  "Ohio Players": "funk",
  "Oingo Boingo": "alternative",
  "Oleta Adams": "soul",
  "Olivia Newton-John": "rock",
  Omar: "soul",
  OMC: "rock",
  "Orchestral Manoeuvres in the Dark": "rock",
  Opus: "rock",
  Orbital: "electronic",
  Orgy: "alternative",
  Orleans: "rock",
  "Ornella Vanoni": "italian",
  "Oscar Peterson": "jazz",
  "Otis Redding": "soul",
  Ottawan: "rock",
  "Our Lady Peace": "alternative",
  "Ozzy Osbourne": "metal",
  Pagliaro: "french",
  "Palemiger Spatzen": "european",
  Pantera: "metal",
  "Paola Turci": "italian",
  Paoli: "italian",
  "Papa Roach": "metal",
  "Parker Charlie": "jazz",
  "Parton Dolly": "country",
  "Party Animals": "electronic",
  "Pat Benatar": "rock",
  "Pat Boone": "rock",
  "Pat Metheny": "jazz",
  "Pater Moeskroen": "european",
  "Pato Banton": "latin",
  "Patricia Paay": "european",
  "Patrick Bruel": "french",
  "Patrick Hernandez": "rock",
  "Patrick Swayze": "rock",
  "Patsy Cline": "country",
  "Patti Smith": "alternative",
  "Paul Davis": "rock",
  "Paul de Leeuw": "european",
  "Paul Desmond": "jazz",
  "Paul Dukas": "classical",
  "Paul Mauriat": "instrumental",
  "Paul Revere and The Raiders": "rock",
  "Paul Simon": "folk",
  "Paul Young": "rock",
  "Paula Abdul": "rock",
  "Paula Cole": "rock",
  "Peaches & Herb": "soul",
  "Pearl Jam": "alternative",
  "Peppino di Capri": "italian",
  "Percy Faith": "instrumental",
  "Percy Grainger": "classical",
  "Percy Sledge": "soul",
  Perplexer: "electronic",
  "Perry Como": "rock",
  "Pet Shop Boys": "electronic",
  "Peter Allen": "rock",
  "Peter Andre": "rock",
  "Peter Cetera": "rock",
  "Peter Cornelius": "european",
  "Peter de Koning": "european",
  "Peter Frampton": "rock",
  "Peter Gabriel": "progressive",
  "Peter Kent": "rock",
  "Peter Koelewijn & Zijn Rockets": "european",
  "Peter Maffay": "european",
  "Peter Schilling": "european",
  "Peter Tosh": "latin",
  "Peter, Paul & Mary": "folk",
  "Petula Clark": "rock",
  Pharao: "electronic",
  Phish: "progressive",
  "Pink Floyd": "progressive",
  Player: "rock",
  Poco: "country",
  Pooh: "italian",
  "Powell Bud": "jazz",
  "The Presidents of the United States of America": "alternative",
  "Lloyd Price": "soul",
  Primus: "alternative",
  Prince: "funk",
  "Procol Harum": "progressive",
  "Professor Longhair": "blues",
  "Pseudo Echo": "rock",
  "Puff Daddy": "hiphop",
  Quarterflash: "rock",
  Queen: "rock",
  Queensryche: "metal",
  "Quiet Riot": "metal",
  "Quincy Jones": "jazz",
  "R.E.M.": "alternative",
  Radiohead: "alternative",
  Raf: "italian",
  "Raffaella Carra": "italian",
  "Rage Against the Machine": "alternative",
  Rainbow: "metal",
  "Ram Jam": "rock",
  Rammstein: "metal",
  "Randy Crawford": "soul",
  "Randy Newman": "folk",
  "Randy VanWarmer": "rock",
  Ranieri: "italian",
  "Rare Earth": "rock",
  Rascel: "italian",
  Rastape: "latin",
  Ratt: "metal",
  "Ray Charles": "soul",
  "Ray Davies": "rock",
  "Ray Parker Jr.": "funk",
  Raydio: "funk",
  "Real Life": "rock",
  "Real McCoy": "electronic",
  "Real Thing": "soul",
  "Red 5": "electronic",
  "Red Hot Chili Peppers": "alternative",
  Redbone: "rock",
  Rednex: "electronic",
  "Reel 2 Real": "electronic",
  "Reel Big Fish": "alternative",
  "Reinhardt Django": "jazz",
  Rembrandts: "rock",
  "Renato Teixeira": "latin",
  "Rene Carol": "european",
  "Rene Froger": "european",
  "Rene Klijn": "european",
  "Renee de Haan": "european",
  "Renee Rosnes": "jazz",
  "Renzo Arbore": "italian",
  "REO Speedwagon": "rock",
  "Restless Heart": "country",
  "Riccardo Cocciante": "italian",
  "Ricchi e Poveri": "italian",
  "Rich , Buddy": "jazz",
  "Richard Harris": "rock",
  "Richard Sanderson": "rock",
  "Rick Astley": "rock",
  "Rick Derringer": "rock",
  "Rick James": "funk",
  "Rick Springfield": "rock",
  "Rickie Lee Jones": "folk",
  "Ricky Nelson": "rock",
  Righeira: "italian",
  "Right Said Fred": "rock",
  "Ringo Starr": "rock",
  Rionegro: "latin",
  "Rita Coolidge": "rock",
  RMB: "electronic",
  "Rob Zombie": "metal",
  "Robbie Williams": "rock",
  "Robert John": "rock",
  "Robert Knight": "rock",
  "Robert Leroy": "european",
  "Robert Miles": "electronic",
  "Robert Palmer": "rock",
  "Roberta Flack": "soul",
  "Robin Beck": "rock",
  "Robin S": "electronic",
  Robyn: "rock",
  "Rocco Granata": "italian",
  Rockwell: "funk",
  "Rocky Horror": "stage",
  "Rod Stewart": "rock",
  "RODGERS RICHARD": "stage",
  "Roger Williams": "instrumental",
  "Rogers Kenny": "country",
  "The Romantics": "rock",
  "Romina Power Al Bano": "italian",
  Ron: "italian",
  "Ronan Keating": "rock",
  "Ronnie Spector": "rock",
  "Ronny Jordan": "jazz",
  "Roots Syndicate": "latin",
  "Rory Block": "blues",
  "Rose Royce": "funk",
  "Vasco Rossi": "italian",
  Roxette: "rock",
  "Roxy Music": "progressive",
  "Roy Black": "european",
  "Roy Clark": "country",
  "Roy Orbison": "rock",
  Rozalla: "electronic",
  "Ruby & The Romantics": "rock",
  "Rudi Carrell": "european",
  Rufus: "funk",
  "Rufus Thomas": "funk",
  Ruggeri: "italian",
  "Rupert Holmes": "rock",
  Rush: "progressive",
  "Ruth Jacott": "european",
  "Ry Cooder": "blues",
  "Ryan Paris": "rock",
  Sabrina: "italian",
  Sade: "soul",
  Saez: "french",
  Sailor: "rock",
  "Sailor Moon": "novelty",
  "Salt-N-Pepa": "hiphop",
  "Sam & Dave": "soul",
  "Sam Brown": "rock",
  "Sam Cooke": "soul",
  "Sam the Sham & The Pharaohs": "rock",
  "Sammy Davis, Jr.": "rock",
  "Sammy Hagar": "metal",
  "Sammy Nestico": "jazz",
  "Sandie Shaw": "rock",
  "Sandro & Gustavo": "latin",
  "Sandy Denny": "folk",
  "Santa Esmeralda": "rock",
  Santana: "latin",
  "Sarah McLachlan": "folk",
  "SASH!": "electronic",
  "Sauter-Finegan Orchestra": "jazz",
  "Savage Garden": "rock",
  "Save Ferris": "alternative",
  "Sawyer Brown": "country",
  "Scatman John": "electronic",
  "Schilling, Peter": "european",
  Scooter: "electronic",
  Scorpions: "metal",
  "Scott James": "jazz",
  "Scott Joplin": "jazz",
  "Scott McKenzie": "folk",
  "Scritti Politti": "rock",
  Seal: "soul",
  "Seals & Crofts": "folk",
  "The Searchers": "rock",
  Selena: "latin",
  Semisonic: "alternative",
  "Sergio Franchi": "italian",
  "Sergio Mendes": "latin",
  Shaggy: "latin",
  Shakatak: "jazz",
  "Shania Twain": "country",
  Shanice: "rnb",
  "Shaun Cassidy": "rock",
  "Shawn Colvin": "folk",
  "Shawn Mullins": "folk",
  "Shearing George": "jazz",
  "Sheb Wooley": "novelty",
  "Sheena Easton": "rock",
  "Shelley Fabares": "rock",
  "Shep & The Limelites": "rock",
  Sheriff: "rock",
  "Shirley Bassey": "rock",
  "Shocking Blue": "rock",
  "Shola Ama": "rnb",
  Showaddywaddy: "rock",
  "Silver Convention": "soul",
  Silverchair: "alternative",
  "Simon & Garfunkel": "folk",
  "Simple Minds": "rock",
  "Simply Red": "soul",
  "Sinead O'Connor": "alternative",
  Sisqo: "rnb",
  "Sister Hazel": "alternative",
  "Sister Sledge": "funk",
  "Sixpence None the Richer": "alternative",
  "Skee-Lo": "hiphop",
  "Skid Row": "metal",
  "Sly & The Family Stone": "funk",
  "Small Faces": "rock",
  "Smash Mouth": "alternative",
  "Smokey Robinson": "soul",
  Smokie: "rock",
  Snap: "electronic",
  "Sniff 'n' the Tears": "rock",
  "Snoop Dogg": "hiphop",
  "Soft Cell": "electronic",
  Sonia: "rock",
  "Sonic Youth": "alternative",
  "Sonny & Cher": "rock",
  "Sophie B. Hawkins": "rock",
  Sorrenti: "italian",
  "Soul Asylum": "alternative",
  "Soul II Soul": "rnb",
  Soundgarden: "alternative",
  "Spandau Ballet": "rock",
  "Spanky & Our Gang": "rock",
  Sparks: "rock",
  "Special EFX": "jazz",
  "Spice Girls": "rock",
  "Spin Doctors": "alternative",
  Spinners: "soul",
  Spirit: "rock",
  "Spyro Gyra": "jazz",
  Squeeze: "rock",
  "Squirrel Nut Zippers": "jazz",
  Stampeders: "rock",
  "Stan Getz": "jazz",
  "Stan Kenton": "jazz",
  "Stanley Clarke": "jazz",
  "Star Wash": "electronic",
  "Starland Vocal Band": "rock",
  Starship: "rock",
  "Status Quo": "rock",
  Steam: "rock",
  "Steely Dan": "rock",
  "Stephanie Mills": "rnb",
  "Stephen Bishop": "rock",
  Steppenwolf: "rock",
  "Steps Ahead": "jazz",
  "Stern Mike": "jazz",
  "Steve Miller Band": "rock",
  "Steve Perry": "rock",
  "Steve Vai": "metal",
  "Steve Winwood": "rock",
  "Stevens Shakin ": "rock",
  "Stevie B": "rock",
  "Stevie Nicks": "rock",
  "Stevie Wonder": "soul",
  Stiltskin: "alternative",
  Sting: "rock",
  "Stone Temple Pilots": "alternative",
  Stories: "rock",
  "Strawberry Alarm Clock": "rock",
  "Stray Cats": "rock",
  Styx: "progressive",
  Sublime: "alternative",
  "Sugar Lee Hooper": "european",
  "Sugar Ray": "alternative",
  Sugarloaf: "rock",
  Supertramp: "progressive",
  Surface: "rnb",
  Survivor: "rock",
  "Suzanne Ciani": "instrumental",
  "Suzanne Vega": "folk",
  "Suzi Quatro": "rock",
  Sweet: "rock",
  "Swing Out Sister": "soul",
  "Swingin' Medallions": "rock",
  "Sydney Youngblood": "rnb",
  Sylvester: "soul",
  "T'Pau": "rock",
  "T-Square": "jazz",
  "T. Rex": "rock",
  Taco: "rock",
  "Tag Team": "hiphop",
  "Take That": "rock",
  "Tal Bachman": "rock",
  "Talk Talk": "progressive",
  "Talking Heads": "progressive",
  "Tammy Wynette": "country",
  "Tanita Tikaram": "folk",
  "Tasmin Archer": "rock",
  "Tatum Art": "jazz",
  Tavares: "soul",
  "Taylor Dayne": "rock",
  "Tears for Fears": "rock",
  Technohead: "electronic",
  Technotronic: "electronic",
  "Ted Nugent": "metal",
  "Television Theme Songs": "stage",
  "Ten Years After": "blues",
  "Terence Trent D'Arby": "soul",
  "Terry Jacks": "rock",
  "Terry Stafford": "rock",
  Texas: "rock",
  "The Alan Parsons Project": "progressive",
  "The Allman Brothers Band": "rock",
  "The Animals": "rock",
  "The Archies": "novelty",
  "The Association": "rock",
  "The B-52's": "alternative",
  "The Babys": "rock",
  "The Bangles": "rock",
  "The Beach Boys": "rock",
  "The Beatles": "rock",
  "The Beau Brummels": "rock",
  "The Beautiful South": "alternative",
  "The Blue Diamonds": "rock",
  "The Bluebells": "rock",
  "The Bluegrass Cardinals": "country",
  "The Blues Brothers": "blues",
  "The Boomtown Rats": "alternative",
  "The Box Tops": "rock",
  "The Brecker Brothers": "jazz",
  "The Brian Setzer Orchestra": "jazz",
  "The Brothers Four": "folk",
  "The Buckinghams": "rock",
  "The Byrds": "folk",
  "The Cardigans": "alternative",
  "The Cars": "rock",
  "The Chi-Lites": "soul",
  "The Chiffons": "rock",
  "The Chordettes": "rock",
  "The Christians": "rock",
  "The Clash": "alternative",
  "The Contours": "soul",
  "The Corrs": "rock",
  "The Cover Girls": "rock",
  "The Cowsills": "rock",
  "The Cranberries": "alternative",
  "The Cult": "alternative",
  "The Cure": "alternative",
  "The Cyrkle": "rock",
  "The Dave Clark Five": "rock",
  "The Doobie Brothers": "rock",
  "The Doors": "rock",
  "The Easybeats": "rock",
  "The Escape Club": "rock",
  "The Everly Brothers": "rock",
  "The Fabulous Thunderbirds": "blues",
  "The Five Satins": "rock",
  "The Five Stairsteps": "soul",
  "The Flying Pickets": "rock",
  "The Folk Implosion": "alternative",
  "The Four Aces": "rock",
  "The Four Preps": "rock",
  "The Four Seasons": "rock",
  "The Gap Band": "funk",
  "The Go-Go's": "rock",
  "The Grass Roots": "rock",
  "The Happenings": "rock",
  "The Hollies": "rock",
  "The Honeydrippers": "rock",
  "The Hooters": "rock",
  "The Human League": "electronic",
  "The Ink Spots": "rock",
  "The Isley Brothers": "funk",
  "The J. Geils Band": "rock",
  "The Kelly Family": "rock",
  "The Kinks": "rock",
  "The KLF": "electronic",
  "The Knack": "rock",
  "The Left Banke": "rock",
  "The Lemon Pipers": "rock",
  "The Lemonheads": "alternative",
  "The Lovin' Spoonful": "rock",
  "The Main Ingredient": "soul",
  "The Manhattan Transfer": "jazz",
  "The Manhattans": "soul",
  "The Marcels": "rock",
  "The Marshall Tucker Band": "country",
  "The Mavericks": "country",
  "The McGuire Sisters": "rock",
  "The Mighty Mighty Bosstones": "alternative",
  "The Mindbenders": "rock",
  "The Monkees": "rock",
  "The Moody Blues": "progressive",
  "The New Colony Six": "rock",
  "The New Seekers": "rock",
  "The Notorious B.I.G.": "hiphop",
  "The O'Jays": "soul",
  "The Offspring": "alternative",
  "The Outfield": "rock",
  "The Outhere Brothers": "electronic",
  "The Partridge Family": "rock",
  "The Pasadenas": "soul",
  "The Platters": "rock",
  "The Pointer Sisters": "funk",
  "The Police": "rock",
  "The Pretenders": "alternative",
  "The Prodigy": "electronic",
  "The Psychedelic Furs": "alternative",
  "The Ramsey Lewis Trio": "jazz",
  "The Rascals": "rock",
  "The Raspberries": "rock",
  "The Righteous Brothers": "rock",
  "The Rippingtons": "jazz",
  "The Ritchie Family": "soul",
  "The Rivieras": "rock",
  "The Robert Cray Band": "blues",
  "The Rolling Stones": "rock",
  "The Ronettes": "rock",
  "The Rooftop Singers": "folk",
  "The Rubettes": "rock",
  "The Rutles": "novelty",
  "The Seekers": "folk",
  "The Shadows": "instrumental",
  "The Shamen": "electronic",
  "The Shangri-Las": "rock",
  "The Smashing Pumpkins": "alternative",
  "The Smiths": "alternative",
  "The Soul Survivors": "soul",
  "The Spencer Davis Group": "rock",
  "The Spotnicks": "instrumental",
  "The Standells": "rock",
  "The Stranglers": "alternative",
  "The Style Council": "rock",
  "The Stylistics": "soul",
  "The Sugarhill Gang": "hiphop",
  "The Supremes": "soul",
  "The Surfaris": "rock",
  "The Swinging Blue Jeans": "rock",
  "The Sylvers": "funk",
  "The Syndicate of Sound": "rock",
  "The Temptations": "soul",
  "The The Kingston Trio": "folk",
  "The Tony Rich Project": "rnb",
  "The Tragically Hip": "alternative",
  "The Trammps": "soul",
  "The Tremeloes": "rock",
  "The Troggs": "rock",
  "The Vapors": "rock",
  "The Ventures": "instrumental",
  "The Verve": "alternative",
  "The Verve Pipe": "alternative",
  "The Walker Brothers": "rock",
  "The Wallflowers": "alternative",
  "The Weather Girls": "rock",
  "The Whispers": "rnb",
  "The Who": "rock",
  "The Yardbirds": "rock",
  "The Youngbloods": "rock",
  "The Zombies": "rock",
  "Thelonious Monk": "jazz",
  Them: "rock",
  "Theodorakis Mikis": "latin",
  "They Might Be Giants": "alternative",
  "Thin Lizzy": "metal",
  "Third Eye Blind": "alternative",
  "Thomas Campion": "classical",
  "Thomas Dolby": "rock",
  "Thompson Twins": "rock",
  "Three degrees the": "soul",
  "Three Dog Night": "rock",
  Tiffany: "rock",
  "Tim Immers": "european",
  "Time Bandits": "rock",
  "Tina Turner": "soul",
  TLC: "rnb",
  "Toad the Wet Sprocket": "alternative",
  "Todd Rundgren": "progressive",
  "Tom Astor": "european",
  "Tom Jones": "rock",
  "Tom McDermott": "jazz",
  "Tom Petty": "rock",
  "Tom Petty and The Heartbreakers": "rock",
  "Tom Turpin": "jazz",
  "Tommy Edwards": "rock",
  "Tommy Flanagan": "jazz",
  "Tommy James": "rock",
  "Tommy Roe": "rock",
  "Tone-Loc": "hiphop",
  "Toni Basil": "rock",
  "Toni Braxton": "rnb",
  "Tony Joe White": "blues",
  "Tony Orlando": "rock",
  Tool: "progressive",
  Tornados: "instrumental",
  "Torriani, Vico": "european",
  Toto: "rock",
  "Tower of Power": "funk",
  "Umberto Tozzi": "italian",
  "Tracey Ullman": "rock",
  "Tracy Byrd": "country",
  "Tracy Chapman": "folk",
  Traffic: "progressive",
  "Trans-X": "electronic",
  "Traveling Wilburys": "rock",
  "Travis Tritt": "country",
  "Trini Lopez": "latin",
  Trio: "european",
  "Trio Hellenique": "latin",
  "Trisha Yearwood": "country",
  Trovato: "italian",
  Tupac: "hiphop",
  Turtles: "rock",
  "Twila Paris": "rock",
  "Tyner Mccoy": "jazz",
  "Type O Negative": "metal",
  "Typically Tropical": "rock",
  "U.S.A. for Africa": "rock",
  U2: "rock",
  U96: "electronic",
  UB40: "latin",
  "Ugly Kid Joe": "metal",
  Ultravox: "rock",
  Undercover: "rock",
  "Urban Cookie Collective": "electronic",
  "Uriah Heep": "metal",
  Us3: "jazz",
  Usher: "rnb",
  UZEB: "jazz",
  "Valens Ritchie": "rock",
  "Van Halen": "metal",
  "Van McCoy": "soul",
  "Van Morrison": "rock",
  "Vanessa Paradis": "french",
  "Vanessa Williams": "rnb",
  Vangelis: "instrumental",
  "Vanilla Fudge": "rock",
  "Vanilla Ice": "hiphop",
  "Vaughan Sarah": "jazz",
  Vengaboys: "electronic",
  "Vera Lynn": "rock",
  "Vertical Horizon": "alternative",
  "Veruca Salt": "alternative",
  "Vicki Sue Robinson": "rock",
  "Victoria Williams": "folk",
  "Village People": "soul",
  "Vince Guaraldi": "jazz",
  "Violent Femmes": "alternative",
  Visage: "electronic",
  "VOF de Kunst": "european",
  Wagner: "classical",
  "Waller Fats": "jazz",
  "Walter Donaldson": "stage",
  "Walter Egan": "rock",
  "Walter Murphy": "rock",
  "Wang Chung": "rock",
  War: "funk",
  "Warren G": "hiphop",
  "Warren Zevon": "folk",
  "Was (Not Was)": "funk",
  "Washington Dinah": "jazz",
  "Watson Johnny Guitar": "funk",
  Wax: "rock",
  "Wayne Jeff": "stage",
  "Weather Report": "jazz",
  Weezer: "alternative",
  "Wendy Moten": "rnb",
  Westbam: "electronic",
  Westernhagen: "european",
  Westlife: "rock",
  "Wet Wet Wet": "rock",
  "Wet Willie": "rock",
  "Wham!": "rock",
  Whigfield: "electronic",
  "White Lion": "metal",
  "White Town": "rock",
  "White Zombie": "metal",
  "Whiteman Paul & His Orchestra": "jazz",
  Whitesnake: "metal",
  "Whitney Houston": "rnb",
  "Wilbert Harrison": "rock",
  "Wild Cherry": "funk",
  "Will Glahe": "european",
  "Will Smith": "hiphop",
  "Will to Power": "rock",
  "Willeke Alberti": "european",
  "William Orbit": "electronic",
  "Willie Nelson": "country",
  "Wilson Phillips": "rock",
  "Wilson Pickett": "soul",
  "Wilson Teddy": "jazz",
  Winger: "metal",
  Wings: "rock",
  "Wolfgang Amadeus Mozart": "classical",
  "Wolfgang Ambros": "european",
  "Wolter Kroes": "european",
  Womack: "soul",
  "Worlds Apart": "rock",
  "Xavier Cugat": "latin",
  Xscape: "rnb",
  Yanni: "instrumental",
  Yazoo: "electronic",
  "Yazz & plastic population": "electronic",
  "Yellow Magic Orchestra (YMO)": "electronic",
  Yes: "progressive",
  "Youssou N'Dour": "latin",
  "Yvonne Elliman": "rock",
  "Zamfir Gheorghe": "instrumental",
  Zappa: "progressive",
  Zebrahead: "alternative",
  "Zequinha Abreu": "latin",
  Zero: "italian",
  "Zez Confrey": "jazz",
  "Zeze di Camargo": "latin",
  Zhane: "rnb",
  "Zhi-Vago": "electronic",
  Zucchero: "italian",
  "ZZ Top": "metal",
};

export const artistShelf = (name: string): ShelfId =>
  primaryShelves[canonicalArtistName(name)] || "other";

// Secondary memberships let artists appear in related filters without duplicate
// cards in the default view. Add only deliberate, curated cross-listings here.
const secondaryShelves: Record<string, ShelfId[]> = {
  Pooh: ["rock", "progressive"],
  Genesis: ["rock"],
  "Chick Corea": ["instrumental"],
  Enya: ["rock", "latin"],
  "Andrew Lloyd Webber": ["classical"],
  "Georges Brassens": ["folk"],
  "Francis Cabrel": ["folk"],
  "Francesco De Gregori": ["folk"],
  "Lucio Battisti": ["rock"],
  "Vasco Rossi": ["rock"],
  Nomadi: ["rock"],
  "Andrea Bocelli": ["classical"],
  Rammstein: ["european"],
  "Die Arzte": ["european"],
  "Daft Punk": ["french"],
  Kraftwerk: ["european"],
  Zappa: ["jazz"],
  Santana: ["rock"],
  "Leonard Bernstein": ["classical"],
};
export const artistShelves = (name: string): ShelfId[] => [
  artistShelf(name),
  ...(secondaryShelves[canonicalArtistName(name)] || []),
];
