import { canonicalArtistName } from "./artistShelves";

// Editorial browsing facets. Each artist has one era; formative years
// resolve careers spanning multiple periods. Missing dates stay unassigned.
export const ROCK_POP_GENRES = [
  {
    id: "traditional",
    label: "Traditional pop & crooners",
  },
  {
    id: "rockabilly",
    label: "Rock ’n’ roll & rockabilly",
  },
  {
    id: "vocal",
    label: "Doo-wop & early vocal groups",
  },
  {
    id: "earlypop",
    label: "Early-1960s pop & teen idols",
  },
  {
    id: "harmony",
    label: "Sunshine, harmony & orchestral pop",
  },
  {
    id: "garage",
    label: "Garage, surf & psychedelic rock",
  },
  {
    id: "roots",
    label: "Roots, folk & country rock",
  },
  {
    id: "bluesrock",
    label: "Blues rock & Southern rock",
  },
  {
    id: "arena",
    label: "Classic, hard & arena rock",
  },
  {
    id: "glam",
    label: "Glam rock & theatrical rock",
  },
  {
    id: "artpop",
    label: "Art rock, eclectic & progressive pop",
  },
  {
    id: "powerpop",
    label: "Power pop & melodic guitar pop",
  },
  {
    id: "soft",
    label: "Soft rock & adult contemporary",
  },
  {
    id: "songwriter",
    label: "Singer-songwriters & piano pop",
  },
  {
    id: "newwave",
    label: "New wave, post-punk & ska-pop",
  },
  {
    id: "synth",
    label: "Synth-pop & New Romantic",
  },
  {
    id: "mainstream",
    label: "Mainstream, dance & teen pop",
  },
  {
    id: "unassigned",
    label: "Genre not assigned",
  },
] as const;

export const ROCK_POP_ERAS = [
  {
    id: "before1955",
    label: "Before 1955",
  },
  {
    id: "1955",
    label: "1955–1962",
  },
  {
    id: "1963",
    label: "1963–1969",
  },
  {
    id: "1970",
    label: "1970s",
  },
  {
    id: "1980",
    label: "1980s",
  },
  {
    id: "1990",
    label: "1990s",
  },
  {
    id: "unassigned",
    label: "Era not assigned",
  },
] as const;

export type RockPopGenre = (typeof ROCK_POP_GENRES)[number]["id"];
export type RockPopEra = (typeof ROCK_POP_ERAS)[number]["id"];
export type RockPopProfile = {
  genre: RockPopGenre;
  era: RockPopEra;
  tags: string[];
};

const assignments: {
  genre: RockPopGenre;
  era: RockPopEra;
  artists: string[];
}[] = [
  {
    genre: "traditional",
    era: "before1955",
    artists: [
      "Al Martino",
      "Alma Cogan",
      "Crosby Bing",
      "Doris Day",
      "Frank Sinatra",
      "Martin Dean",
      "Perry Como",
      "Sammy Davis, Jr.",
      "Vera Lynn",
    ],
  },
  {
    genre: "traditional",
    era: "1955",
    artists: [
      "Barbra Streisand",
      "Bobby Darin",
      "Johnny Mathis",
      "Pat Boone",
      "Shirley Bassey",
      "Tommy Edwards",
    ],
  },
  {
    genre: "traditional",
    era: "1963",
    artists: [
      "Andy Williams",
      "Humperdinck Engelbert",
      "Jack Jones",
      "Richard Harris",
      "Tom Jones",
    ],
  },
  {
    genre: "traditional",
    era: "1970",
    artists: ["Bette Midler"],
  },
  {
    genre: "rockabilly",
    era: "1955",
    artists: [
      "Bill Haley & His Comets",
      "Buddy Holly",
      "Carl Perkins",
      "Chuck Berry",
      'Clarence "Frogman" Henry',
      "Crickets",
      "Eddie Cochran",
      "Eddy Duane",
      "Elvis Presley",
      "Fats Domino",
      "Freddy Cannon",
      "Gene Vincent",
      "Jerry Lee Lewis",
      "Jody Reynolds",
      "Johnny & The Hurricanes",
      "Little Richard",
      "Mickey & Sylvia",
      "The Everly Brothers",
      "Valens Ritchie",
      "Wilbert Harrison",
    ],
  },
  {
    genre: "rockabilly",
    era: "1963",
    artists: ["Johnny Rivers"],
  },
  {
    genre: "rockabilly",
    era: "1970",
    artists: ["Darts", "Showaddywaddy"],
  },
  {
    genre: "rockabilly",
    era: "1980",
    artists: ["Stevens Shakin  ", "Stray Cats", "The Honeydrippers"],
  },
  {
    genre: "rockabilly",
    era: "1990",
    artists: ["Chris Isaak"],
  },
  {
    genre: "vocal",
    era: "before1955",
    artists: ["The Four Aces", "The Ink Spots", "The McGuire Sisters"],
  },
  {
    genre: "vocal",
    era: "1955",
    artists: [
      "Coasters",
      "Crests",
      "Curtis Lee",
      "Danny & The Juniors",
      "Edsels",
      "Shep & The Limelites",
      "The Blue Diamonds",
      "The Chordettes",
      "The Five Satins",
      "The Four Preps",
      "The Marcels",
      "The Platters",
    ],
  },
  {
    genre: "vocal",
    era: "1963",
    artists: [
      "Crystals",
      "Ruby & The Romantics",
      "The Chiffons",
      "The Four Seasons",
      "The Happenings",
      "The Righteous Brothers",
      "The Ronettes",
      "The Shangri-Las",
    ],
  },
  {
    genre: "vocal",
    era: "1980",
    artists: ["The Flying Pickets"],
  },
  {
    genre: "earlypop",
    era: "1955",
    artists: [
      "Billy Fury",
      "Bobby Rydell",
      "Bobby Vee",
      "Brian Hyland",
      "Bruce Channel",
      "Buzz Clifford",
      "Checker Chubby",
      "Chris Montez",
      "Connie Francis",
      "Del Shannon",
      "Dion",
      "Frankie Avalon",
      "Gene Pitney",
      "Joey Dee",
      "Little Eva",
      "Neil Sedaka",
      "Paul Anka",
      "Ricky Nelson",
      "Roy Orbison",
      "Shelley Fabares",
    ],
  },
  {
    genre: "earlypop",
    era: "1963",
    artists: [
      "Bobby Goldsboro",
      "Bobby Vinton",
      "Chris Andrews",
      "Christie Lou",
      "Cilla Black",
      "Cliff Richard",
      "Gary Lewis",
      "Jackie DeShannon",
      "Jay & The Americans",
      "Lesley Gore",
      "Lulu",
      "Mel Carter",
      "Nancy Sinatra",
      "Petula Clark",
      "Ronnie Spector",
      "Sandie Shaw",
      "Terry Stafford",
      "Tommy James",
    ],
  },
  {
    genre: "arena",
    era: "1963",
    artists: [
      "Equals",
      "Freddie & The Dreamers",
      "Georgie Fame",
      "Gerry & The Pacemakers",
      "Herman's Hermits",
      "Manfred Mann",
      "Nashville Teens",
      "Small Faces",
      "The Animals",
      "The Beatles",
      "The Beau Brummels",
      "The Dave Clark Five",
      "The Easybeats",
      "The Hollies",
      "The Kinks",
      "The Mindbenders",
      "The Rolling Stones",
      "The Searchers",
      "The Spencer Davis Group",
      "The Swinging Blue Jeans",
      "The Tremeloes",
      "The Yardbirds",
      "The Zombies",
      "Them",
    ],
  },
  {
    genre: "harmony",
    era: "1963",
    artists: [
      "Cascades",
      "Classics IV",
      "Fifth Dimension",
      "Fortunes",
      "Friend & Lover",
      "Gary Puckett",
      "Jan & Dean",
      "Love Affair",
      "Mary Hopkins",
      "Sonny & Cher",
      "Spanky & Our Gang",
      "The Association",
      "The Beach Boys",
      "The Box Tops",
      "The Buckinghams",
      "The Cowsills",
      "The Cyrkle",
      "The Grass Roots",
      "The Left Banke",
      "The Lovin' Spoonful",
      "The Mamas & The Papas",
      "The Monkees",
      "The New Colony Six",
      "The Rascals",
      "The Walker Brothers",
      "Turtles",
    ],
  },
  {
    genre: "harmony",
    era: "1970",
    artists: [
      "Bobby Bloom",
      "DaWN",
      "First Class",
      "Starland Vocal Band",
      "The New Seekers",
      "The Partridge Family",
      "The Rubettes",
      "Tony Orlando",
    ],
  },
  {
    genre: "harmony",
    era: "1980",
    artists: ["Brian Wilson"],
  },
  {
    genre: "garage",
    era: "1955",
    artists: ["Champs", 'Dave "Baby" Cortez'],
  },
  {
    genre: "garage",
    era: "1963",
    artists: [
      "Cannibal & The Headhunters",
      "Iron Butterfly",
      "It's a Beautiful Day",
      "Jefferson Airplane",
      "Jimi Hendrix",
      "Jimmy Gilmer",
      "John Fred",
      "Kingsmen",
      "Paul Revere and The Raiders",
      "Sam the Sham & The Pharaohs",
      "Spirit",
      "Steppenwolf",
      "Strawberry Alarm Clock",
      "Swingin' Medallions",
      "The Doors",
      "The Lemon Pipers",
      "The McCoys",
      "The Rivieras",
      "The Standells",
      "The Surfaris",
      "The Syndicate of Sound",
      "The Troggs",
      "The Youngbloods",
      "Vanilla Fudge",
    ],
  },
  {
    genre: "garage",
    era: "1970",
    artists: [
      "Blues Image",
      "Greenbaum Norman",
      "Jaggerz",
      "Norman Greenbaum",
      "Rare Earth",
      "Redbone",
      "Shocking Blue",
      "Steam",
      "Sugarloaf",
    ],
  },
  {
    genre: "roots",
    era: "1963",
    artists: [
      "Creedence Clearwater Revival",
      "Grateful Dead",
      "Joe South",
      "Nomadi",
    ],
  },
  {
    genre: "roots",
    era: "1970",
    artists: [
      "America",
      "Billy Swan",
      "Christie",
      "Dave Mason",
      "Dire Straits",
      "Dr. Hook",
      "EXILE",
      "Eagles",
      "Firefall",
      "Five Man Electrical Band",
      "Mungo Jerry",
      "Stampeders",
      "The Doobie Brothers",
      "Tom Petty",
      "Tom Petty and The Heartbreakers",
      "Walter Egan",
    ],
  },
  {
    genre: "roots",
    era: "1980",
    artists: [
      "Bruce Springsteen",
      "Don Henley",
      "Fairground Attraction",
      "Glenn Frey",
      "John Fogerty",
      "John Mellencamp",
      "The Hooters",
      "Traveling Wilburys",
    ],
  },
  {
    genre: "roots",
    era: "1990",
    artists: ["Eagle-Eye Cherry", "Texas", "The Kelly Family"],
  },
  {
    genre: "roots",
    era: "1963",
    artists: ["Van Morrison"],
  },
  {
    genre: "bluesrock",
    era: "1963",
    artists: ["Cream", "Janis Joplin", "Jeff Beck", "Mitch Ryder"],
  },
  {
    genre: "bluesrock",
    era: "1970",
    artists: [
      "Atlanta Rhythm Section",
      "Brownsville Station",
      "Edgar Winter",
      "Free",
      "Grand Funk Railroad",
      "Joe Cocker",
      "Lynyrd Skynyrd",
      "Ram Jam",
      "Rick Derringer",
      "The Allman Brothers Band",
      "The J. Geils Band",
      "Wet Willie",
    ],
  },
  {
    genre: "bluesrock",
    era: "1980",
    artists: ["The Blues Brothers"],
  },
  {
    genre: "arena",
    era: "1963",
    artists: ["The Who"],
  },
  {
    genre: "arena",
    era: "1970",
    artists: [
      "Bachman-Turner Overdrive",
      "Bad Company",
      "Bob Seger",
      "Boston",
      "Foreigner",
      "Golden Earring",
      "Guess Who",
      "Heart",
      "Jefferson Starship",
      "Joe Walsh",
      "Journey",
      "Peter Frampton",
      "Queen",
      "REO Speedwagon",
      "Status Quo",
      "Steve Miller Band",
      "The Babys",
    ],
  },
  {
    genre: "arena",
    era: "1980",
    artists: [
      "Bad English",
      "Bryan Adams",
      "Eddie Money",
      "Eric Johnson",
      "Far Corporation",
      "Jimmy Barnes",
      "Joe Satriani",
      "John Farnham",
      "John Waite",
      "Loverboy",
      "Michael Stanley Band",
      "Mike Reno",
      "Opus",
      "Pat Benatar",
      "Sheriff",
      "Starship",
      "Steve Perry",
      "Survivor",
      "Toto",
      "U2",
      "Vasco Rossi",
    ],
  },
  {
    genre: "arena",
    era: "1990",
    artists: ["Brian May", "dc Talk"],
  },
  {
    genre: "glam",
    era: "1970",
    artists: [
      "Alvin Stardust",
      "David Bowie",
      "David Essex",
      "Gary Glitter",
      "Meat Loaf",
      "Mott The Hoople",
      "Mud",
      "Nick Gilder",
      "Suzi Quatro",
      "Sweet",
      "T. Rex",
    ],
  },
  {
    genre: "glam",
    era: "1980",
    artists: ["Freddie Mercury"],
  },
  {
    genre: "artpop",
    era: "1963",
    artists: ["Blood, Sweat & Tears"],
  },
  {
    genre: "artpop",
    era: "1970",
    artists: [
      "10cc",
      "Gary Wright",
      "Genesis",
      "Gino Vannelli",
      "John Miles",
      "LightHouse",
      "Pooh",
      "Sailor",
      "Sparks",
      "Steely Dan",
    ],
  },
  {
    genre: "artpop",
    era: "1980",
    artists: [
      "David A. Stewart",
      "David Byrne",
      "Kate Bush",
      "Lindsey Buckingham",
      "Scritti Politti",
      "Steve Winwood",
      "Sting",
      "Tears for Fears",
      "Thomas Dolby",
    ],
  },
  {
    genre: "artpop",
    era: "1990",
    artists: ["Babylon Zoo"],
  },
  {
    genre: "powerpop",
    era: "1963",
    artists: ["Los Bravos"],
  },
  {
    genre: "powerpop",
    era: "1970",
    artists: [
      "Bay City Rollers",
      "Cheap Trick",
      "Eric Carmen",
      "Stories",
      "The Cars",
      "The Knack",
      "The Raspberries",
    ],
  },
  {
    genre: "powerpop",
    era: "1980",
    artists: [
      "Crowded House",
      "Feargal Sharkey",
      "Greg Kihn",
      "Joan Jett",
      "Katrina and the Waves",
      "Rick Springfield",
      "Squeeze",
      "The Bangles",
      "The Bluebells",
      "The Go-Go's",
      "The Outfield",
      "The Romantics",
    ],
  },
  {
    genre: "powerpop",
    era: "1990",
    artists: ["BBMak", "Fool's Garden", "Hanson", "Rembrandts", "Tal Bachman"],
  },
  {
    genre: "soft",
    era: "1963",
    artists: ["Bill Medley", "CHRISTIE,TONY", "Robert Knight"],
  },
  {
    genre: "soft",
    era: "1970",
    artists: [
      "Ace",
      "Air Supply",
      "Andrew Gold",
      "Barry & Eileen",
      "Barry Manilow",
      "Bob Welch",
      "Bread",
      "Carpenters",
      "Chicago",
      "Climax",
      "Clout",
      "Dan Hill",
      "David Gates",
      "Demis Roussos",
      "Elkie Brooks",
      "England Dan",
      "Fleetwood Mac",
      "Frankie Valli",
      "Gallery",
      "Hall & Oates",
      "Helen Reddy",
      "Jigsaw",
      "Kenny Loggins",
      "Kiki Dee",
      "King Harvest",
      "Little River Band",
      "Lobo",
      "Looking Glass",
      "Melissa Manchester",
      "Michael Johnson",
      "Morris Albert",
      "Orleans",
      "Paul Davis",
      "Player",
      "Randy VanWarmer",
      "Rita Coolidge",
      "Robert John",
      "Rod Stewart",
      "Smokie",
      "Stephen Bishop",
      "Three Dog Night",
      "Yvonne Elliman",
    ],
  },
  {
    genre: "soft",
    era: "1980",
    artists: [
      "Basia",
      "Bertie Higgins",
      "Bonnie Tyler",
      "Breathe",
      "Chris Norman",
      "Chris Rea",
      "Chris de Burgh",
      "Christopher Cross",
      "Diamond Jim",
      "Double",
      "Glenn Medeiros",
      "Go West",
      "Hue & Cry",
      "Jennifer Rush",
      "Jennifer Warnes",
      "Johnny Hates Jazz",
      "Johnny Logan",
      "Kim Carnes",
      "Lionel Richie",
      "Michael Bolton",
      "Michael English",
      "Mike + The Mechanics",
      "Mixed Emotions",
      "Paul Young",
      "Peter Cetera",
      "Phil Collins",
      "Richard Marx",
      "Richard Sanderson",
      "Robin Beck",
      "Sam Brown",
      "Stevie Nicks",
      "The Christians",
      "Wet Wet Wet",
      "Whitney Houston",
      "Will to Power",
    ],
  },
  {
    genre: "soft",
    era: "1990",
    artists: [
      "Billie Myers",
      "Bob Carlisle",
      "Celine Dion",
      "Curtis Stigers",
      "Enya",
      "Jann Arden",
      "Joan Osborne",
      "Michael Learns to Rock",
      "Niamh Kavanagh",
      "Ronan Keating",
      "Tasmin Archer",
      "The Corrs",
      "Vanessa Williams",
      "Wilson Phillips",
    ],
  },
  {
    genre: "songwriter",
    era: "1963",
    artists: ["Barry Mann"],
  },
  {
    genre: "songwriter",
    era: "1970",
    artists: [
      "Albert Hammond",
      "Billy Joel",
      "Elton John",
      "George Harrison",
      "Gerry Rafferty",
      "Gilbert O'Sullivan",
      "Harry Nilsson",
      "John Denver",
      "John Lennon",
      "Leo Sayer",
      "Neil Diamond",
      "Paul McCartney",
      "Peter Allen",
      "Ringo Starr",
      "Rupert Holmes",
      "Terry Jacks",
      "Wings",
    ],
  },
  {
    genre: "songwriter",
    era: "1980",
    artists: [
      "Bruce Hornsby & The Range",
      "Jimmy Nail",
      "Julian Lennon",
      "Michael Penn",
    ],
  },
  {
    genre: "songwriter",
    era: "1990",
    artists: [
      "Joshua Kadison",
      "Maria McKee",
      "Paula Cole",
      "Sophie B. Hawkins",
    ],
  },
  {
    genre: "songwriter",
    era: "1963",
    artists: ["Ray Davies"],
  },
  {
    genre: "newwave",
    era: "1970",
    artists: [
      "Blondie",
      "Boomtown Rats",
      "Mink DeVille",
      "Sniff 'n' the Tears",
      "The Police",
    ],
  },
  {
    genre: "newwave",
    era: "1980",
    artists: [
      "Bad Manners",
      "Billy Idol",
      "Culture Club",
      "Deacon Blue",
      "Dexys Midnight Runners",
      "Divinyls",
      "Duran Duran",
      "Fine Young Cannibals",
      "Huey Lewis & The News",
      "INXS",
      "Joe Jackson",
      "Madness",
      "Men at Work",
      "Motels",
      "Nick Kamen",
      "Quarterflash",
      "Robert Palmer",
      "Simple Minds",
      "The Escape Club",
      "The Fixx",
      "The Vapors",
      "Time Bandits",
    ],
  },
  {
    genre: "newwave",
    era: "1990",
    artists: ["Edwyn Collins"],
  },
  {
    genre: "synth",
    era: "1970",
    artists: ["Buggles", "M"],
  },
  {
    genre: "synth",
    era: "1980",
    artists: [
      "ABC",
      "Alison Moyet",
      "Alphaville",
      "Animotion",
      "Berlin",
      "Black",
      "Blue System",
      "Boy George",
      "Cock Robin",
      "Communards",
      "Corey Hart",
      "Cutting Crew",
      "Eurythmics",
      "Howard Jones",
      "Jimmy Somerville",
      "Korgis",
      "Laid Back",
      "Level 42",
      "Limahl",
      "Marc Almond",
      "Men Without Hats",
      "Mr. Mister",
      "Naked Eyes",
      "Nik Kershaw",
      "Orchestral Manoeuvres in the Dark",
      "Pseudo Echo",
      "Real Life",
      "Spandau Ballet",
      "The Style Council",
      "Thompson Twins",
      "Ultravox",
      "Wang Chung",
      "Wax",
      "a-ha",
    ],
  },
  {
    genre: "synth",
    era: "1990",
    artists: ["Chyp-notic", "Londonbeat", "White Town"],
  },
  {
    genre: "mainstream",
    era: "1963",
    artists: [
      "1910 Fruitgum Company",
      "New Vaudeville Band",
      "Ohio Express",
      "Tommy Roe",
    ],
  },
  {
    genre: "mainstream",
    era: "1970",
    artists: [
      "ABBA",
      "Andy Kim",
      "Arabesque",
      "Baccara",
      "Bee Gees",
      "Brotherhood of Man",
      "Cher",
      "Cheryl Ladd",
      "Dan Hartman",
      "Daniel Boone",
      "David Dundas",
      "Debby Boone",
      "Dizzy Man's Band",
      "Donny Osmond",
      "Edison Lighthouse",
      "George Baker Selection",
      "Guys 'n' Dolls",
      "Harpo",
      "John Paul Young",
      "Johnny Nash",
      "Leif Garrett",
      "Lucio Battisti",
      "Middle of the Road",
      "Nick MacKenzie",
      "Olivia Newton-John",
      "Ottawan",
      "Patrick Hernandez",
      "Santa Esmeralda",
      "Shaun Cassidy",
      "Typically Tropical",
      "Vicki Sue Robinson",
      "Walter Murphy",
    ],
  },
  {
    genre: "mainstream",
    era: "1980",
    artists: [
      "Amy Grant",
      "Bad Boys Blue",
      "Bananarama",
      "Band Aid",
      "Belinda Carlisle",
      "Boys Town Gang",
      "Bros",
      "Cathy Dennis",
      "Club Nouveau",
      "Cyndi Lauper",
      "Debbie Gibson",
      "Don Johnson",
      "Fancy",
      "George Michael",
      "Hasselhoff David",
      "Irene Cara",
      "Jane Child",
      "Jason Donovan",
      "Jive Bunny",
      "Kevin Paige",
      "Kim Wilde",
      "Kylie Minogue",
      "Laura Branigan",
      "Madonna",
      "Martika",
      "Matthew Wilder",
      "Michael Damian",
      "Michael Sembello",
      "Milli Vanilli",
      "New Kids on the Block",
      "Nick Berry",
      "Patrick Swayze",
      "Paula Abdul",
      "Peter Kent",
      "Rick Astley",
      "Roxette",
      "Ryan Paris",
      "Sheena Easton",
      "Sonia",
      "Stevie B",
      "T'Pau",
      "Taco",
      "Taylor Dayne",
      "The Cover Girls",
      "The Weather Girls",
      "Tiffany",
      "Toni Basil",
      "Tracey Ullman",
      "Twila Paris",
      "U.S.A. for Africa",
      "Wham!",
    ],
  },
  {
    genre: "mainstream",
    era: "1990",
    artists: [
      "911",
      "98 Degrees",
      "A*Teens",
      "Ace of Base",
      "Alannah Myles",
      "All Saints",
      "Annie Lennox",
      "Another Level",
      "Atomic Kitten",
      "B*Witched",
      "Backstreet Boys",
      "Barlow Gary",
      "Boyzone",
      "Britney Spears",
      "Caught in the Act",
      "Chesney Hawkes",
      "Christina Aguilera",
      "Dannii Minogue",
      "East 17",
      "Geri Halliwell",
      "Jennifer Lopez",
      "Jeremy Jackson",
      "Jessica Simpson",
      "Kim Appleby",
      "LEN",
      "LFO",
      "M2M",
      "MN8",
      "Mandy Moore",
      "Mel C",
      "Nicki French",
      "No Mercy",
      "OMC",
      "Peter Andre",
      "Right Said Fred",
      "Robbie Williams",
      "Robyn",
      "Savage Garden",
      "Spice Girls",
      "Take That",
      "Undercover",
      "Westlife",
      "Worlds Apart",
    ],
  },
  {
    genre: "mainstream",
    era: "1990",
    artists: ["Anastacia"],
  },
];

const artistTags: Record<string, string[]> = {
  ABBA: ["Europop", "disco", "Sweden"],
  "The Beatles": ["psychedelic", "pop rock", "UK"],
  Queen: ["glam", "theatrical", "UK"],
  "Fleetwood Mac": ["classic rock", "UK/US"],
  "Bee Gees": ["disco", "soft rock", "UK/Australia"],
  "David Bowie": ["art rock", "new wave", "UK"],
  "Hall & Oates": ["blue-eyed soul", "pop rock"],
  "Steely Dan": ["jazz rock", "soft rock"],
  U2: ["alternative rock", "Ireland"],
  "The Corrs": ["folk pop", "Ireland"],
  Roxette: ["pop rock", "Sweden"],
  Genesis: ["progressive rock", "UK"],
  Pooh: ["Italian", "pop rock", "progressive pop"],
  Enya: ["new age", "Celtic", "pop", "Ireland"],
  "Lucio Battisti": ["Italian", "pop rock"],
  "Vasco Rossi": ["Italian", "rock"],
  Nomadi: ["Italian", "pop rock"],
};

const profiles = new Map<string, RockPopProfile>();
assignments.forEach(({ genre, era, artists }) =>
  artists.forEach((name) => {
    const canonical = canonicalArtistName(name).trim();
    profiles.set(canonical, { genre, era, tags: artistTags[canonical] || [] });
  }),
);

export function rockPopProfile(name: string): RockPopProfile {
  return (
    profiles.get(canonicalArtistName(name).trim()) || {
      genre: "unassigned",
      era: "unassigned",
      tags: [],
    }
  );
}
