export default {
  ja: {
    "app-intro": "オープンソースのオンラインMIDIエディタ",
    "app-desc": "何もインストールせずに作曲を始めよう",
    launch: "起動",
    platform:
      "対応ブラウザ (デスクトップ版のみ): Google Chrome / Firefox / Safari",
    features: "機能",
    "midi-file": "MIDIファイルの読み込み、保存",
    "gm-module": "GM互換音源搭載",
    "piano-roll": "ピアノロールエディタ",
    "multi-track": "複数トラック対応",
    "control-editing": "ベロシティ・ピッチベンド編集",
    "tempo-track": "テンポトラック",
    "time-signature": "4/4以外の拍子に対応 (表示のみ)",
    support: "サポート",
    "support-intro":
      "signalは個人的に趣味で作っているアプリです。不具合があるかと思いますがご了承ください。もしブラウザで動作する軽量な作曲ソフトというコンセプトに共感してもらえたら、ぜひご支援ください。バグ報告や他人へのオススメ、スポンサーをしていただけると嬉しいです。",
    "report-bugs": "GitHubで不具合を報告",
    "request-features": "GitHubで機能要望を送る",
    sponsor: "スポンサーになって支援する",
    "follow-twitter": "Twitterで更新情報を確認する",
    file: "ファイル",
    "new-song": "新規作成",
    "open-song": "開く",
    "save-song": "保存",
    tracks: "トラック",
    "add-track": "トラックを追加",
    categories: "カテゴリ",
    instruments: "楽器",
    "rhythm-track": "リズムトラック",
    cancel: "キャンセル",
    ok: "OK",
    triplet: "三連符",
    dotted: "付点",
    "confirm-new": "編集中の楽曲が破棄されます。本当に新規作成しますか？",
    "confirm-close": "編集中の楽曲が破棄されます。本当にページを閉じますか？",
    "auto-scroll": "自動でスクロール",
    help: "ヘルプ",
    close: "閉じる",
    "keyboard-shortcut": "キーボードショートカット",
    "play-stop": "再生・停止",
    "pencil-tool": "鉛筆ツール",
    "selection-tool": "選択ツール",
    "copy-selection": "選択範囲をコピー",
    "cut-selection": "選択範囲を切り取り",
    "paste-selection": "コピーした選択範囲を現在位置に貼り付け",
    "delete-selection": "選択範囲を削除",
    "move-selection": "選択範囲を移動",
    undo: "元に戻す",
    redo: "やり直し",
    "select-note": "ノートを選択",
    "scroll-horizontally": "左右にスクロール",
    "scroll-vertically": "上下にスクロール",
    "midi-settings": "MIDI設定",
    inputs: "入力",
    outputs: "出力",
  },
} as { [key: string]: { [key: string]: string } }
