export default {
  ja: {
    "app-intro": "オープンソースのオンラインMIDIエディタ",
    "app-desc": "何もインストールせずに作曲を始めよう",
    launch: "起動",
    platform:
      "対応ブラウザ (デスクトップ版のみ): Google Chrome / Firefox / Safari",
    features: "機能",
    "feature-midi-file": "フル機能のMIDIエディター",
    "feature-midi-file-description":
      "複数トラックに対応したピアノロールエディタを使って、自在に作曲しましょう。もちろんベロシティやピッチベンド、エクスプレッション、モジュレーションを使った豊かな表現ができます。",
    "feature-gm-module": "GM互換音源搭載",
    "feature-gm-module-description":
      "WebAudio APIとAudioWorkletで作られた専用の音源モジュールにより、ブラウザ上で大量のMIDIノートを鳴らすことが可能になりました。",
    "piano-roll": "ピアノロール",
    tempo: "テンポ",
    "tempo-track": "テンポトラック",
    "feature-time-signature": "4/4以外の拍子・テンポチェンジに対応",
    "feature-time-signature-description":
      "グラフエディタを使って、曲の途中でテンポや拍子を自由に変えることができます。",
    "feature-pwa": "PWA対応",
    "feature-pwa-description":
      "アドレスバーが邪魔ですか？アプリとしてインストールすることができます。",
    "feature-export-wav": "WAVファイルへの書き出し",
    "feature-midi-io": "MIDI入出力",
    "feature-midi-io-description":
      "Web MIDI APIに対応したブラウザでは、MIDIキーボードを接続して演奏を録音したり、ハードウェアシンセで音を鳴らしたりすることができます。",
    "feature-export-audio": "高速オーディオ書き出し機能",
    "feature-export-audio-description":
      "作った曲をWAVファイルに書き出して、スマートフォンで聴いたり動画のBGMに使ったり、DAWに取り込んだりすることができます。",
    "time-signature": "拍子",
    "add-time-signature": "拍子を追加",
    "remove-time-signature": "拍子を削除",
    support: "サポート",
    "sponsor-intro":
      "signalは週末に趣味で作っているアプリです。もしブラウザで動作する軽量な作曲ソフトというコンセプトに共感してもらえたら、ぜひご支援ください。",
    "support-github-desctiption": "GitHubで不具合報告や要望を送る",
    "become-sponsor": "スポンサーになりませんか？",
    "open-github-sponsors": "GitHub Sponsorsを開く",
    "follow-twitter": "Twitterで更新情報を確認する",
    file: "ファイル",
    "new-song": "新規作成",
    "open-song": "開く",
    "save-song": "保存",
    track: "トラック",
    tracks: "トラック",
    "add-track": "トラックを追加",
    "delete-track": "トラックを削除",
    "duplicate-track": "トラックを複製",
    channel: "チャンネル",
    categories: "カテゴリ",
    instruments: "楽器",
    "rhythm-track": "リズムトラック",
    "conductor-track": "コンダクタートラック",
    "track-name": "トラック名",
    cancel: "キャンセル",
    ok: "OK",
    triplet: "三連符",
    dotted: "付点",
    "confirm-new": "編集中の楽曲が破棄されます。本当に新規作成しますか？",
    "confirm-close": "編集中の楽曲が破棄されます。本当にページを閉じますか？",
    "auto-scroll": "自動でスクロール",
    help: "ヘルプ",
    close: "閉じる",
    "keyboard-shortcut": "キーボードショートカット",
    "play-pause": "再生・一時停止",
    rewind: "巻戻し",
    "fast-forward": "早送り",
    stop: "停止",
    record: "録音",
    "pencil-tool": "鉛筆ツール",
    "selection-tool": "選択ツール",
    "copy-selection": "選択範囲をコピー",
    "cut-selection": "選択範囲を切り取り",
    "paste-selection": "コピーした選択範囲を現在位置に貼り付け",
    "delete-selection": "選択範囲を削除",
    "move-selection": "選択範囲を移動",
    undo: "元に戻す",
    redo: "やり直し",
    cut: "切り取り",
    copy: "コピー",
    paste: "ペースト",
    duplicate: "複製",
    delete: "削除",
    "select-note": "ノートを選択",
    "scroll-horizontally": "左右にスクロール",
    "scroll-vertically": "上下にスクロール",
    settings: "設定",
    "midi-settings": "MIDI設定",
    inputs: "入力",
    outputs: "出力",
    "one-octave-up": "+1オクターブ",
    "one-octave-down": "-1オクターブ",
    arrange: "アレンジ",
    "arrangement-view": "アレンジビュー",
    "open-help": "ヘルプを開く",
    "event-list": "イベントリスト",
    "open-chat": "チャットを開く",
    property: "プロパティ",
    quantize: "クオンタイズ",
    "snap-to-grid": "グリッドにスナップ",
    "export-audio": "オーディオ書き出し",
    export: "書き出し",
    "exporting-audio": "オーディオを書き出し中...",
    "file-type": "ファイル形式",
    "export-error-too-short": "曲が短すぎます",
  },
} as { [key: string]: { [key: string]: string } }
