export default {
  ja: {
    "landing-title": "signal - オンラインMIDIシーケンサ",
    "app-intro": "ブラウザで音楽が作れる",
    "app-desc": "すぐに使えるMIDI編集フリーソフト",
    launch: "起動",
    platform:
      "対応ブラウザ (デスクトップ版のみ): Google Chrome / Firefox / Safari",
    features: "機能",
    "feature-midi-file": "フル機能のMIDIエディター",
    "feature-midi-file-description":
      "複数トラックに対応したピアノロールエディタを使って、自在に作曲しましょう。もちろんベロシティやピッチベンド、エクスプレッション、モジュレーションを使った豊かな表現ができます。",
    "feature-gm-module": "GM互換音源搭載",
    "feature-gm-module-description":
      "WebAudio APIとAudioWorkletで作られた専用の音源モジュールにより、ブラウザ上で大量のMIDIノートを鳴らすことが可能になりました。",
    "piano-roll": "ピアノロール",
    tempo: "テンポ",
    "tempo-track": "テンポトラック",
    "feature-time-signature": "4/4以外の拍子・テンポチェンジに対応",
    "feature-time-signature-description":
      "グラフエディタを使って、曲の途中でテンポや拍子を自由に変えることができます。",
    "feature-pwa": "PWA対応",
    "feature-pwa-description":
      "アドレスバーが邪魔ですか？アプリとしてインストールすることができます。",
    "feature-export-wav": "WAVファイルへの書き出し",
    "feature-midi-io": "MIDIキーボード対応",
    "feature-midi-io-description":
      "Web MIDI APIに対応したブラウザでは、MIDIキーボードを接続して演奏を録音したり、ハードウェアシンセで音を鳴らしたりすることができます。",
    "feature-export-audio": "高速オーディオ書き出し機能",
    "feature-export-audio-description":
      "作った曲をWAVファイルに書き出して、スマートフォンで聴いたり動画のBGMに使ったり、DAWに取り込んだりすることができます。",
    "time-signature": "拍子",
    "add-time-signature": "拍子を追加",
    "remove-time-signature": "拍子を削除",
    support: "サポート",
    "sponsor-intro":
      "signalは週末に趣味で作っているアプリです。もしブラウザで動作する軽量な作曲ソフトというコンセプトに共感してもらえたら、ぜひご支援ください。",
    "support-github-desctiption": "GitHubで不具合報告や要望を送る",
    "become-sponsor": "スポンサーになりませんか？",
    "open-github-sponsors": "GitHub Sponsorsを開く",
    "follow-twitter": "Twitterで更新情報を確認する",
    file: "ファイル",
    "new-song": "新規作成",
    "open-song": "開く",
    "save-song": "保存",
    "save-as": "名前を付けて保存",
    "song-created": "楽曲が作成されました",
    "song-saved": "楽曲が保存されました",
    "download-midi": "MIDIファイルをダウンロード",
    "untitled-song": "無題の楽曲",
    name: "名前",
    rename: "名前の変更",
    track: "トラック",
    tracks: "トラック",
    "add-track": "トラックを追加",
    "delete-track": "トラックを削除",
    "duplicate-track": "トラックを複製",
    channel: "チャンネル",
    categories: "カテゴリ",
    instruments: "楽器",
    "rhythm-track": "リズムトラック",
    "conductor-track": "コンダクタートラック",
    "track-name": "トラック名",
    cancel: "キャンセル",
    ok: "OK",
    reset: "リセット",
    triplet: "三連符",
    dotted: "付点",
    "confirm-new": "編集中の楽曲が破棄されます。本当に新規作成しますか？",
    "confirm-open": "編集中の楽曲が破棄されます。本当に開きますか？",
    "confirm-close": "編集中の楽曲が破棄されます。本当にページを閉じますか？",
    "auto-scroll": "自動でスクロール",
    help: "ヘルプ",
    close: "閉じる",
    "keyboard-shortcut": "キーボードショートカット",
    "play-pause": "再生・一時停止",
    rewind: "巻戻し",
    "fast-forward": "早送り",
    "forward-rewind": "早送り・巻き戻し",
    "next-previous-track": "次のトラック・前のトラック",
    "solo-mute-ghost": "ソロ・ミュート・ゴーストトラックの切り替え",
    stop: "停止",
    record: "録音",
    "pencil-tool": "鉛筆ツール",
    "selection-tool": "選択ツール",
    "copy-selection": "選択範囲をコピー",
    "cut-selection": "選択範囲を切り取り",
    "paste-selection": "コピーした選択範囲を現在位置に貼り付け",
    "select-all": "すべて選択",
    "delete-selection": "選択範囲を削除",
    "move-selection": "選択範囲を移動",
    undo: "元に戻す",
    redo: "やり直し",
    cut: "切り取り",
    copy: "コピー",
    paste: "ペースト",
    duplicate: "複製",
    delete: "削除",
    "song-deleted": "曲を削除しました",
    "song-delete-failed": "曲の削除に失敗しました",
    "select-note": "ノートを選択",
    "scroll-horizontally": "左右にスクロール",
    "scroll-vertically": "上下にスクロール",
    settings: "設定",
    "midi-settings": "MIDI設定",
    inputs: "入力",
    outputs: "出力",
    "no-inputs": "入力デバイスが見つかりません",
    "one-octave-up": "+1オクターブ",
    "one-octave-down": "-1オクターブ",
    arrange: "アレンジ",
    "arrangement-view": "アレンジビュー",
    "open-help": "ヘルプを開く",
    "event-list": "イベントリスト",
    "open-chat": "チャットを開く",
    property: "プロパティ",
    quantize: "クオンタイズ",
    "snap-to-grid": "グリッドにスナップ",
    "export-audio": "オーディオ書き出し",
    export: "書き出し",
    "exporting-audio": "オーディオを書き出し中...",
    "file-type": "ファイル形式",
    "export-error-too-short": "曲が短すぎます",
    "set-loop-start": "ループ開始位置を設定",
    "set-loop-end": "ループ終了位置を設定",
    "switch-tab": "タブを切り替え",
    transpose: "トランスポーズ",
    yes: "はい",
    no: "いいえ",
    "please-sign-up": "サインアップしてクラウドセーブを利用",
    "save-changes": "曲への変更を保存しますか?",
    "sign-in": "サインイン",
    "sign-out": "サインアウト",
    "success-sign-in": "サインインに成功しました",
    files: "ファイル",
    "created-date": "作成日時",
    "modified-date": "更新日時",
    "cloud-beta-warning":
      "クラウド機能は開発中のベータ版のため、大事な楽曲はこまめにダウンロードをお願いします。",
    "cloud-description":
      "サインインすることで楽曲をクラウドに保存し、いつでもどこからでも作曲を再開することができます。",
    "import-midi": "MIDI をインポート",
    "export-midi": "MIDI をエクスポート",
    general: "一般",
    "change-track-color": "トラックの色を変更",
    "control-settings": "コントロール設定",
    add: "追加",
    remove: "削除",
    "initialize-error": "起動時の処理でエラーが発生しました",
    "soundfont-save-notice": "サウンドフォントはブラウザー内に保存されます",
    "loading-external-midi": "外部のMIDIファイルを読み込み中...",
    initializing: "起動中...",
    profile: "プロフィール",
    "edit-profile": "プロフィールを編集",
    "signin-to-edit-profile":
      "プロフィールを編集するにはサインインしてください",
    "display-name": "表示名",
    bio: "自己紹介",
    save: "保存",
    "recent-tracks": "最近の曲",
    "publish-notice":
      "楽曲を公開すると他のユーザーがこの曲を聴くことができるようになります。",
    "published-notice": "この曲は公開されています。",
    publish: "公開",
    unpublish: "非公開",
    "publish-song": "曲を公開",
    "song-published": "曲を公開しました",
    "song-unpublished": "曲を非公開にしました",
    "share-my-song-text":
      "🎶 signalで新しいトラックを作成しました！🎹✨\nMIDIを聴いてください！🎧👇\n#midi #signalmidi @signalmidi",
    "publish-rules":
      "重要なお知らせ：当サイトでは、あなた自身が制作した楽曲のみの投稿を許可しています。著作権法に基づき、あなたが著作権者である、または明示的な許可を得た楽曲のみを投稿してください。他者の楽曲や、著作権で保護されている作品を無許可で公開することは、法的に禁止されています。このような違反が発見された場合、投稿は削除され、アカウントに対して制限が加えられる可能性があります。クリエイティブでオリジナルな作品を共有し、コミュニティの健全な成長にご協力ください。",
    "play-count": "回再生",
    "play-count-1": "回再生",
    /* MIDI Instrument Categories */
    Piano: "ピアノ",
    "Chromatic Percussion": "クロマチック",
    Organ: "オルガン",
    Guitar: "ギター",
    Bass: "ベース",
    Strings: "ストリングス",
    Ensemble: "アンサンブル",
    Brass: "ブラス",
    Reed: "リード",
    Pipe: "笛",
    "Synth Lead": "シンセリード",
    "Synth Pad": "シンセパッド",
    "Synth Effects": "シンセエフェクト",
    Ethnic: "民族楽器",
    Percussive: "打楽器",
    "Sound effects": "効果音",
    /* MIDI Instruments */
    "Acoustic Grand Piano": "アコースティックピアノ",
    "Bright Acoustic Piano": "ブライトピアノ",
    "Electric Grand Piano": "エレクトリック・グランドピアノ",
    "Honky-tonk Piano": "ホンキートンクピアノ",
    "Electric Piano 1": "エレクトリックピアノ",
    "Electric Piano 2": "FMエレクトリックピアノ",
    Harpsichord: "ハープシコード",
    Clavinet: "クラビネット",
    Celesta: "チェレスタ",
    Glockenspiel: "グロッケンシュピール",
    "Music Box": "オルゴール",
    Vibraphone: "ヴィブラフォン",
    Marimba: "マリンバ",
    Xylophone: "木琴",
    "Tubular Bells": "チューブラーベル",
    Dulcimer: "ダルシマー",
    "Drawbar Organ": "ドローバーオルガン",
    "Percussive Organ": "パーカッシブオルガン",
    "Rock Organ": "ロックオルガン",
    "Church Organ": "チャーチオルガン",
    "Reed Organ": "リードオルガン",
    Accordion: "アコーディオン",
    Harmonica: "ハーモニカ",
    "Tango Accordion": "タンゴアコーディオン",
    "Acoustic Guitar (nylon)": "アコースティックギター（ナイロン弦）",
    "Acoustic Guitar (steel)": "アコースティックギター（スチール弦）",
    "Electric Guitar (jazz)": "ジャズギター",
    "Electric Guitar (clean)": "クリーンギター",
    "Electric Guitar (muted)": "ミュートギター",
    "Overdriven Guitar": "オーバードライブギター",
    "Distortion Guitar": "ディストーションギター",
    "Guitar Harmonics": "ギターハーモニクス",
    "Acoustic Bass": "アコースティックベース",
    "Electric Bass (finger)": "フィンガーベース",
    "Electric Bass (pick)": "ピックベース",
    "Fretless Bass": "フレットレスベース",
    "Slap Bass 1": "スラップベース 1",
    "Slap Bass 2": "スラップベース 2",
    "Synth Bass 1": "シンセベース 1",
    "Synth Bass 2": "シンセベース 2",
    Violin: "ヴァイオリン",
    Viola: "ヴィオラ",
    Cello: "チェロ",
    Contrabass: "コントラバス",
    "Tremolo Strings": "トレモロストリングス",
    "Pizzicato Strings": "ピッツィカートストリングス",
    "Orchestral Harp": "ハープ",
    Timpani: "ティンパニ",
    "String Ensemble 1": "ストリングアンサンブル",
    "String Ensemble 2": "スローストリングアンサンブル",
    "Synth Strings 1": "シンセストリングス",
    "Synth Strings 2": "シンセストリングス2",
    "Choir Aahs": "声「アー」",
    "Voice Oohs": "声「ドゥー」",
    "Synth Choir": "シンセヴォイス",
    "Orchestra Hit": "オーケストラヒット",
    Trumpet: "トランペット",
    Trombone: "トロンボーン",
    Tuba: "チューバ",
    "Muted Trumpet": "ミュートトランペット",
    "French Horn": "フレンチ・ホルン",
    "Brass Section": "ブラスセクション",
    "Synth Brass 1": "シンセブラス 1",
    "Synth Brass 2": "シンセブラス 2",
    "Soprano Sax": "ソプラノサックス",
    "Alto Sax": "アルトサックス",
    "Tenor Sax": "テナーサックス",
    "Baritone Sax": "バリトンサックス",
    Oboe: "オーボエ",
    "English Horn": "イングリッシュホルン",
    Bassoon: "ファゴット",
    Clarinet: "クラリネット",
    Piccolo: "ピッコロ",
    Flute: "フルート",
    Recorder: "リコーダー",
    "Pan Flute": "パンフルート",
    "Blown Bottle": "ブロウンボトル",
    Shakuhachi: "尺八",
    Whistle: "口笛",
    Ocarina: "オカリナ",
    "Lead 1 (square)": "正方波",
    "Lead 2 (sawtooth)": "ノコギリ波",
    "Lead 3 (calliope)": "カリオペリード",
    "Lead 4 (chiff)": "チフリード",
    "Lead 5 (charang)": "チャランゴリード",
    "Lead 6 (voice)": "ボイスリード",
    "Lead 7 (fifths)": "フィフスズリード",
    "Lead 8 (bass + lead)": "ベース + リード",
    "Pad 1 (new age)": "ファンタジア",
    "Pad 2 (warm)": "ウォーム",
    "Pad 3 (polysynth)": "ポリシンセ",
    "Pad 4 (choir)": "クワイア",
    "Pad 5 (bowed)": "ボウ",
    "Pad 6 (metallic)": "メタリック",
    "Pad 7 (halo)": "ハロー",
    "Pad 8 (sweep)": "スウィープ",
    "FX 1 (rain)": "雨",
    "FX 2 (soundtrack)": "サウンドトラック",
    "FX 3 (crystal)": "クリスタル",
    "FX 4 (atmosphere)": "アトモスフィア",
    "FX 5 (brightness)": "ブライトネス",
    "FX 6 (goblins)": "ゴブリン",
    "FX 7 (echoes)": "エコー",
    "FX 8 (sci-fi)": "サイファイ",
    Sitar: "シタール",
    Banjo: "バンジョー",
    Shamisen: "三味線",
    Koto: "琴",
    Kalimba: "カリンバ",
    Bagpipe: "バグパイプ",
    Fiddle: "フィドル",
    Shanai: "シャハナーイ",
    "Tinkle Bell": "ティンクルベル",
    Agogo: "アゴゴ",
    "Steel Drums": "スチールドラム",
    Woodblock: "ウッドブロック",
    "Taiko Drum": "太鼓",
    "Melodic Tom": "メロディックタム",
    "Synth Drum": "シンセドラム",
    "Reverse Cymbal": "リバースシンバル",
    "Guitar Fret Noise": "ギターフレットノイズ",
    "Breath Noise": "ブレスノイズ",
    Seashore: "海岸",
    "Bird Tweet": "鳥のさえずり",
    "Telephone Ring": "電話のベル",
    Helicopter: "ヘリコプター",
    Applause: "拍手",
    Gunshot: "銃声",
  },
  "zh-Hans": {
    "landing-title": "signal - 在线 MIDI 编辑器",
    "app-intro": "在浏览器中编辑曲目",
    "app-desc": "无需安装任何东西即可开始创作曲目",
    launch: "开始",
    platform: "支持浏览器(仅限桌面版):Google Chrome / Firefox / Safari",
    features: "功能",
    "feature-midi-file": "全功能 MIDI 编辑器",
    "feature-midi-file-description":
      "使用多轨钢琴卷编辑器自由编排。您可以使用力度、弯音、情绪和调制等控制器来创作出富有表现力的曲目。",
    "feature-gm-module": "GM 兼容音源",
    "feature-gm-module-description":
      "快速加载 128 种虚拟乐器，同时使用 WebAudio API 和 AudioWorklet 构建的专用音频模块让您可以在浏览器中播放任何的音符。",
    "piano-roll": "钢琴卷",
    tempo: "速度",
    "tempo-track": "速度轨",
    "feature-time-signature": "支持除 4/4 以外的拍号和 300+ BPM",
    "feature-time-signature-description":
      "您可以使用可视化编辑器自由更改曲目中的速度和拍号。",
    "feature-pwa": "支持 PWA",
    "feature-pwa-description":
      "想要隐藏浏览器的地址栏？ 您可以将其安装在桌面上并将其用作应用程序使用。",
    "feature-export-wav": "导出为 WAV 文件",
    "feature-midi-io": "支持 MIDI 键盘",
    "feature-midi-io-description":
      "支持 Web MIDI API 的浏览器允许您连接 MIDI 键盘来录制您的演奏，并使用硬件合成器播放音频。",
    "feature-export-audio": "快速音频导出功能",
    "feature-export-audio-description":
      "您可以将创作的曲目导出为 WAV 文件并在智能手机上播放，将其用作视频的背景音乐，或将其导入 DAW。",
    "time-signature": "拍号",
    "add-time-signature": "添加拍号",
    "remove-time-signature": "删除拍号",
    support: "支持",
    "sponsor-intro":
      "signal 是我个人在周末构建的应用程序。如果您喜欢在浏览器中运行的轻量级合成软件，请支持我。",
    "support-github-desctiption": "在 GitHub 上提交 BUG 和 PR",
    "become-sponsor": "成为赞助商",
    "open-github-sponsors": "前往 GitHub Sponsors",
    "follow-twitter": "关注 Twitter 以获取更新",
    file: "文件",
    "new-song": "新建",
    "open-song": "打开",
    "save-song": "保存",
    "save-as": "另存为",
    "song-created": "曲目已创建",
    "song-saved": "曲目已保存",
    "untitled-song": "未命名",
    name: "名称",
    rename: "重命名",
    track: "音轨",
    "add-track": "添加音轨",
    "delete-track": "删除音轨",
    "duplicate-track": "复制音轨",
    channel: "频道",
    categories: "类别",
    instruments: "乐器",
    "rhythm-track": "节奏轨",
    "conductor-track": "指挥轨",
    "track-name": "音轨名",
    cancel: "取消",
    ok: "确定",
    triplet: "三连音",
    dotted: "附点",
    "confirm-new": "正在编辑曲目，您确定要新建一个吗？",
    "confirm-open": "正在编辑曲目，您确定要打开另一个吗？",
    "confirm-close": "正在编辑曲目，您确定要关闭吗？",
    "auto-scroll": "自动滚动",
    help: "帮助",
    close: "关闭",
    "keyboard-shortcut": "快捷键",
    "play-pause": "播放/暂停",
    rewind: "快退",
    "fast-forward": "快进",
    "forward-rewind": "快进/快退",
    "next-previous-track": "下一音轨/上一音轨",
    "solo-mute-ghost": "独奏/静音/幽灵音",
    stop: "停止",
    record: "录音",
    "pencil-tool": "铅笔工具",
    "selection-tool": "选择工具",
    "copy-selection": "拷贝选择的内容",
    "cut-selection": "剪切选择的内容",
    "paste-selection": "粘贴选择的内容",
    "select-all": "全选",
    "delete-selection": "删除选择的内容",
    "move-selection": "移动选择的内容",
    undo: "撤消",
    redo: "恢复",
    cut: "剪切",
    copy: "拷贝",
    paste: "粘贴",
    duplicate: "复制",
    delete: "删除",
    "select-note": "选择音符",
    "scroll-horizontally": "左右滚动",
    "scroll-vertically": "上下滚动",
    settings: "设置",
    "midi-settings": "MIDI设置",
    inputs: "输入",
    outputs: "输出",
    "one-octave-up": "+1 个八度",
    "one-octave-down": "-1 个八度",
    arrange: "编排",
    "arrangement-view": "编排视图",
    "open-help": "打开帮助",
    "event-list": "事件列表",
    "open-chat": "打开聊天框",
    property: "属性",
    quantize: "量化",
    "snap-to-grid": "对齐网格",
    "export-audio": "导出音频",
    export: "导出",
    "exporting-audio": "正在导出音频...",
    "file-type": "文件格式",
    "export-error-too-short": "这首曲目长度太短了",
    "set-loop-start": "设置循环开始位置",
    "set-loop-end": "设置循环结束位置",
    "switch-tab": "切换标签",
    transpose: "移调",
    yes: "是",
    no: "否",
    "please-sign-up": "注册来使用云存档",
    "save-changes": "是否要保存对曲目的更改？",
    "sign-in": "登录",
    "success-sign-in": "登录成功",
    files: "文件",
    "created-date": "创建日期",
    "modified-date": "修改日期",
    "cloud-beta-warning":
      "由于云功能处于开发阶段，请及时下载保存您创作的重要曲目。",
    "cloud-description":
      "通过登录，您可以将您的曲目保存到云端并随时随地恢复作曲。",
    "import-midi": "导入 MIDI",
    "export-midi": "导出 MIDI",
    "publish-rules":
      "重要通知：本网站只允许发布您自己创作的音乐作品。根据著作权法，请确保您是音乐作品的著作权持有人，或已获得明确许可。未经授权公开他人音乐或受著作权保护的作品是法律所禁止的。如果发现此类违规行为，您的帖子可能会被删除，且您的账户可能会受到限制。我们鼓励您分享创意和原创作品，共同促进我们社区的健康成长。",
    /* MIDI Instrument Categories */
    Piano: "钢琴",
    "Chromatic Percussion": "半音打击乐",
    Organ: "风琴",
    Guitar: "吉他",
    Bass: "贝司",
    Strings: "弦乐独奏",
    Ensemble: "合唱合奏",
    Brass: "铜管乐器",
    Reed: "哨片乐器",
    Pipe: "吹管乐器",
    "Synth Lead": "合成主音",
    "Synth Pad": "合成柔音",
    "Synth Effects": "合成特效",
    Ethnic: "民族乐器",
    Percussive: "打击乐",
    "Sound effects": "声音特效",
    /* MIDI Instruments */
    "Acoustic Grand Piano": "大钢琴",
    "Bright Acoustic Piano": "立式钢琴",
    "Electric Grand Piano": "电钢琴",
    "Honky-tonk Piano": "酒吧钢琴",
    "Electric Piano 1": "电钢琴1",
    "Electric Piano 2": "电钢琴2",
    Harpsichord: "拨弦古钢琴",
    Clavinet: "击弦古钢琴",
    Celesta: "钢片琴",
    Glockenspiel: "钟琴",
    "Music Box": "八音盒",
    Vibraphone: "电颤琴",
    Marimba: "马林巴",
    Xylophone: "木琴",
    "Tubular Bells": "管钟",
    Dulcimer: "扬琴",
    "Drawbar Organ": "击杆风琴",
    "Percussive Organ": "打击型风琴",
    "Rock Organ": "摇滚风琴",
    "Church Organ": "管风琴",
    "Reed Organ": "簧风琴",
    Accordion: "手风琴",
    Harmonica: "口琴",
    "Tango Accordion": "探戈手风琴",
    "Acoustic Guitar (nylon)": "尼龙弦吉他",
    "Acoustic Guitar (steel)": "钢弦吉他",
    "Electric Guitar (jazz)": "爵士乐电吉他",
    "Electric Guitar (clean)": "清音电吉他",
    "Electric Guitar (muted)": "弱音电吉他",
    "Overdriven Guitar": "驱动音效吉他",
    "Distortion Guitar": "失真音效吉他",
    "Guitar Harmonics": "吉他泛音",
    "Acoustic Bass": "原声贝司",
    "Electric Bass (finger)": "指拨电贝司",
    "Electric Bass (pick)": "拨片拨电贝司",
    "Fretless Bass": "无品贝司",
    "Slap Bass 1": "击弦贝司1",
    "Slap Bass 2": "击弦贝司2",
    "Synth Bass 1": "合成贝司1",
    "Synth Bass 2": "合成贝司2",
    Violin: "小提琴",
    Viola: "中提琴",
    Cello: "大提琴",
    Contrabass: "低音提琴",
    "Tremolo Strings": "弦乐震音",
    "Pizzicato Strings": "弦乐拨奏",
    "Orchestral Harp": "竖琴",
    Timpani: "定音鼓",
    "String Ensemble 1": "弦乐合奏1",
    "String Ensemble 2": "弦乐合奏2",
    "Synth Strings 1": "合成弦乐1",
    "Synth Strings 2": "合成弦乐2",
    "Choir Aahs": "合唱“啊”音",
    "Voice Oohs": "人声“嘟”音",
    "Synth Choir": "合成人声",
    "Orchestra Hit": "乐队打击乐",
    Trumpet: "小号",
    Trombone: "长号",
    Tuba: "大号",
    "Muted Trumpet": "弱音小号",
    "French Horn": "圆号",
    "Brass Section": "铜管组",
    "Synth Brass 1": "合成铜管1",
    "Synth Brass 2": "合成铜管2",
    "Soprano Sax": "高音萨克斯",
    "Alto Sax": "中音萨克斯",
    "Tenor Sax": "次中音萨克斯",
    "Baritone Sax": "上低音萨克斯",
    Oboe: "双簧管",
    "English Horn": "英国管",
    Bassoon: "大管",
    Clarinet: "单簧管",
    Piccolo: "短笛",
    Flute: "长笛",
    Recorder: "竖笛",
    "Pan Flute": "排笛",
    "Blown Bottle": "吹瓶口",
    Shakuhachi: "尺八",
    Whistle: "哨",
    Ocarina: "奥卡雷那",
    "Lead 1 (square)": "合成主音1（方波）",
    "Lead 2 (sawtooth)": "合成主音2（锯齿波）",
    "Lead 3 (calliope)": "合成主音3（汽笛风琴）",
    "Lead 4 (chiff)": "合成主音4 （吹管）",
    "Lead 5 (charang)": "合成主音5（吉他）",
    "Lead 6 (voice)": "合成主音6（人声）",
    "Lead 7 (fifths)": "合成主音7（五度）",
    "Lead 8 (bass + lead)": "合成主音8（贝斯加主音）",
    "Pad 1 (new age)": "合成柔音1（新时代）",
    "Pad 2 (warm)": "合成柔音（暖音）",
    "Pad 3 (polysynth)": "合成柔音3（复合成）",
    "Pad 4 (choir)": "合成柔音4（合唱）",
    "Pad 5 (bowed)": "合成柔音5（弓弦）",
    "Pad 6 (metallic)": "合成柔音6（金属）",
    "Pad 7 (halo)": "合成柔音7（光晕）",
    "Pad 8 (sweep)": "合成柔音8（扫弦）",
    "FX 1 (rain)": "合成特效1（雨）",
    "FX 2 (soundtrack)": "合成特效2（音轨）",
    "FX 3 (crystal)": "合成特效3（水晶）",
    "FX 4 (atmosphere)": "合成特效4（大气）",
    "FX 5 (brightness)": "合成特效5（轻柔）",
    "FX 6 (goblins)": "合成特效6（小妖）",
    "FX 7 (echoes)": "合成特效7（回声）",
    "FX 8 (sci-fi)": "合成特效8（科幻）",
    Sitar: "锡塔尔",
    Banjo: "班卓",
    Shamisen: "三味线",
    Koto: "筝",
    Kalimba: "卡林巴",
    Bagpipe: "风笛",
    Fiddle: "古提琴",
    Shanai: "唢呐",
    "Tinkle Bell": "铃铛",
    Agogo: "拉丁打铃",
    "Steel Drums": "钢鼓",
    Woodblock: "木块",
    "Taiko Drum": "太鼓",
    "Melodic Tom": "嗵鼓",
    "Synth Drum": "合成鼓",
    "Reverse Cymbal": "铜钹",
    "Guitar Fret Noise": "磨弦声",
    "Breath Noise": "呼吸声",
    Seashore: "海浪声",
    "Bird Tweet": "鸟鸣声",
    "Telephone Ring": "电话声",
    Helicopter: "直升机声",
    Applause: "鼓掌声",
    Gunshot: "枪声",
    velocity: "力度控制",
    "pitch-bend": "弯音控制",
    volume: "音量控制",
    panpot: "声像控制",
    expression: "情绪控制",
    "hold-pedal": "延音踏板",
    pan: "声像",
    event: "事件",
    duration: "时长",
    tick: "起始",
    value: "值",
  },
  "zh-Hant": {
    "landing-title": "signal - 線上 MIDI 編輯器",
    "app-intro": "在瀏覽器中製作音樂",
    "app-desc": "可立即使用的MIDI編輯自由軟體",
    launch: "啟動",
    platform: "支援的瀏覽器（限桌機版）：Google Chrome / Firefox / Safari",
    features: "功能",
    "feature-midi-file": "全能 MIDI 編輯器",
    "feature-midi-file-description":
      "用多軌鋼琴卷軸來自由自在地作曲吧！當然也能使用力度、滑音、表情和顫音等控制功能創造出豐富情感的曲子。",
    "feature-gm-module": "GM 相容音源",
    "feature-gm-module-description":
      "以 WebAudio API 和 AudioWorklet 建構的專用音源模組，讓你可以在瀏覽器上彈奏大量的 MIDI 音符。",
    "piano-roll": "鋼琴卷軸",
    tempo: "速度",
    "tempo-track": "速度軌",
    "feature-time-signature": "支援 4/4 以外的拍號以及高於 300 BPM 的拍速",
    "feature-time-signature-description":
      "您可使用圖形編輯器，自由更改曲目中任何地方的速度和拍號。",
    "feature-pwa": "支援 PWA",
    "feature-pwa-description":
      "瀏覽器網址列很煩嗎？您可以安裝在桌面上，直接當作一般的應用程式使用。",
    "feature-export-wav": "輸出 WAV 檔",
    "feature-midi-io": "支援 MIDI 鍵盤",
    "feature-midi-io-description":
      "您可以使用支援 Web MIDI API 的瀏覽器，連接您的 MIDI 鍵盤來錄製您的演奏，並使用硬體合成器來播放曲子。",
    "feature-export-audio": "快速匯出功能",
    "feature-export-audio-description":
      "您可以將創作的曲目匯出成 WAV 檔，在手機上播放，或作為影片的背景音樂，或將其匯入 DAW（音樂製作軟體）中。",
    "time-signature": "拍號",
    "add-time-signature": "新增拍號",
    "remove-time-signature": "刪除拍號",
    support: "說明",
    "sponsor-intro":
      "signal 是我在週末當作興趣所作的應用程式。如果您也喜歡這種能在瀏覽器上使用的輕量級作曲軟體的這種概念，請多多支持。",
    "support-github-desctiption": "用 GitHub 提出 BUG 和許願新功能",
    "become-sponsor": "想成為贊助者嗎？",
    "open-github-sponsors": "前往 GitHub Sponsors",
    "follow-twitter": "Follow 我們的 Twitter 取得最新消息",
    file: "檔案",
    "new-song": "新增",
    "open-song": "開啟",
    "save-song": "儲存",
    "save-as": "另存為",
    "song-created": "曲目已建立",
    "song-saved": "曲目已儲存",
    "untitled-song": "未命名",
    name: "名稱",
    rename: "重新命名",
    track: "音軌",
    tracks: "音軌",
    "add-track": "新增音軌",
    "delete-track": "刪除音軌",
    "duplicate-track": "複製音軌",
    channel: "頻道",
    categories: "類別",
    instruments: "樂器",
    "rhythm-track": "節奏軌",
    "conductor-track": "指揮軌",
    "track-name": "音軌名稱",
    cancel: "取消",
    ok: "確定",
    reset: "重設",
    triplet: "三連音",
    dotted: "附點",
    "confirm-new": "正在編輯曲目，您確定要新增嗎？",
    "confirm-open": "正在編輯曲目，您確定要開啟嗎？",
    "confirm-close": "正在編輯曲目，您確定要關閉嗎？",
    "auto-scroll": "自動滾動",
    help: "說明",
    close: "關閉",
    "keyboard-shortcut": "快速鍵",
    "play-pause": "播放/暫停",
    rewind: "快退",
    "fast-forward": "快進",
    "forward-rewind": "快進/快退",
    "next-previous-track": "下一音軌/上一音軌",
    "solo-mute-ghost": "獨奏/靜音/幽靈音",
    stop: "停止",
    record: "錄音",
    "pencil-tool": "鉛筆工具",
    "selection-tool": "選擇工具",
    "copy-selection": "複製選擇的內容",
    "cut-selection": "剪下選擇的內容",
    "paste-selection": "貼上選擇的內容",
    "select-all": "全選",
    "delete-selection": "刪除選擇的內容",
    "move-selection": "移動選擇的內容",
    undo: "復原",
    redo: "重做",
    cut: "剪下",
    copy: "複製",
    paste: "貼上",
    duplicate: "複製",
    delete: "刪除",
    "song-deleted": "曲目已刪除",
    "song-delete-failed": "曲目刪除失敗",
    "select-note": "選擇音符",
    "scroll-horizontally": "左右滾動",
    "scroll-vertically": "上下滾動",
    settings: "設定",
    "midi-settings": "MIDI設定",
    inputs: "輸入",
    outputs: "輸出",
    "no-inputs": "無連接的裝置",
    "one-octave-up": "+1 個八度",
    "one-octave-down": "-1 個八度",
    arrange: "編排",
    "arrangement-view": "編排視圖",
    "open-help": "打開說明",
    "event-list": "事件列表",
    "open-chat": "打開聊天視窗",
    property: "屬性",
    quantize: "量化",
    "snap-to-grid": "對齊網格",
    "export-audio": "匯出音檔",
    export: "匯出",
    "exporting-audio": "正在匯出音檔...",
    "file-type": "文件格式",
    "export-error-too-short": "曲目長度太短了",
    "set-loop-start": "設定循環開始位置",
    "set-loop-end": "設定循環結束位置",
    "switch-tab": "切換標籤",
    transpose: "移調",
    yes: "是",
    no: "否",
    "please-sign-up": "註冊後可使用雲端儲存",
    "save-changes": "是否要保存對曲目的修改？",
    "sign-in": "登入",
    "sign-out": "登出",
    "success-sign-in": "登入成功",
    files: "文件",
    "created-date": "建立日期",
    "modified-date": "修改日期",
    "cloud-beta-warning":
      "因雲端儲存功能仍處於Beta階段，請時時下載並儲存您的重要曲目。",
    "cloud-description":
      "通過登入，您可以將您的曲目儲存到雲端並隨時隨地打開繼續編輯。",
    "import-midi": "匯入 MIDI",
    "export-midi": "匯出 MIDI",
    general: "一般",
    "change-track-color": "更改音軌顏色",
    "control-settings": "設定控制功能",
    add: "新增",
    remove: "移除",
    "initialize-error": "啟動時初始化發生錯誤",
    "soundfont-save-notice": "SoundFont會儲存在瀏覽器中",
    "loading-external-midi": "正在讀取MIDI檔...",
    initializing: "啟動中...",
    profile: "個人資訊",
    "edit-profile": "編輯個人資訊",
    "signin-to-edit-profile": "登入以編輯個人資訊",
    "display-name": "顯示名稱",
    bio: "自我介紹",
    save: "儲存",
    "recent-tracks": "最近的曲目",
    "publish-notice": "一旦公開樂曲，其他的使用者也將可以聆聽您的曲目。",
    "published-notice": "您的曲目已公開，其他人也可聆聽您的曲目。",
    publish: "公開",
    unpublish: "非公開",
    "publish-song": "將曲目公開",
    "song-published": "曲目已設為公開",
    "song-unpublished": "曲目已設為非公開",
    "share-my-song-text":
      "🎶 我用signal做了一首曲子囉！🎹✨\n來聽聽看我的MIDI作品吧！🎧👇\n#midi #signalmidi @signalmidi",
    "publish-rules":
      "重要通知：本網站只允許發佈您自己創作的音樂作品。根據著作權法，請確保您是音樂作品的著作權持有者，或已獲得明確許可。未經授權公開他人音樂或受著作權保護的作品是法律所禁止的。如果發現此類違規行為，您的貼文可能會被刪除，且您的帳號可能會受到限制。我們鼓勵您分享創意和原創作品，共同促進我們社群的健康成長。",
    /* MIDI Instrument Categories */
    Piano: "鋼琴",
    "Chromatic Percussion": "固定音高敲擊樂器",
    Organ: "風琴",
    Guitar: "吉他",
    Bass: "貝斯",
    Strings: "弦樂器",
    Ensemble: "合奏",
    Brass: "銅管樂器",
    Reed: "簧樂器",
    Pipe: "管樂器",
    "Synth Lead": "合成音主旋律",
    "Synth Pad": "合成音和弦襯底",
    "Synth Effects": "合成音效果",
    Ethnic: "民族樂器",
    Percussive: "打擊樂器",
    "Sound effects": "特殊音效",
    /* MIDI Instruments */
    /* 翻訳参考：https://zh.wikipedia.org/zh-tw/General_MIDI */
    "Acoustic Grand Piano": "平臺鋼琴",
    "Bright Acoustic Piano": "亮音鋼琴",
    "Electric Grand Piano": "電鋼琴",
    "Honky-tonk Piano": "酒吧鋼琴",
    "Electric Piano 1": "電鋼琴1",
    "Electric Piano 2": "電鋼琴2",
    Harpsichord: "大鍵琴",
    Clavinet: "電翼琴",
    Celesta: "鋼片琴",
    Glockenspiel: "鐘琴",
    "Music Box": "音樂盒",
    Vibraphone: "顫音琴",
    Marimba: "馬林巴琴",
    Xylophone: "木琴",
    "Tubular Bells": "管鐘",
    Dulcimer: "洋琴",
    "Drawbar Organ": "音栓風琴",
    "Percussive Organ": "敲擊風琴",
    "Rock Organ": "搖滾風琴",
    "Church Organ": "教堂管風琴",
    "Reed Organ": "簧風琴",
    Accordion: "手風琴",
    Harmonica: "口琴",
    "Tango Accordion": "探戈手風琴",
    "Acoustic Guitar (nylon)": "木吉他（尼龍弦）",
    "Acoustic Guitar (steel)": "木吉他（鋼弦）",
    "Electric Guitar (jazz)": "電吉他（爵士）",
    "Electric Guitar (clean)": "電吉他（原音）",
    "Electric Guitar (muted)": "電吉他（悶音）",
    "Overdriven Guitar": "電吉他（破音）",
    "Distortion Guitar": "電吉他（失真）",
    "Guitar Harmonics": "吉他泛音",
    "Acoustic Bass": "民謠貝斯",
    "Electric Bass (finger)": "電貝斯（指奏）",
    "Electric Bass (pick)": "電貝斯（撥奏）",
    "Fretless Bass": "無格貝斯",
    "Slap Bass 1": "捶鉤貝斯1",
    "Slap Bass 2": "捶鉤貝斯2",
    "Synth Bass 1": "合成貝斯1",
    "Synth Bass 2": "合成貝斯2",
    Violin: "小提琴",
    Viola: "中提琴",
    Cello: "大提琴",
    Contrabass: "低音大提琴",
    "Tremolo Strings": "顫弓弦樂",
    "Pizzicato Strings": "彈撥弦樂",
    "Orchestral Harp": "豎琴",
    Timpani: "定音鼓",
    "String Ensemble 1": "弦樂合奏1",
    "String Ensemble 2": "弦樂合奏2",
    "Synth Strings 1": "合成弦樂1",
    "Synth Strings 2": "合成弦樂2",
    "Choir Aahs": "人聲「啊」",
    "Voice Oohs": "人聲「喔」",
    "Synth Choir": "合成人聲",
    "Orchestra Hit": "交響打擊樂",
    Trumpet: "小號",
    Trombone: "長號",
    Tuba: "低音號",
    "Muted Trumpet": "悶音小號",
    "French Horn": "法國號",
    "Brass Section": "銅管樂",
    "Synth Brass 1": "合成銅管1",
    "Synth Brass 2": "合成銅管2",
    "Soprano Sax": "高音薩克斯風",
    "Alto Sax": "中音薩克斯風",
    "Tenor Sax": "次中音薩克斯風",
    "Baritone Sax": "上低音薩克斯風",
    Oboe: "雙簧管",
    "English Horn": "英國管",
    Bassoon: "低音管",
    Clarinet: "單簧管",
    Piccolo: "短笛",
    Flute: "長笛",
    Recorder: "直笛",
    "Pan Flute": "排簫",
    "Blown Bottle": "瓶笛",
    Shakuhachi: "尺八",
    Whistle: "口哨",
    Ocarina: "陶笛",
    "Lead 1 (square)": "方波",
    "Lead 2 (sawtooth)": "鋸齒波",
    "Lead 3 (calliope)": "汽笛風琴",
    "Lead 4 (chiff)": "合成吹管",
    "Lead 5 (charang)": "合成電吉他",
    "Lead 6 (voice)": "人聲鍵盤",
    "Lead 7 (fifths)": "五度音",
    "Lead 8 (bass + lead)": "貝斯吉他合奏",
    "Pad 1 (new age)": "新世紀",
    "Pad 2 (warm)": "溫暖",
    "Pad 3 (polysynth)": "多重合音",
    "Pad 4 (choir)": "人聲合唱",
    "Pad 5 (bowed)": "玻璃",
    "Pad 6 (metallic)": "金屬",
    "Pad 7 (halo)": "光暈",
    "Pad 8 (sweep)": "掃弦",
    "FX 1 (rain)": "雨",
    "FX 2 (soundtrack)": "電影音效",
    "FX 3 (crystal)": "水晶",
    "FX 4 (atmosphere)": "氣氛",
    "FX 5 (brightness)": "明亮",
    "FX 6 (goblins)": "魅影",
    "FX 7 (echoes)": "回音",
    "FX 8 (sci-fi)": "科幻",
    Sitar: "西塔琴",
    Banjo: "斑鳩琴",
    Shamisen: "三味線",
    Koto: "古箏",
    Kalimba: "卡林巴鐵片琴",
    Bagpipe: "蘇格蘭風笛",
    Fiddle: "古提琴",
    Shanai: "印度嗩吶",
    "Tinkle Bell": "叮噹鈴",
    Agogo: "阿哥哥鼓",
    "Steel Drums": "鋼鼓",
    Woodblock: "木魚",
    "Taiko Drum": "太鼓",
    "Melodic Tom": "定音筒鼓",
    "Synth Drum": "合成鼓",
    "Reverse Cymbal": "逆轉鈸聲",
    "Guitar Fret Noise": "吉他滑弦雜音",
    "Breath Noise": "呼吸雜音",
    Seashore: "海岸",
    "Bird Tweet": "鳥鳴",
    "Telephone Ring": "電話鈴聲",
    Helicopter: "直升機",
    Applause: "拍手",
    Gunshot: "槍聲",
    velocity: "力度控制",
    "pitch-bend": "滑音控制",
    volume: "音量控制",
    panpot: "相位控制",
    expression: "表情控制",
    "hold-pedal": "延音控制",
    pan: "相位",
    event: "事件",
    duration: "持續",
    tick: "起始",
    value: "值",
  },
} as { [key: string]: { [key: string]: string } }
